OriginProtocol/origin

- README.md
- src/components/demo-step-2.js
- src/services/ipfs-service.js
Note: Apologies for my editor creating "edits" by removing trailing spaces. I can re-submit without those if desired. 
- A few updates to the readme based on my experience getting it running on MacOS. 
- Added a catch() to handle ipfs failure when the gateway is down. For now it just displays generic ugly javascript alert() box. Slightly better than doing nothing.
> Catch ipfs error, and Readme edits

- src/services/ipfs-service.js
Forgot to bring this change along in the last PR.
> Use ENV vars for ipfsDomain/ipfsApiPort when available

- src/components/app.js
- src/components/listing-create.js
- src/components/scroll-to-top.js
Fix for #72 Handle scrolling correctly will always scroll to top when there is a routing page change.
Does not fix scroll to top on the grid, as that requires the routing changes in #64 Add paging to URLs / Router that I am looking into separately.
> add ScrollToTop component for routing

- src/components/listing-detail.js
The price is set to the string `"Loading..."` by default. Because the
announcement form does not have a price field, this string is used in
the price display in the listing preview. The string is converted to the
number `NaN` when rendered.
With this change, the price is just displayed as 0 (the value that will
get stored on the listing contract and displayed once the listing is
created).
Not sure this is the best way to fix the issue, but it seemed like the simplest solution (as opposed to a more robust but complex solution that would require some refactoring).
> Fix NaN price display in announcement creation

- package-lock.json
- package.json
- public/schemas/announcements.json
- public/schemas/for-sale.json
- public/schemas/housing.json
- public/schemas/services.json
- public/schemas/tickets.json
- public/schemas/transportation.json
1) Updated $schema":"http://json-schema.org/draft-04/schema#" to 
"$schema":"http://json-schema.org/draft-06/schema#"
2) Changed types on all min/max field values from string to integer.
Original draft-04 was throwing an error in my linux Firefox (v58.0.2) dev console:
"Error: no schema with key or ref".
I changed the source json $schema values to use draft-06, and then saw a more useful error message. Can't recall the exact error syntax, but it referred to all of the min/max fields being invalid string types, which I then fixed to be integers. That solved the issue.
I suspect the original draft-04 schemas were working in other os/browser environments, due to a less stringent JVM running in those browsers. Perhaps the linux Firefox JVM was less forgiving?
Neil
> json updates to 6 files in public/schemas

- src/components/listing-detail.js
Origin.js was changed to parse the JSON on retrieval in https://github.com/OriginProtocol/platform/commit/4187d47a7fb7eb7ab720a27f0e0ef8617c4b353a#diff-ff15870115f22edd2922952fe9681678
This is an update of the demo-dapp so we don't try to parse the JSON twice.
It still has a reference to the `data` property from the response even though the `data` property comes from [OriginService](https://github.com/OriginProtocol/platform/blob/develop/packages/origin.js/src/origin-service.js#L11). This isn't ideal and the `data` property should be hidden from the library consumers.
> Don't parse JSON from IPFS twice

- src/components/listing-card.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/components/listings-grid.js
- src/services/origin.js
https://github.com/OriginProtocol/platform/pull/82 will break the demo dapp without this PR. Because the origin service is now a class that must be instantiated, and because we only want to instantiate it once in the entire app, I opted to create this service which instantiates the class and then exports the instance to make it available to the rest of the app.
> Create origin service which exports an instantiated Origin class

- src/components/app.js
- src/components/listing-card.js
- src/components/listing-detail.js
See https://github.com/OriginProtocol/origin-js/issues/112 for the issue this fixes.
- Use listing address in listing detail URL.
- Get listing by address using new Listing.get API
This requires https://github.com/OriginProtocol/origin-js/pull/113 on the origin-js side.
> 🔧 Use listing address in listing detail URL.

- src/css/app.css
This fixes an issue with excess white space appearing below the footer on small screens. I think the code was a remnant of a prior iteration of the sticky footer. After 22b09fb, the footer will still stick below the viewport on empty pages.
_This branch is currently visible at http://demo-micah.herokuapp.com/_ ✅
> Remove fixed height from root container

- src/components/app.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/css/app.css
When a user rejects a transaction via the provider's popup window, demo-dapp needs to handle that gracefully and allow the user to reset the state of the app to remove the "waiting" modal. 
This PR uses the error modal styling from the Profile page and implements it on the "Create Listing" and "Listing Detail" pages.
> Issue #62 - Handle MetaMask errors and allow user to reset state

- src/pages/profile/Profile.js
- src/pages/profile/_Wallet.js
This adds a link to the raw identity data in the wallet to satisfy #158. It uses the hard-coded hostname `erc725.originprotocol.com` in the link. This should be merged after https://github.com/OriginProtocol/origin-js/pull/188.
> Identity link

- src/services/origin.js
Fixes an important bug discovered by @micahalcorn . We weren't properly falling back to the default bridge server url.
> Properly fall back to default bridge server url

- .gitignore
build_webpack was in .gitignore back in december: https://github.com/OriginProtocol/demo-dapp/commit/538d9b6235598db348e7cce88be918aca2a373bf#diff-a084b794bc0759e7a6b77810e01874f2
Can't remember why we took it out. Seems there were some files in there that *did* need to be in git? @Nick? 
I just feel dirty always seeing this:
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
build_webpack/
```
> Add build_webpack to .gitignore

- package-lock.json
- package.json
- src/components/web3-provider.js
- src/services/origin.js
**_This depends on a merge of https://github.com/OriginProtocol/origin-js/pull/202._**
If MetaMask is not installed and a native `web3` object is not provided by the browser, then the DApp will fail to render due to the exception thrown [here](https://github.com/OriginProtocol/origin-js/blob/develop/src/services/contract-service.js#L17). This is the critical step to satisfy https://github.com/OriginProtocol/demo-dapp/issues/128, which should probably be broken up into several issues.
> Pass web3 to Origin.js

- src/css/app.css
This issue isn't occuring for @micahalcorn even though we're using the same version of Chrome. Since the issue is related to line height, we think it might (?) be related to machine font configuration. We're not sure, but we don't want to have css that only works for some people.
> Fix chrome bug where profile dropdown was invisible

- src/actions/Listing.js
- src/components/listing-card.js
- src/components/listings-grid.js
- src/reducers/Listings.js
A possible solution for: https://github.com/OriginProtocol/demo-dapp/issues/221
Hides listings that have been flagged in the `hide_list` branch - by address instead of by index. We're transitioning away from indices to addresses.
The only awkwardness of this implementation is that on a page with flagged listings, the grid won't be completely filled up. For example:
We can fix this eventually, it will just require updating the API to return listing addresses instead of indices when fetching all listings.
- Change [this line](https://github.com/OriginProtocol/demo-dapp/blob/develop/src/actions/Listing.js#L35) to be `if (true) {`.
- Change [this line](https://github.com/OriginProtocol/demo-dapp/blob/develop/src/actions/Listing.js#L37) to be …
> Don't render listings that have been hidden by address

- src/components/etherscan-link.js
- src/components/purchase-detail.js
- src/components/user-card.js
- src/css/app.css
- src/pages/profile/_Wallet.js
- src/pages/purchases/transaction-event.js
Adds a universal component for displaying Etherscan links. You simply pass in a hash for an address or transaction and it will create an Etherscan link that points to the right network (rinkeby.etherscan.io, etc) and the right URL path (/address or /tx).
> Add component for displaying Etherscan links

- package.json
Two changes:
- Use npx so that we are using local rather than global webpack-dev-server install
- Set the host option to 0.0.0.0. This does not impact the normal workflow, and it enables port forwarding to work correctly using docker containers
If you don't mind @micahalcorn , can you make sure running `npm start` with this change works for you?
> Tweak dev run command

- src/components/footer.js
- Adding a language-aware param in the `href` URLs for whitepaper and product briefing links in the footer
> Issue #245 - localize whitepaper and product briefing links

- crowdin.yml
Fixing the below error that appeared in the Crowdin console. This change will just affect the directory name where Crowdin will place the translated files when it creates PRs. The script that relies on this hasn't been written yet, so there is no change needed outside of this one file.
> Crowdin integration - fix error in Crowdin console 

- translations/scripts/prepareMessagesPlugin.js
@micahalcorn - this fixes the bug you found where errors in the translation webpack plugin weren't being handled correctly. Now it correctly throws the error in the console and causes the build to fail.
> Fixing i18n webpack plugin error handling

- public/dev.html
- public/index.html
This enables in-context translation via Crowdin by using a query string `?translator=true`:
https://support.crowdin.com/in-context-localization/
I didn't document it yet because it seems like it's going to be kind of a pain to use and I'd rather try it out with the one translator who has asked for it before rolling it out more broadly.
To enable in-context translation in a new language, we have to:
1) Go here: https://crowdin.com/project/originprotocol/settings#in-context
2) select the language from the dropdown menu and build/download a special JSON file that has Crowdin-generated IDs for each message that needs translation
3) Commit that file to the DApp in a new directory like `/translations/languages/<new lang name>/all-messages.json` and deploy it
> Adding script for Crowdin in-context translations

- src/components/purchase-detail.js
- translations/all-messages.json
- translations/messages/src/components/purchase-detail.json
This adds some UX feedback during the transaction processing for purchase stage updates. As we discussed recently, this should eventually be replaced by https://github.com/OriginProtocol/origin-dapp/issues/251 in accordance with https://github.com/OriginProtocol/origin-dapp/issues/85. Until then, this provides at least some improvement.
> Show modal during purchase stage updates

- src/components/Identicon.js
This replaces the square red box generated by IdenticonJS with a blank white circle when the wallet address is not set.
> Issue #288 - render white circle for wallet icon when no address is provided

- src/pages/profile/_ProvisionedChanges.js
Fix broken reference which caused email attestation to break (blank screen and console errors) after a correct verification code is submitted.
> Fix wrong reference to intlMessages attribute

- src/components/transaction.js
I don't know if this is only a local blockchain quirk or not, but I know that we can't entirely rely on block times since they can be manipulated by miners. This adds a safeguard so that [`fromNow`](https://momentjs.com/docs/#/displaying/fromnow/) does not produce "in a few seconds" or whatever.
> Deal with block time in the future

- src/components/purchase-detail.js
This is a temporary patch related to https://github.com/OriginProtocol/origin-js/issues/299. While still not pleasant, it is more effective than the prior `setTimeout` strategy.
> Deal with delayed purchase state changes

- crowdin.yml
@wanderingstan 
Just a small tweak so that Crowdin commits the translated files to a directory named with the language's locale instead of the language name. Per Crowdin docs here:
https://support.crowdin.com/configuration-file/#placeholders
This will set the stage for another PR with more changes to make the scripts and stuff work with this new naming convention.
Issue: https://github.com/OriginProtocol/origin-dapp/issues/340
> Change crowdin config to use local not lang name

- package-lock.json
- package.json
- webpack.config.js
- Add a watch exclusion for reloads on `node_modules` except for `origin-js` so `origin-dapp` recompiles on changes to `origin-js` in `origin-box`.
- Implement a source map loader to load source maps to allow debugging of `origin-js` files in browser ([reference](https://github.com/OriginProtocol/origin-box/issues/30)).
- Change devtool source map type to inline because it should be slightly faster.
- Add a few other config options for webpack-dev-server so they are all handled here instead of at the command line in `origin-box`.
> Webpack config tweaks for origin-box

- src/css/app.css
In https://github.com/OriginProtocol/origin-dapp/pull/303 there was an error where some of the css changes affected too many form-controls.
> Fix that some css properties apply only to modal content

- src/components/conversation.js
- src/components/dropdowns/notifications.js
- src/components/listing-detail.js
- src/components/my-listings.js
- src/components/my-sale-card.js
- src/components/notification.js
- src/components/notifications.js
This repairs the references to buyers and sellers in order to display the "About the {user}" cards, etc. This will need to be revisited once https://github.com/OriginProtocol/origin-js/issues/378 is settled. I will make another issue for that.
> Repair user references

- src/components/boost-slider.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/utils/boostUtils.js
- src/utils/listing.js
This wires up the boost slider to origin.js so that boost value gets stored as commission price in IPFS. 
This can be merged when approved. There is still be additional work to do in origin.js to enable payment of commissions, etc.
> Wire up boost value to origin.js commissions

- src/utils/listing.js
We have a function that maps the names of things in origin.js to the names of things in the dapp. The "description" field wasn’t being carried over into the dapp.
Fixed that.
> Description field wasn’t being carried over into the dapp.

- Dockerfile
Since `WORKDIR` has already been set to `/src`, it is unnecessary to use absolute paths to target locations within this working directory. Using `./` is enough as commands following `WORKDIR` will take `/src` as the current location. 
Only when a different path outside of `/src` needs to be accessed, like `/bin/docker-truffle.sh` in `COPY bin/docker-truffle.sh /bin/docker-truffle.sh`, would we need to use absolute paths.
> Changed unnecessary absolute paths

- src/components/my-listings.js
- src/components/my-purchases.js
- src/components/my-sales.js
I'm not positive but I think a recent refactor probably changed the behavior of the marketplace.getListings origin-js API. It now expects the options "idsOnly" to be set to return listingIds, otherwise it returns Listings.
> Fix call to marketplace.getListings to add idsOnly option

- src/components/listing-detail.js
- src/components/purchase-detail.js
- src/utils/listing.js
After the changes introduced in [origin-js PR 451](https://github.com/OriginProtocol/origin-js/pull/451), it is no longer needed to pass the "schemaVersion" field when calling origin-js marketplace methods that store data in IPFS.
> Remove schemaVersion in IPFS data

- src/components/listing-create.js
- translations/all-messages.json
- translations/messages/src/components/listing-create.json
- ~~[ ] Map any new environment variables with a default value in the Webpack config~~
- ~~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)~~
[Issue #496](https://github.com/OriginProtocol/origin-dapp/issues/496)
Problem:
- Listing creation is a multi-step/multi-component process where the state is handled in the component(s). So if a user navigates away from creating a listing (browser back button or router link), their progress is lost.
Solution:
- use react-router to prompt a warning when a user attempts to navigate from the create a listing process if they have started.
> Listing Creation: Prevent Accidental Form Unload

- src/components/listing-create.js
This repairs an `offset-` issue with a column, improves the responsive sizing, and changes the unload condition so that the prompt does not appear after the listing is created.
> Improve Columns & Prompt

- src/components/form-widgets/price-field.js
This bug was happening because the price field form widget wasn't calling the callback that notified the the parent form of the user's input until after the `getFiatPrice()` method returned a value. If `getFiatPrice()` failed, the widget's callback never was called and the parent form never knew that a price had been entered, so the validation failed since price is a required field.
Now, the callback gets called regardless of the success or failure of `getFiatPrice()`.
> Issue #513 - create listing - fix price validation bug

- src/components/boost-slider.js
- src/components/listing-create.js
This allows a seller to go backward from step 4️⃣ to 3️⃣ and maintain the selected boost level. It also reactively updates the wallet balance after the boosted listing is created.
> Boosted Listing Creation Improvements

- src/components/listing-create.js
- src/components/listings-grid.js
- src/components/my-sale-card.js
- src/css/app.css
- translations/all-messages.json
- translations/messages/src/components/my-sale-card.json
Buttons on create listing page were touching on smaller screens. Resized them to match the UI mockup and maintain spacing on smaller screen sizes. 
https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b7538b2636eb55062e63a77
> resize btns according to design spec and to prevent overlap

- src/components/dropdowns/messages.js
- src/components/purchase-detail.js
- This works, but it isn't ideal
- It would be nice if the `startConversing()` method accepted a confirmation callback and/or returned a promise. This would prevent the need to do the polling that I'm doing here to know if messaging has been enabled so the user can proceed with the arbitration process.
> Wire up "enable messaging" button in arbitration process

- src/components/purchase-detail.js
- src/pages/purchases/transaction-event.js
- translations/all-messages.json
- translations/messages/src/components/purchase-detail.json
Currently, dispute transactions are not shown on the list of transactions. This is confusing when a purchase is in dispute, since there is no trace of it in the transactions.
> Show dispute transactions on purchases/offers.

- src/components/arbitration.js
- src/components/purchase-detail.js
- src/pages/purchases/transaction-event.js
- translations/all-messages.json
- translations/messages/src/components/purchase-detail.json
- PurchaseDetails -  Transactions now show the correct from address
- TransactionEvent - Refactored “transaction” to “event” inside the component, since it’s an event
- TransactionEvent - Now loads the transaction origin address if no from address is passed in
- Arbitration - Updated to use new props for TransactionEvent. The event display looks out of date, so I didn’t adjust things further.
@micahalcorn I didn't test the arbitration page, since I'm not sure how to get it going. Feel free to make any other changes you want to the offer page from here.
> Fix display of transaction from addresses on offer page.

- src/services/origin.js
- webpack.config.js
Didn't have time to test this yet - @micahalcorn can you check that this works with https://github.com/OriginProtocol/origin-js/pull/549 ? Just need to make sure that offers can still be created and viewed in the Dapp. 🙏
> Set origin-js affiliate/arbitrator from env vars

- src/components/dapp-info.js
After merging for the new style, some headings were getting shown twice. 
Fixed so errors get shown nicer.
> Remove redundant headings. 

- src/actions/Profile.js
- src/components/transaction-message.js
- src/components/transaction.js
- translations/all-messages.json
- translations/messages/src/components/transaction-message.json
When publishing profile changes transaction now displays in transaction dropdown. Previously it just showed 1 pending transaction but no details about that transaction. 
**Solves Issue:** https://github.com/OriginProtocol/origin-dapp/pull/617#issuecomment-425566987
> add create profile type transaction to display in transactions dropdown

- src/components/listing-create.js
- src/css/app.css
- translations/all-messages.json
- translations/messages/src/components/listing-create.json
I don't see a way to prevent the error from being shown by `react-jsonschema-form` programmatically, so I did it with CSS.
I also added a warning message because the form didn't notify you when an error occurred, so you'd click "continue" and nothing would happen. The UX wasn't so bad before because the showing of the error summary caused the page to jump down and the error text came into view.
Here's the new warning message:
Issue: https://github.com/OriginProtocol/origin-dapp/issues/623
> Hide create listing form error summary

- src/components/arbitration.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/components/purchase-detail.js
- src/css/app.css
- src/pages/profile/Profile.js
- src/pages/user/User.js
per request from @joshfraser, following code from here:
https://medium.com/@kevinsimper/react-newline-to-break-nl2br-a1c240ba746
Newlines get converted to <br> tags, nothing more. 
We might consider supporting full-on markdown (eg [via this package](https://www.npmjs.com/package/react-markdown)) , but we'd want to disable images, and have a bigger discussion of whether markdown is the officially recommended format for Origin listings.
> Render new lines in descriptions

- src/components/messages.js
Uses `created` instead of `index` ✔️
> Consistent Messages Sort

- package-lock.json
- package.json
Upgrade to using origin npm 0.8.3
> Update DApp to use origin 0.8.3

- src/components/dropdowns/connectivity.js
- src/components/dropdowns/messages.js
- src/components/dropdowns/notifications.js
- src/components/dropdowns/transactions.js
- src/components/dropdowns/user.js
- src/components/notification.js
- src/pages/profile/Profile.js
The default behavior for a Bootstrap dropdown is for it to hide on any click (inside or outside of the menu). I had previously disabled this in some cases but it was inconsistent.
With these changes, the default behavior is for a dropdown to only hide if the nav icon (or its parent) is clicked. Other various clicks will no longer affect the dropdown(s). Manual "toggle" calls are now fired selectively where appropriate. This will be an ongoing effort.
This is one of several things that should be more thoughtfully engineered as a part of a broader effort to remove jQuery and implement our own vanilla components.
> Dropdown Behavior Improvements

- src/components/search/price-filter.js
Solves the problem where search fails when using price filter. 
The problem was [this Pull Request](https://github.com/OriginProtocol/origin-dapp/pull/604/files#diff-272e0265387bbb386b63efe467f8450fL43) the whole bug is probably a result of bad master merge. 
Solves issue: https://github.com/OriginProtocol/origin-js/issues/595
> Price filter query fix

- src/actions/Listing.js
As part of mono-repo migration, we'll rename origin-dapp to origin. This will break fetching the hide/features lists until we can deploy a DApp change to point to origin. But it may take a few hours to successfully deploy any DApp change using the new mono-repo.
As a temporary workaround, I duplicated the lists to origin-bridge and this PRs points to DApp to origin-bridge repo for fetching the list.
> Fetch hide/feature lists from origin-bridge

- .travis.yml
- origin-js/contracts/test-alt/MarketplaceLib.js
- origin-js/contracts/test-alt/TokenLib.js
- origin-js/package-lock.json
This is a short-term hack to fix the Travis build. Better (but will take a bit longer) fix is to refactor origin-faucet and origin-js/contracts/test-alt to remove their dependency. Probably by creating a separate token-lib or equivalent package.
> Temporary hack to fix Travis CI build

- origin-discovery/listener/listener.js
There are a few early listings that have malformed offer data with missing arbitrator.
Currently the indexer will get stuck on those and not make progress (it will fail, exit, restart over and over).
With this change, after max number of retries is reached, the indexer will log then skip the malformed entry.
> [EventListener] Do not exit on errors fetching data

- .gitignore
- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- deployment/kubernetes/charts/origin/templates/dapp-redirect.ingress.yaml
- deployment/kubernetes/charts/origin/templates/dapp.ingress.yaml
- deployment/kubernetes/charts/origin/templates/discovery.ingress.yaml
- deployment/kubernetes/charts/origin/templates/faucet.ingress.yaml
- deployment/kubernetes/charts/origin/templates/ipfs.ingress.yaml
- deployment/kubernetes/charts/origin/templates/messaging.ingress.yaml
- deployment/kubernetes/configure-cluster.sh
- deployment/kubernetes/values/values-dev.yaml
- Adds permanent redirect for `demo.originprotocol.com` to `dapp.originprotocol.com`
- Adds `gateway.originprotocol.com` as a valid host for IPFS servers
- Snuck in a few fixes for `.gitignore`
- Added better isolation for the nginx ingress by using separate classes for `dev`, `staging` and `prod`
- Added flags to solve to solve #743 
- Added flags to enable Prometheus metrics on ingress
- Updated some containers for dev
@franckc the deployment is currently running this so please merge before doing any new deploys or it'll be undone. Merci!
> Add redirects to nginx ingress and configuration changes

- readme.md
We didn't have a top level readme for the new monorepo. Here's a start.
> 🐨 Add top level readme page

- deployment/dockerfiles/dev/origin-dapp
- deployment/dockerfiles/prod/origin-dapp
- deployment/dockerfiles/staging/origin-dapp
Set INSTRUCTIONS_URL to point to Mainnet blog post.
> [DApp] Set INSTRUCTIONS_URL to point to Mainnet blog post

- origin-discovery/listener/listener.js
Adds a `—trail-behind-blocks=N` parameter that forces the listener to stay N blocks behind the current block. Allows you to wait for more confirmations before processing.
Closes https://github.com/OriginProtocol/origin-js/issues/407
> 🎧 Listener - wait N confirmations before processing events.

- deployment/kubernetes/charts/origin/scripts/start-event-listener.sh
Wait 1 block confirmation before processing events. This should help with the out-of-sync node Infura issue we've seen (though currently it is mitigated by retries).
> [EventListener] Wait 1 block confirmation before processing events

- origin-discovery/listener/listener.js
The parsed `url.host` includes the port, which will then be redundant when constructing a new `request` if also included from `url.port` causing an `ENOTFOUND`. This prevents such a case.
> URL Parsing Fix

- deployment/kubernetes/values/secrets-staging.enc.yaml
- origin-js/contracts/migrations/12_add_staging_issuer.js
Currently, the origin bridge server is using the same attestation signing key as prod because it is using the same ENVKEY variables.
For more context, see discussion in [this issue](https://github.com/OriginProtocol/origin-js/issues/591).
I generated a new signing private key for staging and set it as value in the ENVKEY for bridge server on staging.
This PR makes the necessary changes to start using it:
- Adds a migration script to run on Rinkeby for adding the new key
- Update the bridge server staging configuration to use the proper ENVKEY (so far it was using prod )
> [Attestation] Update staging attestation signing key

- deployment/kubernetes/charts/origin/templates/_helpers.tpl
- deployment/kubernetes/charts/origin/templates/eth.ingress.yaml
- ~~[ ] Wrap any new text/strings for translation~~
- ~~[ ] Map any new environment variables with a default value in the Webpack config~~
- ~~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)~~
- Moves the host for our mainnet Ethereum node from `eth.prod.originprotocol.com` to `eth.originprotocol.com`.
> Update deployment eth node hostnames

- deployment/dockerfiles/dev/event-listener
- deployment/dockerfiles/prod/event-listener
- deployment/dockerfiles/staging/event-listener
- docker-compose.yml
- origin-discovery/listener/README.md
- origin-discovery/listener/listener.js
The event-listener had a couple of issues:
- errors when validating offers due to a couple of addresses (arbitrator and affiliate) not being passed to the Origin constructor.
- indexing slowness on Mainnet caused by calls to scan events since inception as opposed to Origin block epoch.
This PR fixes the call to the Origin constructor in event-listener and sets env variables in the various environments.
> [EventListener] Fix call to Origin constructor

- origin-js/src/resources/messaging.js
- origin-js/src/utils/cookieStorage.js
This increases the expiration of ephemeral private keys from 7 to 90 days. It also resolves an issue where the cookies for the key and phrase were getting out of sync.
> We Fix Messaging

- .travis.yml
Label jobs so that it's easier to identify them on the Travis CI build page.
> [Travis] Add names to jobs

- origin-discovery/listener/listener.js
- origin-discovery/package-lock.json
- origin-discovery/package.json
This adds [dotenv](https://www.npmjs.com/package/dotenv) to support running the listener in a local environment. It also fixes a log message for the IPFS URL, for which the default is also changed.
Note ⚠️ The `--ipfs-url` will now need to be passed in for any containers expecting to use `http://origin-js:8080`. I am assuming that there are no consequences to the other discover code as a result of these changes.
> Dotenv & IPFS References

- origin-dapp/src/components/listing-detail.js
This should resolve the issue of getting `this.props.formatMessage is not a function` intermittently on some listing detail pages. However, the issue resolved here only addresses the symptom. There is an underlying error occurring that causes the localized message to appear; probably [this one](https://github.com/OriginProtocol/origin/issues/799).
> Repair Method Call

- deployment/kubernetes/charts/origin/templates/website-redirect.ingress.yaml
- Configures a redirect for originprotocol.com -> www.originprotocol.com so we aren't dependent on wwwizer.com and it also works with SSL.
@franckc this needs to be in your local repo before we do any more deploys or it'll disappear. :space_invader:
> Add website redirect

- origin-js/scripts/helpers/deploy-contracts.js
Recommend to reject() the process if truffle compile-all got failure,
just little change of code logic.
Signed-off-by: Zhilong Liu <zhilong.liu1028@gmail.com>
> Abort deploying if contracts migrated failure

- .travis.yml
We still have build problems with Node 10.x, which Travis automatically
started using today, because 10.x started being LTS today.
> Make Travis use Node 8

- ipfs-proxy/src/index.js
Prevents a crash of `ipfs-proxy` container when 404 response should be returned
> fix bug that crashed ipfs proxy when 404 status should be reported

- origin-discovery/listener/listener.js
Small tweak to make EnvKey optional for event-listener. We want the listener to remain configurable via CLI so I just added a try/catch so that it can carry on if the ENVKEY environment variable is not set.
> Make EnvKey optional for listener

- deployment/kubernetes/charts/origin/scripts/start-event-listener.sh
- deployment/kubernetes/charts/origin/templates/eventlistener.deployment.yaml
NAMESPACE needs to be defined since it is used by start-event-listener.sh
Now, after that is fixed, there is still something broken I think with the event-listener webhook to the notification server. From a shell within the event-listener container, I could not connect to the notification server:
```# curl http://notifications.staging.svc.cluster.local:3456 
curl: (6) Could not resolve host: notifications.staging.svc.cluster.local
```
> Add NAMESPACE env var to event-listener container

- origin-notifications/app.js
The events sent by the event-listener and processed by the notification server exceed the default 100kb limit since they may include user profile with picture from seller + buyer. Each pic can be up to 500x500 which is 750kb uncompressed. So those events could be in the order of couple of MB. There is no reason though to keep the limit on notification server very tight so I'm setting it to 10MB for now.
> [Notification] Increase max payload size to 10MB

- origin-discovery/listener/listener.js
- origin-notifications/app.js
A few fixes to harden the notification server and its integration in the event listener:
- Fix bug in notifier where non offer events (for ex. ListingCreated) would cause a crash
- Do not crash the listener if a webhook calls fails: after maximum number of reties reached, skip the webhook call.
> [Notifications] Do no crash server when receiving non offer related events

- docker-compose.yml
- add contracts build dir to `event-listener` container. Enabling event listener to interact with local web3
- add some more volumes in `origin-js` developers might want to interact with from the host machine
> Add more docker volume mappings

- origin-dapp/src/components/form-widgets/photo-picker.js
I'm not sure what caused this to break (assuming maybe a new version of `react-beautiful-dnd`? But it just needs a non-zero value for `draggableId` and it works fine
Ticket here: https://github.com/OriginProtocol/origin/issues/928
>  Small fix for drag/drop that was breaking listing create

- origin-dapp/public/images/caret-down.svg
- origin-dapp/public/images/caret-up.svg
- origin-dapp/src/components/badges.js
- origin-dapp/src/components/warning.js
- origin-dapp/src/css/app.css
Welcome message on mobile devices takes up less vertical space now and is expandable when clicked on.
- ~[ ] Map any new environment variables with a default value in the Webpack config~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)~
**Fixes issue:** https://github.com/OriginProtocol/origin/issues/934
**Open Zepplin designs:**
https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5bd24ee31311fc09c26a2484
https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5bd24ee513f4bb09f4dfbda9
Looks like this:
> Smaller welcome message on mobile devices

- origin-discovery/devops/es-cli.js
Elasticsearch formats the output of aliases in such manner that there can be multiple whitespaces between index and alias words.
> Fix elasticsearch alias bug

- development/dockerfiles/ipfs-proxy
- ipfs-proxy/package-lock.json
- ipfs-proxy/package.json
- package-lock.json
- package.json
The ipfs-proxy [dev:start command](https://github.com/OriginProtocol/origin/blob/master/ipfs-proxy/package.json#L9) uses nodemon but it is not installed as a dependency so it was failing to start for me in origin-box.
> [ipfs-proxy] Add nodemon as dev dependency

- origin-js/scripts/helpers/start-ganache.js
1. In April, [`blocktime` was renamed to `blockTime`](https://github.com/trufflesuite/ganache-core/pull/101).
2. I can't find a good reason why [using the `blockTime` flag is discouraged](https://github.com/trufflesuite/ganache-cli#using-ganache-cli).
3. With an `undefined` value for `blockTime`, I don't know how our blockchain transaction confirmation UI ever worked with Ganache. Regardless, it currently doesn't in my experience, and this fixes it.
> Ganache Mining Interval

- origin-js/scripts/helpers/start-ganache.js
_This is intentionally pointed at `stable`._
#985 updates the `blockTime` option in the Ganache server to use a four-second mining interval rather than "instant". Here I am cherry-picking that commit and merging it to `stable` so that the blockchain transactions dropdown will work using a local environment for product demos.
> Hotfix: Ganache Mining Interval

- ipfs-proxy/package.json
- origin-notifications/package.json
Fix shell syntax for comparison that is causing notification container to fail to start on staging.
Also fix same syntax for ipfs-proxy.
> Fix start command for ipfs proxy and notification

- origin-dapp/src/components/dapp-info.js
- origin-dapp/src/components/web3-provider.js
- origin-dapp/src/css/app.css
This adds a couple of environment variables to /dapp-info for debugging, but more importantly repairs the "wrong network" modal and consolidates the redundant storage of network id to Redux and not the component state.
> Unsupported Network Repair 📡

- origin-discovery/src/apollo/app.js
GraphQL playground is disabled by default if NODE_ENV is set to production.
Enabling it since it is nice to run graphql queries in prod using the playground to debug things.
> [Disco server] Enable GraphQL playground in prod

- origin-dapp/src/components/purchase-progress.js
This fixes the consistently-reproducible blank white purchase detail page [here](https://dapp.originprotocol.com/#/purchases/1-000-29-0), as reported by @AustinVirts.
😕
> Dispute Repair

- origin-dapp/src/components/listing-detail.js
This prevents the messaging requirement modal from rendering on top of the buyer onboarding modal.
> Modal Cleanup

- Dockerfile
- package.json
- scripts/symlink-packages.js
- These packages don't seem to work well with hoisting so this creates symlinks from `origin-js/node_modules` to `node_modules/` in the root of the repo.
- This was handled for Docker Compose (I thought it was only a problem there) so the fix for that was removed in favour of a separate script.
> Add post install symlinks for difficult packages

- origin-dapp/src/components/conversation.js
- origin-dapp/src/pages/profile/EditProfile.js
[Issue #817](https://github.com/OriginProtocol/origin/issues/817)
- only allow jpeg / png uploads
- Try to upload an image:
- in a conversation
- when creating or editing a listing
- profile photo
> Natasha/only allow jpeg & png uploads

- origin-js/src/resources/attestations.js
It looks like the RLP dependency recently had a new release where they
moved to TypeScript. I'm not clear on why that broke things, but `import
RLP from rlp` was setting `RLP` to `undefined. This fixes things I
believe.
> Fix origin.js test

- origin-notifications/src/app.js
Fix this error that shows up in the server logs when processing a notification:
```
Info: Processing event eventName=OfferCreated blockNumber=3533915 logIndex=15
(node:77) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at ServerResponse.setHeader (_http_outgoing.js:470:11)
at ServerResponse.header (/app/node_modules/express/lib/response.js:767:10)
at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
at app.post (/app/src/app.js:199:7)
```
> Fix notification server errors

- .travis.yml
- Increase clone depth of TravisCI to avoid errors [like this one](https://travis-ci.org/OriginProtocol/origin/jobs/473940821) where another commit happens and the SHA required by Travis is no longer available because the clone depth of the repo was too small.
> Increase TravisCI clone depth

- origin-dapp/src/components/web3-provider.js
- origin-dapp/src/services/origin.js
- origin-js/src/index.js
- origin-js/src/services/contract-service.js
- origin-mobile/ios/OriginCatcher/Info.plist
currently if you want to link a wallet on stage, you need to set the WALLET_LINKER_URL on the dapp, but the problem is that setting the WALLET_LINKER_URL will show the QR code prompt on stage, which we probably don't want to do yet.
> This allow wallet linker to on without showing the QR code on stage.

- deployment/kubernetes/values/origin/values-dev.yaml
- origin-linking/dot.env
- origin-linking/src/utils/message-queue.js
- Add an env var to allow configurable REDIS_URL
> Make redis server used by origin-linking configurable

- origin-dapp/dev.env
- origin-dapp/src/components/web3-provider.js
- origin-js/src/resources/wallet-linker.js
- origin-linking/src/logic/linker.js
- origin-mobile/ios/OriginCatcher/Info.plist
- origin-mobile/src/OriginWallet.js
- origin-mobile/src/components/wallet-modal.js
When linking from the mobile wallet to safari, sometimes the search params will get lost and not link correctly this hopefully corrects that.
> Make safari load the private params when it's on the same page

- origin-linking/src/config/config.js
- Add underscored: true for production to it queries correct column names
- Removed operatorAliases option since I don't think it is needed, this prints on `origin-linking` start:
`(sequelize) Warning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.`
> Add underscored: true to production for sequelize for origin-linking

- origin-dapp/src/components/dapp-info.js
- origin-dapp/webpack.config.js
- Add missing WALLET_LINKER_URL var to webpack config and dapp info screen
> Add WALLET_LINKER_URL to webpack

- origin-dapp/src/components/listing-card-prices.js
- origin-dapp/src/components/listing-create.js
- origin-dapp/src/components/listing-detail.js
- origin-dapp/src/utils/listing.js
Fixes the following bugs for multi unit listings: 
- removes slash `/` before the `each` word in pricing
- hides boost remaining when listing has not been boosted for multi unit listings
- solves a bug where `boost limit` form would report an error when boost slider is reduced to 0
> Sparrow dom/multi unit fixes

- deployment/kubernetes/charts/origin/templates/linking.ingress.yaml
Websocket timeouts needed to be higher for mobile linking server.
> Increase rps and timeouts for websockets

- origin-dapp/src/components/boost-slider.js
- origin-dapp/src/components/purchase-progress.js
- origin-dapp/src/components/tooltip.js
Fixes the tooltip behaviour in the Dapp (excluding the source code found under experimental folder):
- tooltip on boost slider
- tooltips on purchase progress slider
Seems that overlay trigger requires either a link or a button as an immediate child to work. Can't find any documentation on that though.
- ~[ ] Wrap any displayed ETH addresses with [`formattedAddress`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/utils/user.js#L15-L17)~
- ~[ ] Wrap any new text/strings for translation~
- ~[ ] Map any new environment variables with a default value in the Webpack config~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)~
**Solves issue:** https://github.com/OriginProtocol/origin/issues/1188#event-2059225934
> fix tooltips in boost slider and purchase progress

- origin-dapp/src/components/onboarding-modal/index.js
[Issue #1091](https://github.com/OriginProtocol/origin/issues/1091#issuecomment-451296288)
- Stop the getting started modal from blocking the UI
- Change metamask to Mainnet & dismiss Beta Modal. You should be able to scroll etc
> Natasha/Unblock ui when getting-started is triggered.

- experimental/origin-admin/src/pages/listings/Listing.js
- experimental/origin-admin/src/pages/marketplace/_Offers.js
- experimental/origin-admin/src/pages/marketplace/mutations/MakeOffer.js
- experimental/origin-admin/src/queries/Fragments.js
- experimental/origin-admin/src/queries/Mutations.js
- experimental/origin-dapp2/src/mutations.js
- experimental/origin-dapp2/src/mutations/MakeOffer.js
- experimental/origin-dapp2/src/pages/listing/ListingDetail.js
- experimental/origin-dapp2/src/pages/listing/mutations/Buy.js
- experimental/origin-dapp2/src/queries/Fragments.js
- experimental/origin-eventsource/src/index.js
- experimental/origin-graphql/src/mutations/marketplace/makeOffer.js
- experimental/origin-graphql/src/typeDefs/Marketplace.js
* Addition of `unitsAvailable`, `unitsSold`, and `depositAvailable`
* New `quantity` field for `MakeOffer` mutation
* Purchasing multiple units in `origin-admin` and `origin-dapp2`
There are no tests or validation yet. Validation can go in its own PR.
> Multi-unit for GraphQL

- origin-mobile/ios/OriginCatcher/Info.plist
- origin-mobile/src/OriginWallet.js
- origin-mobile/src/components/transaction-item.js
- origin-mobile/src/components/transaction-modal.js
- origin-mobile/src/screens/transaction.js
- origin-mobile/src/screens/wallet-funding.js
…ance object so fromWei crashes have to convert to string.
-  For some reason web3.utils.toBN was not creating a BN object(it was an s object) and so toWei/fromWei would crash. Using string as default parameter for now.
> Fix crash on depolyed wallet when trying to purchase/sell

- origin-dapp/src/actions/Activation.js
- origin-dapp/src/components/onboarding.js
- origin-dapp/webpack.config.js
- origin-messaging/src/index.js
This solves an issue of the "messaging requirement" modal persisting while Orbit is being synced. Now we will start by querying the central server for whether or not the account is in the global registry. We will still listen for it to be enabled later once everything is synced.
> Messaging Account Detection

- deployment/kubernetes/charts/origin/templates/messaging-api.ingress.yaml
- Enable CORS on the messaging api server from anywhere on dev and staging and from the dapp on production in support of #1223 
- [] ~~Wrap any displayed ETH addresses with [`formattedAddress`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/utils/user.js#L15-L17)~~
> Enable cors on messaging API server

- origin-js/src/contractInterface/users/resolver.js
- origin-linking/src/linker-routes.js
- origin-linking/src/logic/linker.js
- origin-mobile/src/OriginWallet.js
With the new Identity system to be rolled out soon, Origin-js needs to be passed a new variable called attestationAccount, otherwise origin.users.get(address) will fail verifying attestations for new identities.
This PR passes that variable to origin-mobile via the server-info route from origin-linking.
> Update mobile to support new Identity

- deployment/dockerfiles/event-listener
- deployment/dockerfiles/origin-dapp
- deployment/dockerfiles/origin-discovery
- deployment/dockerfiles/origin-faucet
- deployment/dockerfiles/origin-linking
- deployment/dockerfiles/origin-token-transfer-server
Since the ABIs were updated in PR #1233 and a new release 0.8.5 was created, the deployments also need to be updated to copy the ABIs from release 0.8.5... my bad, I forgot that !
> Deployments: copy ABIs from release 0.8.5

- experimental/origin-admin/src/pages/listings/Listing.js
- experimental/origin-admin/src/pages/marketplace/_Offers.js
- experimental/origin-admin/src/queries/Fragments.js
- experimental/origin-admin/src/queries/Listing.js
- experimental/origin-eventsource/src/index.js
- experimental/origin-graphql/src/resolvers/Listing.js
- experimental/origin-graphql/src/typeDefs/Marketplace.js
Implements offer validation in the event sourcing layer for GraphQL.
This change introduces a new `Listing` field called `allOffers`, which
contains all offers regardless of validity.
The existing `offers` field now contains just valid offers.
Additionally, each `Offer` now contains the `valid` and
`validationError` fields.
> Offer validation for GraphQL

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
On staging, the Access-Control-Allow-Origin and Access-Control-Allow-Credentials headers were set twice on the response, causing Chrome browser to fail the request.
> Do not set cors response headers twice on staging

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- This hack was intended to allow CORS requests from any origin for the bridge for demo purposes, but it is causing too many problems right now
> Remove workaround for CORS from anywhere on bridge

- experimental/origin-services/index.js
This change makes the ganache instance launched by origin-services use
the same mnemonic that's used by origin-js's ganache instance. This
makes switching between the two code bases much easier.
> Use existing mnemonic for origin-services

- experimental/origin-admin/src/pages/listings/Listing.js
- experimental/origin-dapp2/src/pages/listing/ListingDetail.js
Correct line break handling for listing description for both dapp2 and origin-admin.
> Correctly handle line breaks in descriptions.

- origin-notifications/README.md
> Notifications Instructions

- origin-discovery/src/listener/rules.js
Fractional listings don't have a price field.
> Don't overzealously check for price in indexer

- origin-dapp/src/pages/profile/ConfirmReset.js
- origin-dapp/translations/all-messages.json
- origin-dapp/translations/messages/src/pages/profile/ConfirmReset.json
Adds a "Learn More" link that points to medium blog post about new identity.
> Add blog post link to identity upgrade modal

- origin-dapp-creator-client/src/pages/App.js
- Forgot to store the marketplacePublisher ethereum address in the config 😞
> Store marketplacePublisher correctly

- experimental/origin-graphql/src/mutations/marketplace/makeOffer.js
- experimental/origin-graphql/src/mutations/marketplace/updateListing.js
- experimental/origin-graphql/test/_helpers.js
- experimental/origin-graphql/test/_mutations.js
- experimental/origin-graphql/test/index.js
- More tests, especially for invalid offers
- Prevent UpdateListing mutation from changing unitsTotal so that it's below unitsSold.
- Fixed a bug in checking offer quantity (caught by a new test!).
Our marketplace tests should be sufficient for now.
> GraphQL: more tests and validation

- experimental/origin-dapp2/src/queries/Config.js
- experimental/origin-graphql/src/contracts.js
- experimental/origin-graphql/src/typeDefs/Web3.js
This fixes the "affiliate" field in dapp2's dapp-info page, where it's
currently blank.
Also removed an unused parameter to the OriginEventSource constructor.
> Fix spelling of 'affiliate' in Config query

- experimental/origin-admin/src/pages/accounts/_populate.js
- experimental/origin-admin/src/pages/listings/Listing.js
- experimental/origin-admin/src/pages/marketplace/_Offers.js
- experimental/origin-admin/src/pages/marketplace/mutations/CreateListing.js
- experimental/origin-admin/src/pages/marketplace/mutations/MakeOffer.js
* Show validation error when hovering over offer status "Invalid"
* Populate commissions for demo listings
* Handle commissions in origin-admin  …
- Show commissions info on each listing page
- Specify commission & per-unit commission for create & edit commissions
- Handle commissions when creating new listing based on example listings
> origin-admin commission handling

- origin-js/src/ipfsInterface/adapters/listing/v1-listing-adapter.js
Fix a problem where fractional listings were missing `commission` property when decoded from IPFS.
> fix a problem with fractional listings not showing in elasticsearch

- origin-discovery/src/lib/search.js
The new listing.availability and offer.timeSlots fields use a complex jCal type.
This is causing issues with ElasticSearch dynamic mappings functionality.
Here is the scenario:
- First doc of the corpus with an availability field gets indexed, Elastic decides on a mapping.
- 2nd doc comes, it has an availability field but the structure is different -> Elastic fails indexing that document since the mapping has changed.
Since for now we do not need to support searching by availability we can simply disable indexing of those fields.
In terms of longer term solution, dynamic mapping is pretty dangerous and we should probably turn it off in favor of defining explicit mappings ourselves.
> [Search] Disable indexing of jCal fields

- development/envfiles/origin-dapp.env
- I find myself always enabling performance mode in origin-box so we should make it enabled by default
> Enable performance mode by default for origin-box

- origin-dapp-creator-server/src/middleware.js
- Web3 beta 38 got released and it requires you to pass a provider
> Pass provider URL to web3

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- deployment/kubernetes/helmfile/origin.yaml
- deployment/kubernetes/values/origin/redis/values-dev.yaml
- deployment/kubernetes/values/origin/redis/values-prod.yaml
- deployment/kubernetes/values/origin/redis/values-staging.yaml
- Bug in newer version of redis chart (>5.3.0) with metrics container https://github.com/helm/charts/issues/10733
- Disable password generation for redis
> Pin redis chart to a specific version

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- origin-dapp/src/services/origin.js
- The js-ipfs team added this functionality where whenever you load something from IPFS it sends an additional request to a preload node to prompt those nodes to try and retrieve those hashes. The IPFS server in the browser for messaging triggers thousands of these requests and we see a lot of failed requests so I think we should disable this preloading for now.
> Disable IPFS preloading for messaging IPFS

- origin-messaging/src/config.js
- origin-messaging/src/index.js
…ectly after read
- Load the logs from the snap shot in batches and sleep in between to allow ipfs a chance to breath
- Do not write to snapshot directly after read.
> Hope this actually fixes messaging

- origin-dapp/src/components/web3-provider.js
- origin-dapp/translations/all-messages.json
- origin-dapp/translations/messages/src/components/web3-provider.json
It seems that there is no merit in checking for a web3 "connection".
- [Trust Wallet provider](https://github.com/TrustWallet/trust-web3-provider/blob/f5bc6f0b19818accbc93eeed61e2931ab4d4db95/src/index.js#L21-L23)
- [MetaMask provider](https://github.com/MetaMask/metamask-inpage-provider/blob/dcfd9245ee4fd687e1e91fa4a9ba23b8a72dd3db/index.js#L111-L113)
- [Web3.js Deprecation](https://github.com/ethereum/web3.js/issues/440#issuecomment-321517072)
- [Web3.js 1.0 docs](https://web3js.readthedocs.io/en/1.0/search.html?q=isconnected&check_keywords=yes&area=default)
It also suffers from [some underlying problem in the Cyton Android wallet](https://github.com/cryptape/cyton-android/issues/294). We've had problems with it in the past when dealing with IMToken's wallet, which did not support …
> Pointless Web3 Connection Check

- origin-dapp-creator-client/package.json
- origin-dapp/package.json
- origin-js/package.json
- Webpack now uses Terser for minification, Terser released a broken package which causes these errors for builds:
`TypeError: Cannot read property 'minify' of undefined`
- Pinned terser to the version prior to the broken one
- Ref https://github.com/terser-js/terser/issues/251
> Pin terser to 3.14.1

- origin-js/scripts/helpers/contract-addresses.js
- origin-js/scripts/helpers/debug-output.js
- origin-js/scripts/serve.js
This PR adds some helpful debug output when running `origin-js` with `npm start` as requested in #1379.
> Useful debug output for origin-js 

- origin-discovery/README.md
- origin-discovery/package.json
- origin-discovery/test/apollo-resolvers.test.js
- package-lock.json
This PR is fairly trivial but could use a second set of eyes. 
- README fix
- Test fix
- Upgraded GraphQL
It would be good if someone could review and confirm the test change.  It's unrelated to the GraphQL upgrade since it was throwing before that change, but `expect().to.be.an()` apparently doesn't see class instances as Javascript objects, even though `typeof GraphQLJSON` would still return `object`.  This change seems more accurate to me, but GraphQL is new to me, so I'd like to be sure.
Also, the GraphQL upgrade required no changes to `origin-discovery` to pass tests, even with the breaking changes listed for their releases. The scalar value changes could impact users, but it looks like it would require bad behavior in the queries to begin with.
> Graphql upgrade and some other stuff

- origin-dapp-creator-client/package.json
- origin-dapp-creator-server/package.json
- The `^` modifier is dangerous with web3 😞
- Web3 published beta 42 which is broken
> Pin web3 in creator to beta 34

- origin-ipfs-proxy/load.js
- origin-ipfs-proxy/package.json
- origin-ipfs-proxy/src/app.js
- origin-ipfs-proxy/src/config.js
- origin-ipfs-proxy/test.js
> Implement prettier and run for origin-ipfs-proxy

- package.json
origin-growth was made a dependency of origin-discovery, which is needed
for install:mobile. origin-growth depends on origin-graphql, which has a
lot of transitive dependencies, so it's easier to just install all
packages when running `install:mobile`.
cc @micahalcorn @crazybuster
> Fix `npm run install:mobile`

- deployment/dockerfiles/event-listener
- deployment/dockerfiles/origin-discovery
- origin-dapp-creator-client/package.json
- origin-dapp-creator-server/package.json
- `origin-discovery` now depends on `origin-growth` so a bunch of new packages need to be added to the discovery based deployment containers
- Added a path fix to `origin-dapp-creator-server` eslint rule so it doesn't pick up the `dist` directory
> Container updates for origin-growth dependency in origin-discovery

- Dockerfile-experimental
- docker-compose.experimental.yml
This solves 2 problems: 
- added `origin-token` folder in image creation step, otherwise a clean install produced this errors:  `Can not find origin-token@0.1.0`
- corrected `node_modules` folder omissions. In my case the host machine `node_modules` have been mapped to the docker containers producing unexpected results.
> Fix problems with dapp2 running in docker

- origin-js/src/services/contract-service.js
- origin-linking/src/logic/hot.js
- Infura doesn't support signing or sending transactions for accounts that it doesn't have private keys for, this sends a raw transaction instead.
> Allow signing and sending transaction for off browser processes

- origin-contracts/sig_schema/Listing.json
- origin-dapp/src/components/listing-create.js
- Made an assumption that unitsTotal can be uint, apparently not the case.
> New type for unitsTotal since it can go negative

- origin-contracts/migrations/17_transfer_vA_ownership_for_mainnet.js
- migration to set the multisig owner.
> set VA marketplace to the multisig account

- origin-discovery/src/apollo/injector.js
- origin-discovery/src/apollo/logger.js
This PR adds some instrumentation in the discovery server to troubleshoot why creation of no-gas listings in the services category fails.
> Add instrumentation to injectListing

- docker-compose.experimental.yml
Ports that DApp2 and IPFS run on were changed in #1461.
> Update DApp2 and IPFS ports in Docker

- docker-compose.experimental.yml
- New env vars required for origin-discovery due to the no gas changes
> Add missing env vars for origin-discovery in docker

- experimental/origin-graphql/src/mutations/_gasCost.js
- experimental/origin-graphql/src/mutations/marketplace/executeRuling.js
- experimental/origin-graphql/src/typeDefs/Marketplace.js
- experimental/origin-graphql/test/_mutations.js
- experimental/origin-graphql/test/index.js
- Add test of disputeOffer mutation
- Add several tests of executeRuling mutation
- Add explicit checking to executeRuling `commission` and `ruling` parameters
- Document allowed value strings in GraphQL types file
> GraphQL tests of dispute and executeRuling mutations.

- experimental/origin-graphql/src/mutations/_txHelper.js
- experimental/origin-graphql/test/_gasTable.js
- experimental/origin-graphql/test/index.js
Shows a table of min and max gas usage per Origin GraphQL mutation.
No dependencies.
> Show table of gas usage in Origin GraphQL tests.

- deployment/kubernetes/charts/origin/templates/_helpers.tpl
- deployment/kubernetes/charts/origin/templates/faucet.deployment.yaml
- deployment/kubernetes/charts/origin/templates/faucet.ingress.yaml
- deployment/kubernetes/charts/origin/templates/faucet.secret.yaml
- deployment/kubernetes/charts/origin/templates/faucet.service.yaml
- Reduced faucet replicas to 1 so nonce manager works
- Prod uses /eth
- Staging and dev use /
Will need to update some DNS entries for this to work.
> Enable faucet in production

- origin-dapp-creator-client/src/pages/App.js
- origin-dapp-creator-server/src/middleware.js
- Fix for broken signing on creator and replaced signing of config with a better message
> Replace config signing with nicer message

- deployment/kubernetes/charts/origin/templates/faucet.ingress.yaml
> Simplify ingress and just use /eth for faucet.originprotocol.com

- origin-faucet/src/eth.js
Waiting for a txn receipt on mainnet can take several minutes (it took over 2 min when I tested today)... This is not a great user experience since upon form submission, the use has to wait with no feedback as to what's happening.
Changes logic to return the txn hash right away, with a link to the pending transaction on etherscan so that the user can check there on the status.
In order to do this, I refactored the code to introduce a TxnManager which wraps calls to web3 for sending transaction, getting hash and receipt.
> [ETH Faucet] Return txn hash right away rather than waiting for receipt

- origin-dapp/src/actions/Activation.js
- origin-dapp/src/components/onboarding.js
- origin-dapp/src/components/web3-provider.js
Please see [this comment](https://github.com/OriginProtocol/origin/issues/1437#issuecomment-466588391) @crazybuster in case we should also make a change to the messaging resource.
In https://github.com/OriginProtocol/origin/pull/1358, we added a client-side check so that a user who had previously enabled messaging but since deleted cookies or moved to a different device would be prompted to enable messaging. The problem with this in the real world is that [it depends on `this.account`](https://github.com/OriginProtocol/origin/blob/bd562ea4533f2c1588ead919155eb16fb676e9ba/origin-js/src/resources/messaging.js#L890), which in turn [depends on `initKeys`](https://github.com/OriginProtocol/origin/blob/bd562ea4533f2c1588ead919155eb16fb676e9ba/origin-js/src/resources/messaging.js#L240), which …
> Repair Delayed Messaging Requirement

- origin-mobile/android/app/build.gradle
- origin-mobile/android/app/src/main/java/com/origincatcher/MainApplication.java
- origin-mobile/android/sentry.properties
- origin-mobile/android/settings.gradle
- origin-mobile/ios/OriginCatcher.xcodeproj/project.pbxproj
- origin-mobile/ios/OriginCatcher/AppDelegate.m
- origin-mobile/ios/sentry.properties
- origin-mobile/package.json
Integrate Sentry with react-native. This is basically the output of the automated sentry integration script. I haven't attempted to test this at all, maybe you can try and spin it up @micahalcorn? There is an auth token you might need which goes in sentry.properties. You can ping me for it if you need it.
- [] Test your work and double-check to confirm that you didn't break anything
> Add sentry to origin-mobile

- origin-contracts/README.md
We are no longer creating ERC725 contracts for identity, so I updated the info in the identity section of origin-contracts readme.
> Update old info in the identity section of origin-contracts readme.

- deployment/cloudbuild-deploy.yaml
- deployment/dockerfiles/origin-dapp2
- deployment/kubernetes/charts/origin/templates/dapp2.deployment.yaml
- deployment/kubernetes/charts/origin/templates/dapp2.ingress.yaml
- deployment/kubernetes/charts/origin/templates/dapp2.service.yaml
- experimental/origin-dapp2/webpack.config.js
Adds dapp2.staging.originprotocol.com configured for Rinkeby.
> Dapp2 staging deploy

- origin-growth/src/apollo/adapter.js
- origin-growth/src/apollo/resolvers.js
- origin-growth/src/rules/rules.js
Separating Apollo formatting functionality out of rules class
> separate apollo adapter logic to a separate file

- deployment/cloudbuild-deploy.yaml
- deployment/dockerfiles/origin-dapp2
Make some env vars available to dapp2 inside Docker container
> Make GIT_COMMIT_HASH and GIT_BRANCH available to dapp2 build

- origin-dapp/src/components/onboarding.js
- origin-dapp/src/reducers/App.js
This removes the requirement to enable messaging before buying or selling as discussed below. 🔥
> No Messaging Prerequisite

- experimental/origin-dapp2/src/pages/about/DappInfo.js
Add env vars to dapp-info for ease of debugging
> Add env vars to dapp2's dapp-info page

- experimental/origin-dapp2/src/components/PageTitle.js
> Add titles from marketplace creator to PageTitle component in DApp2

- experimental/origin-dapp2/src/components/MobileLinkerCode.js
Wasn't passing in linkCode to openLinkerApp()
> Fix "open in wallet" button

- origin-linking/src/logic/linker.js
The mobile wallet gets its URLs from the linking server. Right now,
we're returning bad URLs because staging's EnvKey has DAPP_URL set to
something that ends in `/#/`, which the linking server appends another
`/#/` to for the profile URL and other URLs.
This change uses Node's builtin `url` package to remove extra `/#/`s and
prevent double slashes. This should make the generated URLs a little
cleaner.
> Fix wallet dapp URLs

- experimental/origin-graphql/src/resolvers/marketplace/listings.js
Currently a single invalid listing will break the entire listing results page. This is because `Promise.all` will immediately reject if any sub-promise rejects. 
While there might be better ways to handle this long term (will make separate issue for discussion), the simplest approach is to just exclude from the results any listings that fail to load, are invalid, or throw errors.
This does have the downside of possibly returning fewer listings than were asked for, but it's certainly better than breaking the whole front page, and making people unable to browse listings.
> Exclude an invalid listing from listings search, rather than return no results at all

- experimental/origin-eventsource/src/index.js
A listing json containing `{...media:"string"...}` would crash the dapp.
There was an existing check making sure media had a "length", but this also succeeded for a string.
> Don't crash with a string as a listing media

- origin-mobile/src/screens/scan.js
Fixes #1536 by re-rendering `QRCodeScanner` on nav change. 
This fix adds a small delay to rendering.  Probably ~500ms.  If #1536 can not be reproduced on iOS, then this fix could be adjusted to be Android-only.
> fixes #1536 by forcing re-render of QRCodeScanner on nav switch

- origin-bridge/src/app.js
Remove the secure cookie setting from `origin-bridge`. This stops cookies working because the nginx -> origin-bridge communication is not via https, the https connection terminates at nginx. It isn't necessary either since nginx enforces https.
> Remove secure cookie requirement from bridge

- experimental/origin-dapp2/src/pages/listing/_ListingEditOnly.js
- experimental/origin-dapp2/src/queries/Fragments.js
NOTE: This expects there to be a `listing.unitsPending` field *which does not yet exist*. Best to hold off on merging this PR until that change gets made. @nick is on it. 
Resolves P0 blocker number 6  "[No way to see number of remaining units on a created unit listing](https://docs.google.com/spreadsheets/d/1IPsBe-08Bnq5WEtg4KMdZKgEWLF2AbLqo0LLhLriW5Q/edit#gid=794850718&range=6:6) " from spreadsheet:
Styling not yet blessed by Aure, but a request has been made.
> Add Sold/Pending/Available data to buy box for seller.

- origin-faucet/src/eth.js
- Allow passing of PROVIDER_URL to faucet rather than using INFURA_ACCESS_TOKEN.
@franckc I was looking for a way to leverage your work on the eth faucet for distributing eth on our testnet. I think this is the only change I need to make (and add a row to the campaign table with a large limit and invite code). What do you think? I think we should change this anyway because it gives us the option of using other web3 providers.
> Use PROVIDER_URL in faucet

- origin-mobile/README.md
This was added as part of Android wallet support. The wallet app doesn't start without this environment variable.
> Add GCM_SENDER_ID to origin-mobile's README.md

- experimental/origin-dapp2/src/pages/listing/ListingDetail.js
- experimental/origin-dapp2/src/pages/listing/_ListingEditOnly.js
We were showing a "Price " and "Units Sold" etc.. for fractional listings, which makes no sense.
I'm loathe to add more if/then display logic, but for now we're already on that path, so here's to more!
> Fix display of "Edit Only" box on listing detail

- experimental/origin-dapp2/src/pages/create-listing/Boost.js
Wrong URL for token info page when going through create listing flow.
> Fix dead link to token info page

- experimental/origin-dapp2/src/components/Calendar.js
- experimental/origin-dapp2/src/pages/create-listing/Availability.js
- experimental/origin-graphql/src/utils/AvailabilityCalculator.js
- experimental/origin-graphql/test/availability-calculator.js
Fractional was using a nonstandard way of respresenting dates and ranges. This switches us to use our standard ISO 8601 format.
Ranges (which are called "Intervals" in the ISO standard) are represented as 2 dates joined by a `/`, e.g. `2007-03-01/2008-05-11`
https://en.wikipedia.org/wiki/ISO_8601#Time_intervals
NOTES: 
- Should we write a little converter that recognizes dates/ranges in the old format and converts them on the fly? Would only be useful for pre-launch testing. 
- I think we should consider using a delimter other than `:` for adding a price to a range, as the colon is used in ISO time formats e.g. `2008-09-15T15:53:00`. We could not expand this format to include hourly fractional usage.
> Use IOS dates and ranges in fractional

- .travis.yml
- docker-compose.yml
- origin-services/index.js
In this pr: 
- docker images build a lot faster since they are built only once. Seems that `build` config triggers rebuilding of image and Lerna hoisting for each of the containers
- fix contracts path preventing `origin-dapp` container to start
- (slightly unrelated) enable `origin-growth` by default since this won't effect staging/production deployment
> New dapp and docker fix

- origin-dapp/src/pages/listing/Edit.js
- Per title. `marketplacePublisher` wasn't getting saved on edit listings.
> Pick up marketplacePublisher on edit listing

- origin-bridge/src/models/attestation.js
I noticed this was not working while working on a different table...
I don't think it is exercises in the bridge so nothing is currently broken
> Fix default value for attestation createdAt

- origin-discovery/src/listener/handler_identity.js
- origin-discovery/src/listener/handler_marketplace.js
- origin-growth/src/models/growth_event.js
- origin-growth/src/resources/event.js
Use date from blockchain rather than current date so that if the listener is down for a period of time or if we do some re-indexing, the createdAt field won't vary.
> [Growth] Set event createdAt to blockchain event date.

- origin-discovery/package.json
- origin-discovery/test/listener-handler.test.js
The change I made recently to not populate automatically growth_event.created_at broke a discovery unit test....
> Fix discovery test

- deployment/dockerfiles/origin-messaging
- deployment/kubernetes/charts/origin/templates/messaging.ingress.yaml
- deployment/kubernetes/charts/origin/templates/messaging.service.yaml
- deployment/kubernetes/charts/origin/templates/messaging.statefulset.yaml
- Exposes https rather than orbit
- Add SQL migrations and access to SQL via cloudsql proxy
- Configured REDIS_URL and DATABASE_URL in EnvKey
I think all that is left is `npm run orbit-to-db` when the new centralized messaging starts. Anything else @crazybuster?
We should merge this before #1691
> Centralized messaging Kubernetes configuration

- deployment/cloudbuild-deploy.yaml
- Add some step ids to make build logs prettier
- Also removed the machine definition for the builds to see if it makes things faster. It takes Google longer to spin up N1_HIGHCPU_8, but builds faster when it has started so want to check it is actually helping.
> Add step ids to cloudbuild deployment

- origin-dapp/src/pages/growth/Welcome.js
- origin-dapp/src/pages/growth/WithEnrolmentModal.js
On mobile prevent users from joining the growth campaign
**!Important** change base branch to master once `sparrowDom/growthOnboarding ` gets merged
> Disable growth enrolment on mobile

- origin-dapp/src/components/GrowthCampaignBox.js
- origin-dapp/src/pages/growth/Welcome.js
- origin-dapp/src/pages/growth/WithEnrolmentModal.js
- origin-dapp/src/pages/onboard/Finished.js
- origin-dapp/src/pages/onboard/Messaging.js
- origin-dapp/src/pages/onboard/MetaMask.js
- origin-dapp/src/pages/onboard/Notifications.js
- origin-dapp/src/pages/onboard/Onboard.js
- origin-dapp/src/pages/onboard/Profile.js
- origin-dapp/src/pages/onboard/Wallet.js
- origin-dapp/src/pages/user/Profile.js
- creates a growth campaign box placeholder in profile view
- goes to on-boarding if user doesn't have a wallet installed
- removes the ability to register mobile wallet as part of growth on-boarding
- redirects back to profile or welcome pages after on-boarding and opens the growth enrolment modal to not break flow
> Integrate on-boarding with growth enrolment flow

- origin-dapp/src/pages/messaging/Message.js
Quick one-liner to make messages look like this:
Instead of splitti
ng mid-word.
> Fix word-break in messaging

- origin-graphql/src/contracts.js
- origin-graphql/src/utils/eventCache.js
The event cache finds all events in a given range and stores them in local storage. Previously this was all done in a single call which could take a long time to respond. This new code takes a range of blocks and splits it up into requests of 20,000 each. It then sends those requests in batches of 7.
For example, a range of blocks of 6,000,000 to 7,000,000 would result in 100 requests.These requests are then sent in batches of 7, so that the node is not hit with 100 requests at once.
I reached the 20,000 blocks in batches of 7 after a bit of experimentation... seems to be a sweet spot.
> Past event batching

- devops/dockerfiles/origin-cron
- I noticed the cron jobs where failing due to trying to connect to redis on localhost because REDIS_URL wasn't set. I think it's because we were not sourcing envkey.
- I did check the proper envkey value is set for origin-cron in the secrets.
> Fix cron container to source envkey

- packages/contracts/truffle.js
- packages/token/src/config.js
Replace with PROVIDER_URL which will be pointing to infura or alchemy.
> Cleanup: get rid of INFURA_ACCESS_TOKEN

- DEVELOPMENT.md
A minor text fix in the Developer Quickstart. The admin tool is located inside `dapps/admin` directory not just `admin`.
> Fix admin tool directory in Developer Quickstart

- devops/kubernetes/charts/origin/templates/growth.ingress.yaml
- infra/growth/src/apollo/app.js
After we launch, it will be handy for us to be able to query the reward data via the prod growth graphql server for a given user to be able to troubleshoot potential issues.
> [Growth] Add admin access

- dapps/marketplace/src/pages/growth/Action.js
Hide reward earned when that value is 0
> Reward engine hide reward earned

- crowdin.yml
- dapps/marketplace/scripts/fbToSimpleJsonFormat.js
Dapp2 seems to not have Crowdin integration. What this PR attempts to do is: 
- convert the new fbt output translation files into the simple JSON format
- prepare a crowdin.yml configuration file that should configure Crowdin where to look for source files and where to put the translated files.
**Remark:**
- the new dapp2 `all-messages.json` was manually uploaded to Crowdin so Anna could start with the Chinese translations. 
**TODO:**
- read what Crowdin produces and integrate those translations back to Dapp2
> attempt to configure crowdin translations for the new facebook plugin

- packages/graphql/src/mutations/marketplace/makeOffer.js
As requested by @joshfraser and @matthewliu, this intends to shorten the finalization window from one year to two weeks. I recommend that we eventually prescribe different timeframes depending on the listing types or consider a different approach altogether.
> Two-Week Finalization Window

- packages/graphql/src/utils/currencies.js
Set default exchange rates for currencies to deal with the case where the centralized server we query to dynamically fetch the rates is down.
Also fixed a bug in the rate ! It was storing the reverse of what we want... :)
> [GraphQL] Set default currency conversion rates

- dapps/marketplace/src/pages/growth/Invite.js
This fixes a bug where `origin-invite-code` field does not get populated on the second open of invite page. The problem was that Query was hitting cache and not triggering `onComplete` function that populated the invite code state.
> Fixes a bug where invite code didn't show up on second open of invite screen

- dapps/marketplace/src/pages/growth/Invite.js
- dapps/marketplace/src/queries/Fragments.js
- infra/growth/src/resources/invite.js
- packages/graphql/src/typeDefs/Growth.js
Id seems to be a field in Apollo with special properties since Cache seems to use it. Changed `id` to `pendingId` to circumvent weird cache behaviour
> Sparrow dom/rewards fix

- infra/discovery/src/listener/handler_marketplace.js
- infra/discovery/src/listener/queries/Fragments.js
- infra/discovery/src/listener/webhooks.js
- infra/discovery/test/listener-handler.test.js
Fixes offer status indexing which is `offerStr` not `offer` in graphql. The `offer` attribute is an integer representing the status.
> Fix indexing of offer status

- packages/graphql/package.json
- packages/graphql/src/contracts.js
- packages/graphql/src/utils/eventCache.js
the event cache is currently stored in localStorage but has recently gone over the limit, causing errors in the dapp.
This PR is a short term fix to compress the events before storing in localStorage.
> Compress event cache to prevent localStorage overflow

- infra/discovery/src/listener/listener.js
We don't really need concurrency when its running normally, but it is handy for backfilling. Make it configurable with default to 1.
> Add concurrency setting to listener

- dapps/marketplace/package.json
- dapps/marketplace/src/mutations/GrowthEnroll.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/growth/mutations/Enroll.js
- infra/growth/src/apollo/resolvers.js
- infra/growth/src/resources/authentication.js
- infra/growth/src/util/locationInfo.js
- packages/graphql/src/typeDefs/Growth.js
Compute a fingerprint on the enroll page and pass it to the back-end to store it in growth_participant.data
> [Growth] Store browser fingerprint during campaign enrollment

- packages/graphql/src/typeDefs/Common.js
It would be better to use CurrencyResult but it involves changing the rules in the DB.
For the sake of not blocking the stable coins launch, let's use String which is waht is currently being used in prod.
> [Growth] change Price.currency to String in short-term

- dapps/marketplace/src/pages/identity/EmailAttestation.js
- dapps/marketplace/src/pages/identity/PhoneAttestation.js
Fixes #1709 
When `type` attribute is not set, it defaults to `submit`. That caused both submit and cancel buttons to act as submit.
> Add `type` attributes to button

- infra/discovery/src/listener/listener.js
I noticed the listener gets stuck if it hits either rate limiting error or network errors when calling Infura/Alchemy.
This change wraps those calls with exponential backoff retries.
> [Listener] Add retries to blockchain calls in main loop

- packages/services/index.js
Change to @origin/services to allow someone to provide an option for ganache to generate more accounts for testing.
> Adds an option to allow for more accounts to be used with ganache

- infra/bridge/migrations/20190408083420-add-google-attestion-type.js
This is correct for the deployments but it is then out of sync with the tests (this is due to legacy enum name from the old Python bridge server). I'll revert this and rename the enum on the deployment SQL databases.
> Revert "Fix bridge attestation enum"

- dapps/marketplace/src/components/ImagePicker.js
- dapps/marketplace/src/pages/user/Profile.js
- dapps/marketplace/src/pages/user/_EditModal.js
- dapps/marketplace/src/utils/uploadImages.js
- packages/graphql/src/typeDefs/Identity.js
We are wanting to transition the identity avatar image out being embedded as a base64 string in the profile, and change to posting the image to IPFS and linking to it as we do with listing images. See issue #1795.
The first step of this transition is to save newly uploaded avatars in IPFS, while keeping the old data url method as the one actively used. This way we don't have to carefully time our avatar IPFS image backfill, and the transition should be seamless.
- Refactors out our image uploading and resizing code to a util file, which is then used by both listing and avatar photos.
- Stores avatar photos in IPFS, and adds a new profile field  `avatarUrl` with an 'ipfs://HASHHERE' style url.
- Nothing about reading or using profile avatars is changed.
> Store avatar profile

- infra/notifications/src/app.js
Fix missing logger module error. @wanderingstan this probably worked locally because you had an ENVKEY variable set so it never hit the logger call.
> Fix logger import

- mobile/ios/OriginCatcher/Info.plist
- mobile/src/OriginWallet.js
- mobile/src/components/onboarding.js
- mobile/src/screens/marketplace.js
This was a hard one to track down, but it looks like the `SafeAreaView` component from react-native [is broken](https://github.com/callstack/react-native-paper/issues/800). The one from `react-navigation` seems to work fine.
Also fixed a little issue with network detection.
> Fix shaking/lockup due to react-native SafeAreaView

- infra/discovery/src/lib/search.js
- infra/discovery/test/apollo-search.test.js
Currently our search results contain a lot of irrelevant listings, often ahead of the obvious choice. (see #2042)
Primarily this is because we were selecting any listing that contained *any* word from the search query. This placed many irrelevant featured listings ahead of real results, and adds in many listings with no relationship to the search phrase.
This PR makes two changes.  
1) When using multi-word searches, listings must contain almost of the query words in order to match. Searching for "origin event tshirt" will now require that a listing contains all three of those words, instead of matching both all listings with "tshirt" and all listings with "origin". I've set it to require all words, up to four words, then after allow 20% of the words not to match. Hopefully this number is …
> Reduce irrelevant search results

- infra/faucet/src/eth.js
Per request from @micahalcorn, in anticipation of the Korean meetups next week, we want to:
1. make campaign code case insensitive to make it more mobile friendly
2. turn off the phone attestation speed bump since Korean users seems to be having problems verifying their phone
Note: this will require a deploy to prod. @micahalcorn let me know if you need me to do the deploy or if the team is already planning on doing a deploy this week...
> [Faucet] Make campaign code case insensitive and check on phone attestation conditional

- dapps/marketplace/src/pages/App.js
- Hides growth banner in webview while it doesn't work on mobile.
> Disable growth banner in webview

- packages/eventsource/src/index.js
Fixes #2088 
The [AvailabilityCalculator](https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/utils/AvailabilityCalculator.js#L138) expects the range separator to be '/' but was getting '-'. That caused this bug.
> Fix fractional listing calendar to show booked dates

- mobile/README.md
- Docs no longer need the `.env` stuff as the config is mostly handled by graphql and the network switcher.
> Update mobile documentation

- infra/discovery/src/listener/handler.js
Log the errors that cause webhook calls to fail.
> Log webhook error details in listener

- packages/graphql/src/utils/eventCache.js
- packages/graphql/src/utils/genericEventCache.js
Quick fix for eventCache to only poll 3,000 blocks at a time
> Event cache hotfix

- packages/event-cache/src/EventCache.js
Fix an issue where the listener, which is currently using in-memory storage, was not loading the IPFS cache at startup.
> [Event-cache] Fix IPFS cache loading condition

- packages/graphql/src/resolvers/Offer.js
This was missed in my original PR #1975  Event args given to `EventCache.getEvents` should be strings since that's what's originally returned by web3.js.
> Fixes an event arg for getEvents

- dapps/marketplace/src/hoc/withFingerprint.js
One of the weirdest bugs to hunt down... the problem was that `cancelIdleCallback` is not defined in IOS's browser component in CoinBase and instead of throwing an error saying `cancelIdleCallback  is not defined` a `React cross-origin-error` was thrown.
> fix cross-origin-error on Coinbase IOS wallet

- docker-compose.yml
I needed to add `origin-js` folder mapping in order for services to run. I couldn't find it as a dependancy in `services/package.json` though
> Add services container dependacy

- dapps/marketplace/src/hoc/withFingerprint.js
Create an UUID and populate it with first `walletId` that tries to Enrol into growth (or use `withFingerprint` hoc). Store that UUID in `localStorage` and a `cookie`
In future it would be even more resilient storing this into IndexedDB, but that is not a part of this PR.
> add uuid as fingerprint data

- infra/discovery/src/listener/listener.js
Make sure the event-listener uses the latest processed block for `processedToBlock` instead of assuming the latest block number it requested is the same that event-cache gets.
> Lowering event listener's assumptions

- packages/graphql/src/utils/AvailabilityCalculator.js
- packages/graphql/test/availability-calculator.js
Fixes #1735.
For some reasons, the existing code was allowing only one price to be set for all custom ranges. That caused the issue.
> Add support for multiple custom price ranges

- packages/event-cache/src/EventCache.js
`lastIndexedBlock` was trailing with the block from the last getPastEvents request instead of being set after.  Since listener used this, it was reprocessing past events back to the previous request block number.
> fixes problem where lastIndexedBlock was trailing

- packages/event-cache/src/EventCache.js
- packages/event-cache/src/backends/AbstractBackend.js
- packages/eventsource/src/index.js
- packages/graphql/test/index.js
`getLatestBlock` was changed to async for IndexedDBBackend but was not updated in AbstractBackend, which is used for the other backends(including memory, which was used for listener).  Not sure of JS's behavior in this case for certain, but I'm thinking `await`ing on a synchronous function is probably a bad idea.
> async and non-async function mix issue

- dapps/marketplace/src/components/Balances.js
- dapps/marketplace/src/pages/nav/Profile.js
This attempts to solve two confusing states that were reported by @jonhearty. First is when a user clicks the ➕ to sign up for Origin Rewards and is presented with a full-screen modal. Once the process is completed and the modal closes, the dropdown remains. This causes the user to be unaware of the component state change behind the dropdown. The second occurs if the user clicks the ➕ again after having already navigated to the campaign dashboard. Since the ➕ effectively links to that route, there is no feedback provided by the interface.
> Close dropdown when rewards icon is clicked

- dapps/marketplace/src/pages/growth/Action.js
- dapps/marketplace/src/utils/numberFormat.js
- Style origin rewards on mobile (see screenshots below). 
- Number format function now has a shortening ability. 
- Number format function does not show decimals anymore if those are 0
> fix origin mobile rewards styling

- infra/discovery/src/listener/handler_identity.js
This is purely a debugging PR.  No functional changes are being done here.  This adds some debug logging for a suspected sync issue between the listener handler and graphql.  I just want to see if this actually occurs on staging and prod before I really dig in to the *why* of this issue.
Ref: #2163
> Listener debugging

- infra/discovery/src/listener/handler.js
- infra/discovery/src/listener/handler_identity.js
- infra/discovery/src/listener/queries/Identity.js
- packages/graphql/src/index.js
- fixes an issue with the debug statment in PR #2225, due to missing data in the GraphQL query
- Disables the GraphQL cache for the discovery listener handler because it's not strictly necessary here
This *might* resolve ||don't auto close GitHub|| #2163
> Fix to debug and disables graphql cache for the listener

- infra/discovery/src/lib/search.js
Before boosting in search results, check that OGN has actually been deposited in the marketplace contract.
> Before boosting, check that OGN is in the contract

- packages/graphql/src/resolvers/IdentityEvents.js
The avatarUrl column was not populated by the listener because the graphql code handling avatar binary was calling atob which is not supported by node. Replaced with calls to Buffer which is supported in node and is magically converted to something that works in the browser by babel/polyfill.
> [Listener] Fix avatarUrl persistence in DB

- packages/event-cache/src/EventCache.js
When IndexedDB is cleared out and you refresh a local instance of the dapp, events are not guaranteed to be loaded before they are returned from event-cache. This change attempts to fix it... really hope it doesn't have any unintended side effects!
> Fix to ensure latest events available on initial load

- infra/bridge/src/utils/index.js
Do not append state to redirect URL unless available
> Do not append state to redirect URL unless available

- scripts/clean-package-locks.sh
I assume this changed with the package restructuring.  Tested and works as expected.
> fixes clean-package-locks.sh for new package structure

- mobile/ios/OriginCatcher/Info.plist
This intends to change the display name under the app icon from "Origin Wallet" to "Origin Marketplace". I made the change using Xcode, which seems to have produced some other side effects in the `.plist`. I also wasn't able to test because of local build problems.
> App Display Name

- dapps/marketplace/src/components/Avatar.js
- dapps/marketplace/src/utils/makeGatewayUrl.js
If a profile was passed in, and did non contain an avatarUrlExpanded, then it would not show the avatar. It should have fallen back to using the profile’s avatarUrl.
I’ve cleaned up the code so that this condition no longer exists.
> [dApp] Fix Avatar display bug.

- packages/graphql/src/resolvers/IdentityEvents.js
I had overlooked that automatically "upgraded" `avatar` to `avatarUrl` fields were being set from GraphQL without an IPFS protocol in the URI (eg they looked like 'QmS4...', rather than 'ipfs://QmS4...'.) This is fixed in this PR and the correct format is now returned.
However, we also have 149 cases where a user profile was edited with an old style avatar data field and no change was made to the avatar image. If this happened, then the "ipfs://"-less url would be saved into the profile JSON. I've added a check to GraphQL that will fix data up, so that everything coming from out of the GraphQL avatarUrl field will be correct and consistent.
Fixes #2322
> Consistent AvatarUrls

- packages/graphql/src/resolvers/IdentityEvents.js
Fix foolish crashing bug for when an identity has no avatar. No idea how I missed this, must have tested on only identities with avatars.
> Fix for error when identity has no avatar

- dapps/marketplace/src/pages/settings/Settings.js
This fixes the Mutation refetch on the settings page.  It was changed to a string in 8d548ba96af932a29ca0f82f36ba49b12f9f8f2c for some reason, but [the Apollo docs don't really explain what the string option is for or how it works](https://www.apollographql.com/docs/react/essentials/mutations#props).  @Nick?
> fixes Mutation refetch on Settings page in marketplace dapp.

- packages/eventsource/src/index.js
- packages/graphql/src/resolvers/Listing.js
- Sets graphql listing cache to 15s(block time)
- Throws an error on listing not found in eventsource
Ref: #2346
> Some caching tinkering

- packages/graphql/src/resolvers/Marketplace.js
Changing graphql server caching to 15s in the Marketplace.listing resolver.
Ref #2346
> Lowers graphql cache to 15s for Marketplace.listing resolver

- packages/graphql/README.md
- packages/graphql/src/contracts.js
Adds the ability to specify an explicit web3 JSON-RPC provider URL with `WEB3_PROVIDER_URL`
This an okay location to do it?  Wanted to keep the config files clean.  Could probably use `customConfig` for `setNetwork()` as well and do it just for graphql server?
> Adds WEB3_PROVIDER_URL env var

- infra/discovery/src/listener/handler_marketplace.js
adds a defensive check with better/clearer error for when a listing/offer cannot be fetched.  The error shown in #2390 doesn't really explain anything and is more or less a side-effect.
Ref #2390
> Simple PR for a cleaner error message in Marketplace event handler

- packages/graphql/package.json
- packages/graphql/src/utils/metricsProvider.js
- yarn.lock
It was reported to us by Alchemy that our invalid `eth_getBlockByNumber` requests were actually due to a parameter tacked on by web3-provider-engine[1].  They also explicitly use this parameter in their `latest` event handler[2].
This also required another PR to web3-provider-engine(https://github.com/MetaMask/web3-provider-engine/pull/316), and has been reported (https://github.com/MetaMask/web3-provider-engine/issues/311). So, now there's two outstanding PRs and this adjusts the dependency to use another branch of my fork[3] that combines both.
[1] https://github.com/MetaMask/web3-provider-engine/blob/a17a32fab2717e5c6d600c5a8c25f9591c085aff/index.js#L30
[2] https://github.com/MetaMask/web3-provider-engine/blob/a17a32fab2717e5c6d600c5a8c25f9591c085aff/index.js#L130
[3] …
> Fixes issue with Alchemy and web3-provider-engine's eth_getBlockByNumber requests

- infra/growth/src/util/tokenDistributor.js
- packages/token/package.json
- packages/token/src/config.js
- packages/token/src/contractHelper.js
- packages/token/test/token.js
The truffle-privatekey-provider package was causing the OGN payout script to error out due to incompatible changes made in recent versions of web3-provider-engine.
This PR replaces it with plain web3 calls.
> [Token package] Replace truffle-privatekey-provider with web3

- infra/growth/src/resources/rules.js
- infra/growth/test/rules-april.test.js
- infra/growth/test/rules-june.test.js
- infra/growth/test/rules-may.test.js
- infra/growth/test/rules.test.js
With the launch of meta-txn, the listener back-end will be recording GrowthEvents (e.g. Identity updates, Listing Sold/Purchased, etc...) under the address of either the wallet (in case user paid for gas) or the proxy (in case relayer paid for gas).
This PR updates the rules logic so that it loads events recorder under the wallet and any proxies owned by it.
The DApp always queries the growth back-end using the wallet address regardless of the wallet having aproxy or not. As a result, the user should see rewards for actions performed by either wallet or proxies.
Note: the fraud and payout pipeline needs to be updated to take into account proxies. I'll handle that as a separate PR.
> [Growth] Query events from owner and proxies

- dapps/marketplace/src/components/WaitForTransaction.js
Ref: #2434
Checks for `blockNumber` in a tx receipt, as Parity will return receipts for pending transactions.  Currently, the `WaitForTransaction` component's logic would make the user think the tx has been mined and confirmed when in fact, neither are true.
> Checks for blockNumber when waiting on tx to be mined

- packages/graphql/src/providers/index.js
I don't really know why WPE uses so many emitters... or why this level only showed up on staging... so this raises them to get rid of the warning... for *reasons*.  The previous level of 50, doesn't trip the warning on my local, but it does on staging.
(node:19) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 51 data listeners added. Use emitter.setMaxListeners() to increase limit
Wish I had a better argument for this PR other than I'm attempting to squash the warning.
> Raises event emitters for web3-provider-engine

- dapps/marketplace/src/hoc/withGrowthRewards.js
Provide growth Rewards information even when web3 account not present. Just assume that OGN has 18 token decimals.
> show ogn badnge when no web3 provider available

- dapps/marketplace/index.js
Adds `NOOPENER` env var to prevent the marketplace dapp start script from opening a browser.  The `opener()` call keeps destroying my browser profiles and it's driving me mad.  This should not change how people normally use the `start` script.
> Ability to prevent dapp start script from opening browser

- packages/graphql/env.js
- packages/graphql/server.js
- packages/graphql/src/resolvers/IdentityEvents.js
- packages/graphql/src/server.js
For some reasons the IdentityResolver.js file was loaded even before loading the environment variables. Most likely has to do something with the order of require/import during babel transpilation.
> Fix attestations on staging and production

- devops/dockerfiles/origin-relayer
Think this was introduced in b32bcece2dad8da6fa864e3de95837029023ec82.  Appears to be missing as a dep for the bridge container.  Seen in Cloud Build:
error Couldn't find package "@origin/identity@^0.1.0" required by 
"@origin/bridge@0.1.0" on the "npm" registry.
> Fixes missing infra/identity from bridge container

- devops/kubernetes/charts/origin/values.yaml
Simple version bump for the ipfs container image.  I don't think there's any special migration work that needs to be done.  I did do a test update on my local from an even older version and it went clean.
Might be worth watching the dev+staging builds to make sure.  The base32 file hash encodings should currently be opt-in, but there's a chance their docker image could behave differently.
Ref: #2408
> upgrades go-ipfs to v0.4.21

- devops/kubernetes/charts/origin/templates/ipfs.statefulset.yaml
Was difficult to test this locally, but created a Dockerfile with an `ENTRYPOINT` the same as this kube deployment `command` and the behavior was the same.  ~~Updating it to include the `daemon` subcommand and the option `--migrate=true`.  This is the same as the default docker implementation.  I don't think this upgrade requires migrations, but I've used this in the past without issue.~~
~~@tomlinton For the sake of time, I'd like to merge this now to get things working again, but if you'd like to remove the auto-migrate option in the future let me know.~~
EDIT: For now, I'm just going to be careful and remove the auto-migrate option and see how it goes.  It might be worth adding later, though, as it could cause future version upgrades to fail.
Ref: #2488
> Fixes IPFS container issue

- infra/ipfs-proxy/package.json
- yarn.lock
Might've opened a can of worms here.  Seen on the ipfs-proxy container on dev:
Error: Cannot find module 'superagent'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object.<anonymous> (/app/src/app.js:6:17)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> adds missing dependency superagent for infra/ipfs-proxy

- dapps/marketplace/src/components/ExternalAnchor.js
- dapps/marketplace/src/hoc/withIsMobile.js
- dapps/marketplace/src/pages/_Footer.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
This is to stop links outside of the DApp in the mobile app. Visiting these will likely crash the app and it is not something we really need to support.
- Added ExternalAnchor component to strip anchors if we are in the mobile app
- Removed some links that don't make sense in the footer if the anchor is removed
- Added isMobileApp to withIsMobile HOC, I think you were asking about this earlier @nick, maybe you did it a different way which I can integrate here instead of this method
> Hide footer links in mobile app

- infra/relayer/src/purse.js
There appears to be a bug in Purse but there's not enough info in the logs.  One tx stuck in pending.  This will help debug.
> Log a re-broadcast error in Purse

- infra/relayer/migrations/20190620211348-enum-add-gaslimit.js
fixes down() migration function for enum-add-gaslimit.  Tested an `db:migrate:undo` on my local and this works.  Thanks for catching this @franckc
> Fixes migration revert error in relayer

- dapps/admin/src/pages/listings/_EnsureModerator.js
- dapps/admin/src/queries/Mutations.js
I was calling MetaMask directly for signing moderator logins, but it turns out I was doing so in a way that only worked for local unlocked accounts. I've updated the code to use our standard origin GraphQL mutation for signing this message.
Thanks to @nick for the cleaner way to call a GraphQL mutation.
> Sign moderation logins with our GraphQL signing code.

- infra/relayer/package.json
- infra/relayer/src/purse.js
Initially this was setup so that individual child accounts could get funded when they need to.  This caused Purse to try and fund 3 accounts when the balance of the master could only afford to fund 2.  Not the end of the world, but it caused a tx to be forever-broadcast until I guess the master balance was satisfied enough to send it.  
In addition to this change, the values for baseFunding could be set differently if 0.5 Ether is too much, but I'm going by @franckc's suggested numbers here.  I lowered prod down to 2 children so things would run smoothly for now.
> Child funding changes

- infra/relayer/src/purse.js
- infra/relayer/test/purse.test.js
When nonce was recovered from redis upon a service restart, the value stored for `txCount` would be a string.  This caused the increment operations `+=` to actually append a number to the end of the string value instead of actually doing a Number increment.
> Purse: Fixes nonce recovery from redis type issues

- infra/relayer/src/purse.js
I don't even know... `.count` isn't a thing and never has been.
> Purse: Quick fix

- dapps/marketplace/src/pages/user/Profile.js
Should fix the following issue:
- Go through a onboarding flow on a new Ethereum account
- Try to do an attestation without setting a `description`
`description` will be `undefined`/`null`. GraphQL doesn't accept either as a string.
> Exclude undefined values when publishing profile

- infra/relayer/src/purse.js
Simple change, should take care of #2545.  Makes sure to set the transaction count in redis if it's inaccurate or missing.
> Purse: nonce persistence fixes

- infra/messaging/migrations/20190625030841-add-content-hash.js
Sequelize is cool.  Not really sure how I missed this in testing.  Maybe I had the DB disabled or something.  But @tomlinton renamed the columns in the DBs manually(which fixed the issue), and I'm changing this migration to match.
> fixes column name in migration

- packages/eventsource/src/index.js
Reported by a user to @AustinVirts. User wanted to buy multiple gift cards without having to do individual transactions for each.  This allows the gift card to be multi-unit.
>  GiftCardListing should be multiUnit

- mobile/package-lock.json
- mobile/package.json
- mobile/src/screens/marketplace.js
Handle Android hardware back button in WebView. The diff looks horrible, but its just because the whole marketplace render function needed to be wrapped in <AndroidBackHandler>. Closes #2559.
> Android back fix

- devops/kubernetes/charts/ethereum-network/templates/geth-genesis.configmap.yaml
- devops/kubernetes/charts/ethereum-network/values.yaml
This updates geth to v1.8.27, and makes an attempt at a byzantium fork.  
The fork is tricky as I can't find an authoritative source for how this goes down.  [This StackExchange answer](https://ethereum.stackexchange.com/a/29412/8492) might be the best idea.  I think if we bring up a 3rd miner node with that genesis block, maybe stop the other 2 miners and let this one do its thing, the other should fall in line.  Then maybe if we have to clear state on nodes 0 and 1 and re-sync(not clear if that's necessary).
Though there's also a chance of an incompatibility, and if nodes 0 and 1 come up and don't like the conflicting genesis hash, everything could come to a halt.  So, a bit of a gamble here.  Would be interested in your take on it, @tomlinton.
> Geth upgrade and byzantium fork

- mobile/src/graphql/queries.js
- mobile/src/hoc/withOriginGraphql.js
- mobile/src/screens/marketplace.js
- mobile/src/screens/onboarding/ready.js
- Adds a (subtle) error if identity didn't publish via relayer for whatever reason.
- Blocks on the last screen of the onboarding process until the identity is actually ready. I know we talked about a spinner inside the profile dropdown of the DApp @micahalcorn, but at this point it is a lot of complexity in both the DApp and mobile and this is relatively simple. I think we should do this and revisit later if we want something nicer.
> Better mobile profile publishing feedback

- mobile/src/components/back-arrow.js
- mobile/src/screens/onboarding/email.js
- mobile/src/screens/onboarding/growth-terms.js
- mobile/src/screens/onboarding/name.js
- mobile/src/screens/onboarding/phone.js
- mobile/src/screens/onboarding/pin.js
- mobile/src/styles/onboarding.js
Adds back arrows where needed in the mobile onboarding process according to what is in Zeplin. Positioned them slightly differently (alongside titles) to try and save space.
> Mobile onboarding back arrows

- docker-compose.yml
The bridge server now requires Redis, but the docker-compose.yml file wasn’t updated to configure the needed connection URL.
This fix lets the bridge server start again in our docker env.
> Bridge server now requires Redis.

- packages/graphql/src/configs/docker.js
Fixes an error reported by @DanielVF with local docker.  The listener would scream in pain because it didn't have the address for the ProxyFactory.
> Fixes local docker config for ProxyFactor

- packages/contracts/contracts/identity/IdentityProxy.s
I've added `requires` to the external and ERC20 calls that did not have them, per the discussion in 
#2009. This will prevent parts of these transactions from silently failing while others parts succeeded.
> Make all external contract calls and ERC20 actions require success

- dapps/marketplace/src/pages/transaction/_EscrowDetails.js
- dapps/marketplace/src/pages/transaction/_OfferDetails.js
- dapps/marketplace/src/pages/transaction/_Progress.js
Fix > characters in CSS. The uglify/minify breaks the escaping so we end up with this:
> Fix escaped ›

- packages/graphql/src/contracts.js
When `useLatestFromChain` is set to `false`, the `latestBlock` needs to be set by some external force.  In this case, `@origin/graphql`'s block header websocket listener.
Closes #2619
> Makes sure setLatestBlock is called for ProxyFactory contract

- devops/cloud-functions/gcf-pin-ipfs-hash/fixtures/listing-log.json
- devops/cloud-functions/gcf-pin-ipfs-hash/fixtures/profile-log.json
- devops/cloud-functions/gcf-pin-ipfs-hash/index.js
- devops/cloud-functions/gcf-pin-ipfs-hash/test.js
- devops/cloud-functions/gcf-pin-ipfs-hash/util_base58.js
This fixes the IPFS pinner to work with the new post-GraphQL data format.
Parsing tests are updated to check that it works.
I can't actually test the whole integration with google function, and the whole devops side. Let me know if there are any problems.
> Fix IPFS Pinner by redoing parsing to match new formats.

- dapps/marketplace/src/components/DownloadApp.js
- dapps/marketplace/src/components/ImagePicker.js
- dapps/marketplace/src/pages/create-listing/ChooseCategory.js
- dapps/marketplace/src/pages/create-listing/ChooseListingType.js
- dapps/marketplace/src/pages/listing/ListingDetail.js
- dapps/marketplace/src/pages/listings/ListingCards.js
- dapps/marketplace/src/pages/nav/Profile.js
- dapps/marketplace/src/pages/settings/Settings.js
- Removes the mobile app CTA from listing creation when in our app
- Uses the aspect ratio that we recommend to users (4:3) on desktop
- Makes appliances listing creation use the hourly fractional steps
- Causes the strenth meter to link to the profile screen
- Adds a link to the test builds buried in developer mode settings
[Deployed to test build](https://originprotocol.github.io/test-builds/micah/#/) ☑️
> Mo' DApp Cleanup

- infra/relayer/src/purse.js
Some calculations that shouldn't run in certain cases now hidden in an if/else, and fixes the value of `MIN_CHILD_BALANCE`
> Purse fixes

- infra/relayer/src/relayer.js
- infra/relayer/test/relayer.test.js
We were storing IP+geo only for tx declined by risk engine.
Store it for all transactions so that we can use that data for fraud detection if needed.
> Store IP+geo in relayer_txn table

- dapps/marketplace/src/hoc/withGrowthRewards.js
Fix bug where rewards don't show if you are not enrolled into rewards program
> Fix rewards bug

- infra/relayer/src/purse.js
- infra/relayer/src/relayer.js
This makes sure the relayer only accepts one pending transaction per proxy contract.  It's a short-term solution to prevent bad nonces for #2631.
I'm not really sure if this gels with the behavior of the dapp with profile updates. @nick?
> Relayer: One tx per proxy

- infra/relayer/migrations/20190707034049-add-relayer-txn-gas-price.js
- infra/relayer/src/models/relayer_txn.js
Note: as opposed to creating yet another migration, I'll run some sql directly on DB to fix the type.
> [Relayer] Use bigint rather than integer to store gasprice

- mobile/src/screens/onboarding/growth-terms.js
Adds a page title and back arrow to the growth ineligibility screen on mobile. Different to what is in Zeplin. But it sounds like we wanted this from chatting with @micahalcorn.
> Add title and back arrow to growth ineligible screen on mobile

- infra/bridge/src/controllers/utils.js
- infra/bridge/test/utils.js
- mobile/src/screens/onboarding/email.js
- mobile/src/screens/onboarding/phone.js
When doing duplicate checks for emails and phones we don't want to display the import warning in mobile if:
- the account found with the duplicate is the same account that was imported
- it was the first created account with that email/phone
This is because we consider the first created account to be OK but may take action against duplicate accounts created later.
> Don't display warning on duplicate email or phone if first account

- devops/kubernetes/charts/origin/templates/dapp.ingress.yaml
Only use the additional hosts we added on prod to avoid dev/staging trying to issue certs for these domains.
> Remove extra dapp hosts from non-prod namespaces

- README.md
- dapps/marketplace/public/template.html
This PR updates the OG tags for social sharing to link back to our new domain: shoporigin.com.
> Update OG tags to point to shoporigin.com

- infra/faucet/src/eth.js
- packages/graphql/src/resolvers/web3/transactions.js
Adds a check on the presence of blockNumber in the receipt to determine if tx was mined.
This is a difference in behavior between Geth (which Infura uses) vs Parity (used by Alchemy).
This may help solving #2623
> Check on blockNumber in receipt

- dapps/marketplace/src/pages/user/Profile.js
Fixes a bug where unpublished data in localStorage never expired.
It occurred most likely due to [this line](https://github.com/OriginProtocol/origin/compare/shahthepro/identity-bug-fix?expand=1#diff-909bfb587479776ba538c7dccd979214L532). I missed to include the timestamp while writing the data to localStorage, when there is none.
This made the `hasDataExpired()` function to always return `false`. (`Date.now() - undefined > 3600000` === `NaN > 3600000` === `false`).
I'm still unsure if this caused #2728 to happen.
> Fix Profile Page Bug

- devops/kubernetes/charts/origin/templates/_helpers.tpl
- devops/kubernetes/charts/origin/templates/dapp-shoporigin-redirect.ingress.yaml
- devops/kubernetes/charts/origin/templates/dapp.ingress.yaml
- Removes dapp.originprotocol.com from the dapp ingress and replaces it with shoporigin.com
- Adds another ingress for dapp.originprotocol.com with a permanent redirect to shoporigin.com
Deployed this on `prod` to make sure it works so it is already configured.
> Configure dapp.originprotocol.com to redirect to shoporigin.com

- packages/graphql/src/utils/validateAttestation.js
[As per web3's docs, passing `message` directly as string is supported](https://github.com/ethereum/web3.js/blob/1.x/docs/web3-eth-accounts.rst#L373-L387). We don't have to hash it separately.
We can either pass the `message` and `signature` or just an object with `{messageHash, v, r, s}`.
In all other places, we pass the `message` and are not hashing it. So just for consistency.
> Pass message directly to `web3.eth.accounts.recover()`

- infra/relayer/src/relayer.js
Relayer was adding signatures to memory for the dupe check even when the request was preflight.  So the followup real request would always fail.  This makes sure not to add the signature to memory on preflight checks..
> Fixes a relayer dupe issue causing all relays to 429

- packages/web3-provider/src/subproviders/EthGasStationProvider.js
EthGasStationProviderwas not forwarding requets to the next subprovider when the methods were things it didn't care about.
> EthGasStationProvider not forwarding

- packages/graphql/src/contracts.js
Use EthGasStationProvider on staging so it can be tested before hitting prod.
> Use EthGasStationProvider on staging

- infra/growth/campaigns/august.js
- infra/growth/src/apollo/adapter.js
- infra/growth/src/resources/rules.js
- infra/growth/src/scripts/manageCampaign.js
- infra/growth/test/apollo-adapter-august.test.js
- infra/growth/test/rules-august.test.js
- packages/graphql/src/typeDefs/Growth.js
On the FE, we need to be able to show if the action of sharing a piece of content was completed or not. With the previous implementation it was not possible since all the contents were handled by a single rule.
This PR defines 1 rule per content that is shareable.
> [Social Sharing] Define 1 rule per shareable piece of content

- dapps/marketplace/src/pages/settings/Settings.js
- dapps/marketplace/src/queries/Config.js
- packages/graphql/src/typeDefs/Web3.js
Adding growth server to **/#/settings** configuration page: 
- ~[ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation~
- ~[ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)~
> Sparrow dom/add growth to config

- infra/bridge/src/controllers/promotions.js
- infra/bridge/test/promotions.js
- infra/growth/campaigns/README.md
- infra/growth/campaigns/august.js
- Twitter shortens and replaces all the text that it identifies as URLs. So, if we have a text like `ogn.dev/mobile`, it is shortened to `t.co/xxxxxx`. Twitter does give a mapping of shortened URL to original URL. But the original URL in the mapping prepends `http://`. So there will be a mismatch in content which will result in "Share" event not being resolved by `bridge`.
The easiest way to overcome this will to manually prepend `http://` in growth campaign rules.
- Twitter also truncates the tweet content (if the content is longer than 140 chars, I guess) but also gives the full text along with a preview. Should prefer `event.extended_tweet.full_text` (if it exists) over `event.text`
> [SocialRewards] Fix tweet content bug

- infra/bridge/src/controllers/hooks/index.js
- infra/bridge/src/controllers/promotions.js
- infra/bridge/test/hooks.js
Fix for #2847 
Use id_str rather than id to avoid JS big number issue. See [this doc](https://developer.twitter.com/en/docs/basics/twitter-ids.html).
Note: this won't fix the data we store in attestation.value - it has the wrong rounded id. This will be addresses in a separate PR.
> [SocialSharing] Fix for verification

- dapps/marketplace/src/pages/user/Profile.js
- packages/graphql/src/mutations/identity/deployIdentity.js
- packages/validator/src/schemas/profile_2.0.0.json
As of now, DApp fetches, caches and sends all the data that'll be part of the user identity (to be deployed to IPFS). GraphQL just validates it and publishes the data.
I have updated this as follows:
1. DApp only sends changed fields or new/updated attestations. It caches them to localStorage for an hour
2. GraphQL combines these fields with last deployed identity, deduplicates and validates them before publishing to IPFS and the blockchain
This should fix #2728
> Move merging Identity updates to GraphQL 

- dapps/marketplace/public/template.html
- dapps/marketplace/src/components/Analytics.js
Closes #2319 - We now pass query strings on through to Google Analytics. This allows us to track the user's search queries in Google Analytics.
Closes #2832 - We now do not track page views from localhost. Before we were recording every automated CI run into our stats, and likely every developer action, making a very lopsided view of the actual activity on our Dapp.
For example, the "Create Listing" page is heavily biased to tests and developers.
Finally, a bonus bug fix - we were always recording a users first page view on the Dapp as "/". This meant we didn't actually know which page a user actually arrived to the Dapp on.
> Google Analytics Improvements

- infra/bridge/src/controllers/hooks/index.js
- infra/bridge/test/hooks.js
We don't have signature validation for webhook endpoints at present. This means anyone can post any events to the webhook endpoints. This PR should fix that.
> [SocialRewards] Add signature validation to webhook controllers

- docker-compose.yml
Fixes a race between graphql and the Ethereum JSON-RPC service.
> Make graphql wait on services container

- packages/graphql/src/configs/docker.js
`IdentityProxyImplementation` address was missing in graphql config for docker network. 
ref #2869
> Fixes docker graphql config for proxy implementation

- infra/growth/src/apollo/app.js
- infra/growth/src/apollo/resolvers.js
Fix a bug that was introduced with origin admin inspector where a user would not be signed out of Origin Rewards when he changes current wallet. 
- ~[ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation~
- ~[ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)~
> Sparrow dom/fix growth admin override

- infra/bridge/test/email.js
- infra/bridge/test/exchange-rate.js
- infra/bridge/test/hooks.js
- infra/bridge/test/promotions.js
`DEL *` isn't a valid redis command. So switching to `FLUSHALL` command to clean out all keys before each test
> Change `DEL *` to `FLUSHALL`

- infra/discovery/src/apollo/app.js
- infra/growth/src/apollo/app.js
- packages/graphql/src/server.js
Enable debug and log stack traces on the server side for all our graphQL servers: graphql, discovery and growth.
We can discuss and implement in a separate PR our strategy for logging server side exceptions to Sentry.
> [GraphQL] Log stack traces on server side

- infra/discovery/src/apollo/resolvers.js
The interface to the discovery server for searching listing was modified to use argument "search" rather than "searchQuery" in PR #2873. But the caller of this interface, the graphql server, was not updated. This caused searches in the DApp to always used empty search terms.
> [Discovery] Fix broken search

- infra/discovery/package.json
- infra/discovery/src/lib/search.js
- yarn.lock
Some listings on staging are test data and are malformed. Their price.amount field is set to null.
It causes the sorting painless script to crash. This could also happen in prod due to bugs or malicious user writing directly listing data to IPFS rather than thru our code.
This PR adds some defensive code.
> [Search] Handle malformed listings with no price

- infra/discovery/src/lib/search.js
Use a try/catch statement in search sorting script rather than trying to use defensive coding.
Thanks @sparrowDom for this suggestion, it is much cleaner and robust ! :)
I ran the query manually in prod and it seems to work well.
> [Search] Catch exceptions in sorting script

- dapps/marketplace/src/components/SendMessage.js
This fixes a couple of issues:
- `messaging.id` from the graphql is the sending user, which apparently I did not expect for some reason, nor did it show up in my local tests(?)
- The forward after sending a message should send to the actual recipient and not the proxy address
> Proxy messaging bug

- dapps/marketplace/src/pages/settings/Settings.js
A very minor fix for the dropdown.
Probably broken when #2938 got merged [because of this line](https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/pages/listings/SortMenu.js#L206)
> Fix dropdown width in Settings Page

- infra/discovery/src/lib/search.js
- infra/discovery/src/listener/handler_marketplace.js
Pin API version rather than using the default in the client.
Other misc fixes:
- Await for listing to be indexed in listener
- Use default exchange rate if we fail fetching from redis
> [Search] Pin elasticsearch API version in the client

- packages/messaging-client/package.json
- packages/messaging-client/src/Messaging.js
- yarn.lock
Upgrade crypto-random-string and fix code for breaking change:
`Breaking:
Move the length argument to an options-object 16a6364
cryptoRandomString(10); → cryptoRandomString({length: 10});
`
Fixes #3055.
> Upgrade crypto-random-string

- packages/graphql/src/resolvers/messaging/Conversation.js
I think the intention here was 1 second before the first message sent to the support account, not 1 second before the last message sent. 
Fixes #2952.
> Fix order of support messages

- packages/graphql/src/contracts.js
- packages/web3-provider/package.json
- packages/web3-provider/src/ProviderEngine.js
- packages/web3-provider/src/index.js
- packages/web3-provider/src/subproviders/EthGasStationProvider.js
- packages/web3-provider/src/subproviders/MetricsProvider.js
- packages/web3-provider/src/subproviders/Subprovider.js
- packages/web3-provider/src/subproviders/ThrottleRPCProvider.js
- packages/web3-provider/src/subproviders/createPayload.js
- packages/web3-provider/test/index.js
- yarn.lock
Stripped down web3-provider-engine to the bare bones.
The original web3-provider-engine had it's own block tracker, event emitter and a bunch of other stuff we don't need. This PR gives us a bare bones web3-provider-engine for our Metrics, ThrottleRPC and EthGasStation providers.
Will hopefully reduce blockNumber calls significantly...
> Pared down web3-provider-engine

- packages/graphql/src/contracts.js
- packages/mobile-bridge/src/index.js
~~To rule in/out the `EthGasStationProvider`~~ from causing #3266, and also the `createEngine`provider init for webviews.
> Temporarily disables EthGasStationProvider subprovider in mobile-bridge

- infra/relayer/src/purse.js
- packages/web3-provider/src/index.js
when using createEngine, EthGasStationProvider must be initialized separately
> Gasstation fix for relayer

- dapps/marketplace/src/components/WaitForTransaction.js
This is my quick and dirty solution for #3284.  I don't think this should be the long-term solution, but I think it'll work here.  This straight up ignores Invalid JSON-RPC errors in WaitForTransaction. When they happen with `eth_getTransactionReceipt`, there's no reason to suspect they aren't just a one-off.
This is untested, because testing it would require me rigging up some insane fake JSON-RPC interface, so beware.
> Ignore JSON-RPC errors when waiting on a transaction

- packages/graphql/src/mutations/uniswap/swapToToken.js
We are still getting reports in production of the DAI swap failing.
Increasing the margin from 1% to 2%, to stabilize things in the short-term.
> Increase ETH excess to 2% when buying DAI

- dapps/marketplace/src/components/TransactionStages.js
Add progress bar stages for offer rejected / offer declined. Before this fix it just showed an empty 3 stage progress bar. 
Result looks like this: 
**Related issue:** https://github.com/OriginProtocol/origin/issues/3306
> add offer withdrawn stages

- dapps/marketplace/src/pages/listing/ConfirmPuchase.js
Set multiUnit display as default for UI in `ConfirmPurchase` component.  Issue #3304
> Fixes multi-unit for ConfirmPurchase

- packages/graphql/src/utils/proxy.js
When `DISABLE_CACHE` is set to `true`, don't memoize proxy functions.
closes #3337 
CC @nick
> Adds the ability to disable cache for proxy utils

- devops/kubernetes/charts/ethereum-nodes/templates/geth-tx.statefulset.yaml
Enables the debug API on geth nodes.  It should be noted that there's a potential for DoS with the debug API calls:
- `debug_setHead()`
- `debug_startGoTrace`
If we start using these for anything critical, we should disable `debug`.
> Enable the debug API over RPC for geth nodes

- devops/kubernetes/values/origin/values-dev.yaml
- packages/event-cache/src/EventCache.js
- packages/graphql/src/contracts.js
EventCache is useless without an address.  It should raise a storm without one.  Might help troubleshoot #2944.  Will not stop errors when this happens.
> EventCache should die without an address

- dapps/marketplace/src/utils/sentry.js
Env vars aren't naturally numbers
> Fixes environment context for Sentry in the dapp

- packages/graphql/src/contracts.js
- packages/graphql/src/utils/getId.js
Fixes version resolution in `@origin/graphql/src/utils/getId`.
> fix version resolution in getId functions.  closes #3387

- infra/growth/migrations/20190917214102-add-growth-participant-status-closed.js
- infra/growth/src/apollo/resolvers.js
- infra/growth/src/enums.js
- infra/growth/src/resources/authentication.js
- packages/graphql/src/typeDefs/Growth.js
This PR adds the 'Closed' status to the already existing statuses 'Active', 'Banned' on the growth_participant table.
It will be used to mark an account as terminated per request from the user. For example if the user gets confused and created duplicate accounts on mobile and desktop, then contacts us to keep a single account and close the others.
Note: this PR only handles the back-end. Front-end changes to properly display closed account will be handled separately (not a high priority since very few cases).
> [Growth] Add a new status 'Closed' to the growth_participant table

- dapps/marketplace/src/pages/user/User.js
According to @tomlinton's awesome observation, during the onboarding, EventCache is triggered to start fetching events(triggered by a query).  This is the last user of the `Identity` query.  I'm not 100% sure if onboarding is considered part of the `User` react page, however.  To me, it looks like the only other query in onboarding would be the `Wallet` query, which I don't think requires event logs.
Ref: #3229
> Use SkinnyIdentity graphql query on User page

- infra/relayer/src/purse.js
If a timeout occurs, don't continue thinking an account lookup is still in progress.  
Ref #3429
> Fixes relayer getting stuck in lookup state

- dapps/marketplace/src/components/growth/Action.js
- mobile/README.md
- mobile/src/screens/marketplace.js
Sorry @shahthepro I think we'll have to revert this because the current mobile code lives in `tomlinton/web3view` and this has been refactored. I think it'll be easier to redo this rather than try and merge. My fault as I've had this long running branch that hasn't been merged into master but is the basis for the current set of mobile releases.
I'll create a new PR for this.
> Revert "Fix Telegram Attestation on Mobile (#3405)"

- infra/notifications/package.json
- infra/notifications/src/app.js
- mobile/ios/OriginMarketplace/Info.plist
- mobile/package.json
- mobile/src/PushNotifications.js
- mobile/src/constants.js
- Removed requirement for a device token to be available for mobile to register. This only happens when the register callback fires which is never on iOS if the user never gets a notification prompt.
- Removed in code rate limiter because we have one in nginx ingress.
- Bump mobile version
- Fix Sentry import
Closes #3438.
> Mobile registry fix

- mobile/ios/OriginMarketplace.xcodeproj/project.pbxproj
- mobile/ios/OriginMarketplace/Base.lproj/LaunchScreen.xib
- mobile/src/AppContainer.js
- Change iOS launch screen to clear blue
- Remove other loading indicator that isn't really necessary as it is very quick (and it makes it look like a flicker)
- Migrated an iOS localisation thing
Closes #3421.
> iOS LaunchScreen update

- mobile/src/screens/account.js
Enables private key exports for mnemonic based accounts. Closes #3403.
> Enable private key export for mnemonic based accounts

- mobile/src/screens/marketplace.js
The KeyboardAvoidingView was introduced to fix an issue on Android where the keyboard would overlay the bottom of mobile modals. This was never an issue on iOS and the KeyboardAvoidingView caused a padding issue there (#3376). We can just disable the KeyboardAvoidingView on iOS to solve that.
Closes #3376.
> Disable KeyboardAvoidingView on iOS

- infra/notifications/src/app.js
- infra/notifications/test/marketplace.test.js
Due to the refactoring in #3453 the notification was not returning a response when called by the listener for an event such as ListingCreated which does not require to send any notification.
> [Notification server] Fix error handling

- dapps/marketplace/src/pages/transaction/mutations/WithdrawOffer.js
- packages/graphql/src/mutations/_txHelper.js
- `from` was not being properly set for withdrawOffer transactions
- relayer fallback to web3 was mistakenly disabled
Ref #3283
> Fixes relayer fallback and withdrawOffer

- packages/graphql/src/mutations/_txHelper.js
txHelper errors were not getting bubbled back up to mutations resulting in un-closable modals, eg when rejecting tx signatures.
> Ensure tx errors are passed back to mutations

- dapps/marketplace/src/pages/transaction/mutations/RejectOffer.js
Fixes `from` address used for offer rejection. 
Ref #3283
> Wrong from address in RejectOffer

- packages/web3-provider/src/subproviders/EthGasStationProvider.js
This might solve .:. #3512.  Doesn't appear that cross-fetch will timeout if the HTTP server doesn't timeout.  I suspect ethgasstation might not and this is blocking for longer than it should.
> Adds fetch timeout for EthGasStationProvider

- packages/graphql/src/mutations/_txHelper.js
Throws errors on invalid transaction hash in `txHelper`.  Trying to get to the bottom of #3275.  The graphql receipt resolver already does validation.  This is the only place I found that might be doing this from the dapp.
In the case of these invalid hashes being sent to Alchemy, it would generate an error anyway, so better to head it off early.
> Throw errors on invalid txhash

- packages/event-cache/src/utils.js
Couple calls to `console.warning` in `event-cache/src/utils.js`
> console.warning is not a thing

- infra/discovery/src/listener/handler_identity.js
Skip processing malformed event described in #3581 
This is a short-term fix to unstuck the listener while we investigate the root cause and come up with a better way to harden the listener against such failures.
> [Listener] Short-term fix to unblock the listener

- dapps/marketplace/src/queries/MessagingStatusChangeSubscription.js
- packages/graphql/src/resolvers/Subscription.js
- packages/graphql/src/typeDefs/Messaging.js
- packages/messaging-client/src/Messaging.js
A minor fix. `onMessagingStatusChange` event was published before the account was set. Related to issue #3625
> Fix onMessagingStatusChange subscription

- dapps/admin/webpack.config.js
- dapps/marketplace/webpack.config.js
Makes sure `WEBPACK_BUILD` is set for admin dapp build and cleans up the marketplace plugin definition a bit.
This env var was introduced for PR #3155 to deal with conditional imports of sequelize junk the dapp doesn't need.  Reduces the bundle by ~1MB.
> Env var cleanup and admin fix

- dapps/admin/src/pages/contracts/_DeployContract.js
- dapps/admin/src/pages/contracts/_DeployIdentityEvents.js
- dapps/admin/src/pages/contracts/_DeployMarketplace.js
- dapps/admin/src/pages/contracts/_DeployToken.js
- packages/graphql/src/mutations/token/deployToken.js
- packages/graphql/src/utils/proxy.js
The way account selection is done in the constructor prevents the state from being updated when the prop is updated.  Added handling of this case in a `componentDidUpdate` method.
This also handles some cases(geth?) where a `Proxy.owner()` call may return a zero-address.  This was specifically seen on dev and I imagine other geth JSON-RPC nodes as well.
This also sets `autoWhiltelist` to false because it's only useful in the case of the deployer account actually being the token owner, which I think is rare.
> Admin: DeployMarketplace account selection fix

- devops/kubernetes/charts/ethereum-network/templates/geth-miner.statefulset.yaml
- devops/kubernetes/charts/ethereum-network/templates/geth-tx.statefulset.yaml
Think we're running into pruning issues on the test net.  Probably shouldn't use `fast` syncmode(default) on a network with 2 nodes.
> Full syncmode for test network

- infra/bridge/src/controllers/hooks/telegram.js
Seems like the group type of Korean Telegram group is "supergroup" instead of "group". This makes the events from that group to be dropped
> Fix group type

- infra/growth/src/resources/campaign.js
Seems like `rewardStatus` in the GrowthCampaign model is not a reliable way to query or filter the active campaign. So changing that to use `CampaignRules.getStatus()` method
> Fix active campaign resolver

- infra/discovery/src/listener/webhooks.js
Log data sent by the webhook to debug why eth_address param is seen as undefined on the receiver side.
> [Listener] Add instrumentation to debug email webhook issue

- packages/graphql/src/contracts.js
- packages/graphql/src/utils/getEnvironmentalVar.js
`Event-listener` and `graphql` services failed because of a bug as a service. This fixes it
> Sparrow dom/event listener fix

- dapps/marketplace/src/pages/onboard/Wallet.js
Fix to a bug that was introduced after #3719 was merged.
The "download wallet" screen still appeared even if the user has a wallet installed (but not unlocked it)
> Redirect if wallet installed but not unlocked

- dapps/marketplace/src/components/EnableMessagingModal.js
- dapps/marketplace/src/hoc/withMessagingStatus.js
- packages/messaging-client/src/Messaging.js
Suppressing the event (when it is already in the same state) caused some unexpected behaviour on mobile randomly.
https://github.com/OriginProtocol/origin/compare/shahthepro/messaging-sub-fix?expand=1#diff-64fc362de5e424bf915ace27f6898007L122-L125
Also, `withMessagingStatus` HOC was not subscribed to MessagingStatusChange.
> Fix messaging status subscriptions

- infra/discovery/src/listener/handler_proxy.js
- infra/discovery/src/listener/listener.js
- infra/discovery/test/listener-handler.test.js
- infra/identity/src/utils.js
This PR fixes a couple of issues caused by PR #3773:
1. I disabled storing the full twitter and telegram profile in the identity data column.
This caused the twitter share reward calculation to break and always return zero (see [this code](https://github.com/OriginProtocol/origin/blob/master/infra/growth/src/resources/rules/socialShareRule.js#L174)). In the future I may change this code to lookup that data from the attestation table, but for the short-term this PR restores storing that data in the identity table. Once deployed, I'll run a backfill in prod.
2. There was a change in the argument to the proxy_handler (passing a context rather than a config object). This caused the proxy handler to get disabled.
> Store twitter and telegram profile in identity

- infra/identity/src/utils.js
Fixing a race condition in the identity code that was causing more than a single row per attestation type to get inserted in the growth_event table.
This is less performant but not worth optimizing prematurely.
> [Listener] Fix race condition in identity

- infra/identity/src/utils.js
Case mismatch on the address was causing the logic to fail loading attestation data.
> [Identity] Fix bug where identity table was not populated correctly

- infra/bridge/src/controllers/identity.js
Fix bug where owner's address should be used to load proxy address(es).
No impact on user but that bug was causing some column to not get populated in the identity table.
> [Identity back-end] Fix attestation metadata loading

- .circleci/docker_test_builds.sh
This got renamed by @shahthepro.
> Fix name of origin-auth in docker test builds

- .circleci/config.yml
Logged into Apollo Engine dashboard earlier and I guess confirmed that the trial is over.  The GraphQL schema test no longer works.  Disabling for now, might remove later.  It's not a super compelling test on its own, at least until we break something.
> Disabling apollo engine jobs

- packages/graphql/src/mutations/identity/deployIdentity.js
Now that the bridge identity write endpoint is enforcing auth, the request needs to include an authorization token.
> Add authorization header to bridge identity write requests

- devops/kubernetes/charts/origin/templates/bridge.ingress.yaml
Adding the Authorization header to the bridge's Access-Control-Allow-Headers since it will be used by clients to authenticate themselves against the bridge.
> Add Authorization header to Access-Control-Allow-Headers on bridge

- packages/graphql/src/contracts.js
imToken will throw an error trying to use `eth_subscribe` because of how web3.js detects websocket support.  This undefines `provider.on` to try and get around that detection.
There's a chance of unexpected behavior after this so we should keep an eye out.
Would like @micahalcorn to test out the test URL first: https://shoporigin.com/index.test.html
> imToken websocket kludge

- packages/graphql/package.json
- packages/graphql/src/resolvers/IdentityEvents.js
Fix for #3940 
The listener process imports and runs the graphql package.
Some of the queries issues by the listener to get the details about an offer involve getting data about a the buyer and seller. This was triggering the execution of the graphql identity resolver which makes a call to fetch() for getting the identity from the bridge server.
fetch() is not a supported call in Node.js which was causing an error.
> Use node-fetch rather than fetch in graphql identity code

- mobile/src/components/back-arrow.js
Make the back arrow in mobile onboarding match Zeplin colour. Closes #3938.
> Change back arrow colour

- infra/token-transfer-client/src/components/BonusModal.js
- infra/token-transfer-server/src/controllers/lockup.js
- infra/token-transfer-server/test/api/lockup.test.js
Implements minimum lockup of 10 to prevent 0 sized lockups and also users taking advantage of lockup rewards being rounded up, e.g. lockup 1 OGN for 1 OGN.
> T3 minimum lockup size

- infra/token-transfer-client/src/utils/index.js
- infra/token-transfer-server/migrations/20191114224700-revised-schedule-column-update.js
- infra/token-transfer-server/src/controllers/user.js
- infra/token-transfer-server/src/enums.js
- infra/token-transfer-server/src/models/user.js
Should have not done it the lazy way @franckc sorry! When I get the data to be imported here I realised we don't have the dates some of the amendments were signed so I needed a different way to represent accepted without a date. I could have just set it to some random date but that seemed ugly. It's good to have a record of who accepted via the onboarding flow and who didn't.
- ~~[ ] Update any relevant READMEs and …
> Use enums for T3 revised schedule states

- infra/token-transfer-server/src/scripts/send_welcome_token.js
- infra/token-transfer-server/src/templates/welcome.mjml
- infra/token-transfer-server/src/templates/welcome.txt
Remove pregenerated login tokens from welcome emails. Users can just jump to the T3 page and enter their email and get their own token. Avoids peoples initial tokens expiring and then them having to ask us.
- ~~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)~~
> Remove T3 tokens from welcome emails

- devops/dockerfiles/origin-token-transfer-client
- devops/kubernetes/charts/origin/templates/_helpers.tpl
- devops/kubernetes/charts/origin/templates/t3.ingress.yaml
- devops/kubernetes/charts/origin/templates/t3.service.yaml
- infra/token-transfer-client/src/components/pages/Dashboard.js
- infra/token-transfer-client/src/components/pages/Lockup.js
- infra/token-transfer-client/src/components/pages/WithdrawalHistory.js
- infra/token-transfer-client/src/constants/index.js
- infra/token-transfer-client/src/utils/index.js
- infra/token-transfer-server/src/shared.js
- Kubernetes configuration for a separate client with an employee hostname.
- Use only one unlock date env var, no need for two because employees and investors run on a separate server.
- Allow setting an employee specific API URL via an env var that is used when the employee hostname is in use.
> T3 separate employee API URL

- infra/bridge/src/utils/exchange-rate.js
Fix for #4061 
Added missing `USDT` to currencies array. 
Because https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/utils/currencies.js#L147 was referencing this code https://github.com/OriginProtocol/origin/blob/master/infra/bridge/src/utils/exchange-rate.js#L24, where USDT is missing, and below in FALLBACK_EXCHANGE_RATES , it is present.
> @origin/bridge did not return xrate for USDT

- infra/token-transfer-server/src/utils.js
Per title. Required for ip2geo to function.
> Add additional header to T3 server for originating IP address for Heroku

- mobile/src/screens/marketplace.js
- mobile/src/screens/partnerWelcome.js
Couple of referral fixes to mobile:
- Fixes the display of the partner splash and forced onboarding (addition of multiple prefixes conflicted)
- Sets the final onboarding redirect to `/campaigns` if the mobile app sees a referral code
Ref: #3948 
CC: @micahalcorn
> Partner referral fixes

- mobile/src/screens/marketplace.js
`prevProps.props` is not a thing.
Ref: #4101
> Fixes bad props reference in mobile app

- mobile/src/screens/marketplace.js
The redirect to `/campaigns` wasn't being injected because the conditional check would always eval false.  This fixes it to make sure it injects at least once if there's a referral code.
> make sure campaigns redirect is injected if referralCode injected at all

- dapps/marketplace/src/constants/config.js
- dapps/marketplace/src/hoc/withPartnerCampaignConfig.js
- dapps/marketplace/src/pages/onboard/Finished.js
- dapps/marketplace/src/pages/onboard/RewardsSignUp.js
- dapps/marketplace/src/utils/growthTools.js
- infra/growth/src/resources/authentication.js
Pull reward amount from `campaigns.json` for partner funnel dapp pages as the current method from PR #4115 will always return 0.
This is untested and depends on https://github.com/OriginProtocol/origin-website/pull/458
> Reward should come from campaigns.json

- infra/discovery/src/listener/listener.js
Decrease polling interval in order to reduce number of calls to Alchemy.
The impact is that there will be a longer delay for indexing listings.
But we have so few listings creation/edit that this should not be a concern.
> Increase listener polling interval from 5 to 30sec

- dapps/marketplace/src/pages/App.js
- dapps/marketplace/src/pages/ReferralRedirect.js
- dapps/marketplace/src/pages/growth/Welcome.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/onboard/RewardsSignUp.js
Should fix #4131 
When users click on "Sign Up" in the rewards landing page, they are redirected to `/onboard` only if they are not signed in.
After the sign in and do email and profile attestations, they are taken back to `/welcome` landing page.
> Fix rewards landing page

- dapps/admin/src/pages/_NodeInfo.js
The `data` object was being accessed even before the query loaded. This caused the admin tool to crash. This PR should fix it.
> Fix Admin Dapp

- infra/bridge/src/controllers/identity.js
- infra/bridge/src/utils/identity.js
- infra/identity/src/utils.js
Send phone,IP and country code as arguments when calling the website email webhook from the bridge when an identity gets updated.
> Pass phone, country and IP to the email webhook

- dapps/marketplace/src/hoc/withFingerprint.js
- dapps/marketplace/src/pages/growth/mutations/Enroll.js
- packages/graphql/test/availability-calculator.js
Previously, the user has to click on a button to sign a message and trigger the enroll mutation. Since the signing requirement was removed in favor of auth token, We no longer needed that extra modal. 
So, I had made that enroll mutation to auto run when `pages/growth/mutations/Enroll` component is rendered. The problem was that the fingerprint data took a couple of seconds to load. So when the component was rendered, fingerprintData was always `null`.
This PR will defer the enroll mutation until the finger data is loaded and cached.
> Defer enroll mutation until fingerprint data is available

- infra/token-transfer-server/src/controllers/account.js
Same as title.
Sorry, my bad for breaking this.
> [T3 server] Send country code rather than country struct when calling insight

- infra/token-transfer-client/src/reducers/transfer.js
All in the title! Now uses same method for both client and server calculation, which is what I intended but somehow didn't clean up.
> Fix T3 client side balance calculation for expired withdrawals

- infra/bridge/src/controllers/hooks/telegram.js
When an user sends `/start` directly to the bot, reply to them with a message to go through the flow on the DApp again.
> Notify users to go through Telegram Attestation on DApp

- packages/graphql/src/mutations/identity/deployIdentity.js
This change will have the following effect:
- The DApp won't store the identity blob to IPFS before it makes a request to the bridge server to save an identity. It means that the identity blob will only be saved in the DB and no longer both in IPFS and DB
- Note that we'll also lose identity history since previously we were relying on storing the history of identity IPFS hashes. I think that's tolerable given the situation we are in
Once this change is deployed and the client refresh to pick up the code, user should be able again to save their identity (e.g. set/update profile, add attestations).
Once we have fixed our IPFS cluster, we can if backfill the data in IPFS by reading it from the DB.
This change will NOT fix:
- profile pic uploads
- listing creation
- offer creation
> [IPFS outage] Stop writing identity data to IPFS

- infra/bridge/src/hooks/telegram.js
I had increased the rate limiting time to 3s while testing locally and missed to revert it before pushing :/
> Reduce telegram reply rate limit

- infra/auth-server/src/controllers/index.js
- mobile/src/PushNotifications.js
- mobile/src/screens/marketplace.js
- packages/auth-client/src/auth-client.js
User are not able to login if they have incorrect date/time on their machine. This PR adds an endpoint to auth server that will return the current timestamp of auth server.
It shouldn't be a problem security wise either, we already trust the client to send the timestamp. Also, we don't generate auth token if the time is in future or older than a few minutes.
This requires a mobile app update.
> Get time for login from auth server

- dapps/marketplace/README.md
Added a space to make valid markdown. Hi Origin!
> Space missing in markdown headline

- dapps/marketplace/src/pages/listing/PaymentMethods.js
- dapps/marketplace/src/pages/listing/_ConfirmPurchaseButton.js
Fixes 2 issues that caused purchase button to stays disabled:
- User is on desktop and not logged in to Metamask
- User has on a previous listing selected a purchase method (let say OGN) and then opens another listing that doesn't offer that purchase method.
Fixes issue: https://github.com/OriginProtocol/origin/issues/4039
> fix 2 bugs that cause payment button to be in loading state

- infra/bridge/src/utils/attestation.js
In Telegram the username is optional. So when an user without an username tries to do the attestation, the attestation body contains `{ username: { raw: null } }` which is invalid as per the attestation_v1.0.0.json schema. It has to be string value or not exist at all.
This fixes #4217
> Don't include username in attestation body if empty

- devops/kubernetes/charts/origin/templates/graphql.ingress.yaml
Some requests are just really slow right now.  This allows nginx to cope with that a little without failing outright.
> Increase graphql ingress proxy_read_timeout to 120s

- dapps/marketplace/src/pages/App.js
- infra/bridge/test/exchange-rate.js
PR #4248 had changed the fallback values in [exchange-rate.js](https://github.com/OriginProtocol/origin/blob/shahthepro/fix-exchange-rate-tests/infra/bridge/src/utils/exchange-rate.js#L18) file.
This PR updates that values so that the tests don't fail
> Update fallback value in bridge tests

- infra/bridge/src/utils/exchange-rate.js
Since OGN is now available on exchanges, this PR removes the hardcoded value of OGN and tries to pull the data from API
> Pull OGN value from API

- packages/graphql/src/mutations/identity/deployIdentity.js
As opposed to testing on NODE_ENV being test or docker, test on it being production or not.
> Disable identity IPFS writes in prod, enable everywhere else

- devops/kubernetes/charts/origin/templates/ipfs.ingress.yaml
Add a separate domain (`ipfs.ogn.app`) to IPFS ingress that bypasses `ipfs-proxy` and can access the add and link IPFS HTTP API methods.
> Dshop IPFS configuration

- dapps/marketplace/src/components/UserActivationLink.js
- dapps/marketplace/src/pages/listing/_ConfirmPurchaseButton.js
If onboarding started from listing purchase screen, redirect back to listing after onboarding. 
Fixes issue: https://github.com/OriginProtocol/origin/issues/4286
> Back to listing onboarding

- dapps/marketplace/src/pages/_Footer.js
The ::after pseudo-element with carrot icon for dropdowns (in footer at least) was capturing mouse events. Meaning that if you clicked *exactly* on the carrot, the dropdown would not open. Adding `pointer-events: none` prevents this capturing of mouse events.
Image showing region of un-clickable pseudo-element in dapp footer dropdown:
> Catch clicks exactly on icon in dropdowns

- infra/token-transfer-client/config/webpack.config.js
#4316 included a change that renamed an option in the T3 webpack config and broke the build. This fixes it.
> Fix Webpack config due to renamed option

- devops/kubernetes/charts/origin/templates/ipfs-issuer.service.yaml
- devops/kubernetes/charts/origin/templates/ipfs-issuer.statefulset.yaml
- devops/kubernetes/charts/origin/values.yaml
- devops/kubernetes/values/origin/values-dev.yaml
- devops/kubernetes/values/origin/values-prod.yaml
- devops/kubernetes/values/origin/values-staging.yaml
Essentially duplicates dapp-creator-issuer but parks it in front of origin-ipfs instead of the dapp container.  It uses the same image since there shouldn't be any deviation except for an env var and service.
> Adds origin-ipfs-issuer

- dapps/shop/backend-old/package.json
Fixes naming conflict caused by PR #4340
> Fix conflicting package name for backend-old

- packages/graphql/src/mutations/_txHelper.js
In an effort to deal with the tx receipt param issues we've been seeing(and me thinking they're web3.js internal), I moved the error event handler to also be used in `.catch()`.
> txHelper error handler change

- packages/mobile-bridge/src/index.js
The replacement block tracker in PR #4357 is missing a few methods that web3-provider-engine expects causing some errors.
> Missing block tracker methods

- mobile/src/components/origin-web3view.js
- mobile/src/hoc/withOriginGraphql.js
- mobile/src/screens/wallet.js
This uses "strategic" events to update the balance instead of an interval to poll for balance updates.  Currently this includes sending transactions and changing networks.
Anything I'm missing?
> Alternative to polling for balance updates

- dapps/marketplace/src/pages/transaction/mutations/FinalizeOffer.js
- When a buyer would release funds you would have modals stacked on top of each other.
- I added `confirmationModal: false` to the onClick function to fire off when a user click yes release funds
> Fix Modals on Modals

- devops/kubernetes/charts/origin/templates/growth.ingress.yaml
- infra/bridge/src/utils/webhook-helpers.js
- infra/growth/src/apollo/app.js
Get rid of the ingress rewrite so that we can have non-graphql routes on the growth server.
> [Growth] Serve graphql at / vs /graphql

- devops/kubernetes/charts/origin/templates/ipfs.ingress.yaml
Was seeing a bunch of this in the logs for IPFS requests:
[...] an upstream response is buffered to a temporary file [...]
The files generally weren't that large, either.  Adding this in hopes to reduce that a bit.
> proxy-buffers-number for ipfs ingress

- dapps/shop/backend/scripts/gcp/marketplace/README.md
- dapps/shop/backend/scripts/gcp/marketplace/build.sh
- dapps/shop/backend/scripts/gcp/marketplace/startup_script.sh
This is pretty much @DanielVF's work from [this gist](https://gist.github.com/DanielVF/3d5f9a0b47d93269cfda452cbe5c19a7) with the addition of a build script to make life easier, switches to [Openresty](http://openresty.org/en/getting-started.html) instead of nginx, and adds [lua-resty-auto-ssl](https://github.com/auto-ssl/lua-resty-auto-ssl) for automagic TLS support.
Basically, all you should have to do is have gcloud configured, install packer, and run:
./deploy.sh
> Dshop GCP VM image builder

- dapps/shop/src/utils/listing.js
- dapps/shop/src/utils/useConfig.js
Fix bug in admin config where the local marketplace address was used on any network. This caused a fun bug for the update listing button on Mainnet :)
> DShop admin config: only use local marketplace address when on network id 999

- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-mainnet.ingress.yaml
GCP has a [default request limit of 1MB](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#configuration-options). This should increase that to 50MB.
> Update Dshop's upload request size limit
