OriginProtocol/origin

- contracts/Listing.sol
The sections they use pretty match up to what @UnicycleMatt was asking for in last pr comments. I like the style, and being able to have auto-generated docs.
> Update contract code style to match ConsenSys/StandardBounties

- contracts/Listing.sol
- src/components/demo-app.js
- src/components/demo-buy.js
- src/components/demo-step-0.js
- src/components/demo-step-3.js
- src/css/demo-app.css
- src/services/contract-service.js
Big thing is ability to buy listings.
Some UI cleanup needed. Prices are now converted from Ether to Wei before interacting with contract.
> Buy listings

- README.md
Just updated the readme only.
I didn't change the testing private key.
> Update with new branding name, website, and GitHub URL

- config/env.js
- ecosystem.config.js
- scripts/start.js
- src/components/demo-step-1.js
- truffle.js
- Prep the app so that it can run under pm2 on live
- Change absolute URLs to relative where appropriate
- Setup truffle for deploying contracts as needed on Rinkeby test network
> Get dapp ready to run on testnet

- src/components/footer.js
Replaced Discord link with Slack link and added  target="_blank" links (to stay consistent with main webpage)
> Update footer.js with Discord link

- src/components/app.js
- src/components/listings-grid.js
Adds pagination to URLs as specified in https://github.com/OriginProtocol/demo-dapp/issues/64
> Issue/64 Use url params for pagination

- src/components/listing-card.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/services/contract-service.js
- src/services/origin-service.js
There is a tradeoff we're making here. We don't have as much granular
control over error handling.
As I went through this I put some effort into making the error handling more consistent. I could have gone further (there are still several inconsistencies), just didn't want to do too much at once.
Fixes #40
> Issue/40 Chain promises, rather than nesting them

- src/components/listing-detail.js
- src/css/app.css
- This is the first pass attempt at https://github.com/OriginProtocol/demo-dapp/issues/31
- On a side note I believe there are rooms of improvement regarding css and html layout structure with the current state of the app (we can talk offline) which can include but not limited to ..
1. changing from Css to SCSS.
2. Using built in `<p>, <h1>...<h6>, <label>` tags instead of wrapping text elements in `<div>'s`.
```
<div className="description">{this.state.description}</div>
```
vs.
```
<div className="lister">
<label className="lister-label">Creator </label>
<h6 className="lister-address">{this.state.lister}</h6>
</div>
```
3. className consistency.
http://getbem.com/introduction/
4. Utility classNames
https://blog.mariano.io/css-utility-classes-how-to-use-them-effectively-d61ee00dad2d
> Show Creator of Listing

- src/components/listing-create.js
Fixing what we broke in https://github.com/OriginProtocol/demo-dapp/pull/76
> put scroll to top back in between view state changes on the create page

- README.md
Update our links to the origin-js repo.
> Update readme to point to new repo url

- src/components/my-listing-card.js
- src/components/my-listings.js
- src/components/my-purchase-card.js
- src/css/app.css
- src/data.js
This updates `/my-listings` to use real data from the blockchain. It also adds the ability to close a listing. Since there is not yet an index server to allow querying listings by seller address, this code results in multiple requests, which may not scale to more than a handful of listings.
> Close Listings

- README.md
Update port specified in README: `9545` -> `8545` (see commit https://github.com/OriginProtocol/origin-js/commit/ddd9bf4381359a3b8ddccc70324d69bfbdaf57f1)
> Update readme port

- src/actions/Listing.js
- src/components/app.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/components/my-purchases.js
- src/components/purchase-detail.js
- src/components/timelapse.js
- src/components/web3-provider.js
- src/services/origin.js
Various fixes for the web3 1.0 upgrade
> Upgrade to web3 1.0

- src/components/my-listings.js
- src/components/my-purchases.js
- src/components/my-sales.js
- src/components/purchase-detail.js
With the upgrade to web3, we lost the current user account for several pages. This updates the necessary components to use the updated API. In the near future, we can put the accounts result in the store so that we can dry up these components.
> Use new accounts API

- package-lock.json
- package.json
- src/Store.js
- src/actions/Alert.js
- src/actions/Listing.js
- src/components/alert.js
- src/components/app.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/components/web3-provider.js
- src/css/alertify.css
- src/reducers/Alert.js
Remove the old alertify dependency and use our own redux-managed component instead
> Remove alertify dependency

- package-lock.json
- src/components/app.js
- src/components/not-found.js
Adding a 404 view for hash routes that do not match by adding a catch all react router route, and hooking it up to the not found component.
> add not found component and catch all route

- public/images/menu-icon-dark.svg
- public/images/menu-icon-light.svg
- src/components/dropdowns/connectivity.js
- src/components/dropdowns/notifications.js
- src/components/dropdowns/user.js
- src/components/navbar.js
- src/components/web3-provider.js
- src/css/app.css
This adds a drop-down menu to the navbar indicating the connectivity status of the blockchain, ipfs gateway, and bridge server. Currently, the gateway and server are static since we don't yet allow DApps to pass in those configuration options. I also added a dropdowns subdirectory for the relevant components.
> Connectivity status indicators

- src/actions/Listing.js
- src/reducers/Listings.js
- Show a notice when the currently selected network has no deployed contract
> No listing contract notice fix

- src/actions/User.js
- src/components/listing-detail.js
- src/components/purchase-detail.js
- src/components/review.js
- src/components/user-card.js
- src/css/app.css
- src/pages/profile/Profile.js
- src/pages/user/User.js
This updates several instances of user data to match some API changes. It also improves the UI in a few places. This should not be merged until after https://github.com/OriginProtocol/origin-js/pull/198.
> Repair user elements and improve the UI

- src/components/my-listings.js
- src/components/my-purchases.js
- src/components/my-sales.js
- src/components/purchase-detail.js
- src/css/app.css
- src/pages/profile/VerifyEmail.js
- src/pages/profile/VerifyPhone.js
- src/pages/profile/_Guidance.js
This includes a variety of copy improvements discussed with Matt & Aure yesterday. There will be a few more coming later today but I will wait for at least https://github.com/OriginProtocol/demo-dapp/pull/184 to get merged before I add those. It would be best to go ahead and merge this before then.
> Copy improvements

- src/components/my-purchase-card.js
- src/pages/profile/_Wallet.js
Just another couple of minor elements to hide 🙈
> Hide placeholder wallet history and button

- src/components/web3-provider.js
A recent change hardcoded the DApp so that it always acted as though it was in production, which requires a specific test network. This reverts that change so that the DApp again works with a local blockchain.
> Fix use of demo DApp using a local blockchain

- src/components/dropdowns/user.js
- src/components/listing-detail.js
- src/components/navbar.js
- src/components/review.js
- src/components/user-card.js
- src/css/app.css
- src/pages/user/User.js
- src/reducers/Alert.js
- src/reducers/Users.js
This adds the avatar to the user dropdown, repairs unnamed user placeholders, hides the blank buy box for announcement listings, and and provides a nav link for small screens to get back to the root path.
> User improvements

- public/schemas/announcements.json
- src/components/listing-card.js
- src/components/listing-create.js
- src/components/listing-detail.js
This addresses #209 by modifying the announcement listing schema to only allow a single enumerated value (`0`), which is also set as the `default`. The form component then detects this "auto value" and hides the price field.
> 📣Repair announcement listings

- src/components/listing-card.js
- src/components/listing-detail.js
- src/components/listings-grid.js
- src/css/app.css
🚧 _This is a work in progress but feel free to merge along the way._ 🚧
**Summary**
- Pins the sample listings to the beginning of the pagination
- Labels "featured" listing cards with a badge per Aure
> WIP: Finishing Touches

- src/components/listing-detail.js
- src/components/purchase-detail.js
- src/css/app.css
> Increased identity modal spacing

- src/components/purchase-detail.js
This was missed because the ListingDetail component is not being reused. It needs to be broken up into separate components
> Hide another thing

- src/pages/user/User.js
just fixing a minor error in image names
> minor icon fixes

- src/utils/languageNames.json
- src/utils/translationUtils.js
- translations/README.md
We have translators for these languages so this PR adds support for them
> Add additional languages as requested by translators

- src/css/app.css
- src/css/variables.css
This just makes use of some new color names that we generated in Zeplin so that they are easier to comprehend in the CSS.
> Add new color names

- src/components/listing-card-prices.js
- adding 30 min caching for call to Cryptonator API to prevent likely rate-limiting
* https://github.com/OriginProtocol/demo-dapp/issues/228
> Issue #228 : Price approximation failure

- src/components/my-purchase-card.js
- src/components/my-sale-card.js
- src/components/purchase-detail.js
Accommodates [changes to purchase resource in origin-js](https://github.com/OriginProtocol/origin-js/commit/408c0b1f5f0ba77eb2851f326debac302e1286a4#diff-1dd33e048282c9b351f925615a0e2059R25) ☑️
> Update purchase stage name

- src/components/purchase-detail.js
This resolves an issue where the buyer's purchase progress was stuck at "Wait for the seller to withdraw the funds".
> Correct comment and repair buyer's ui

- src/css/app.css
- src/pages/profile/VerifyAirbnb.js
- src/pages/profile/VerifyEmail.js
- src/pages/profile/VerifyFacebook.js
- src/pages/profile/VerifyPhone.js
- src/pages/profile/VerifyTwitter.js
- src/pages/profile/_countryOptions.js
- translations/all-messages.json
- translations/messages/src/pages/profile/_countryOptions.json
This repairs a small issue with the US country code option UI. It also moves a submit handler out of a render function and makes a few opinionated code style changes.
Also, https://github.com/OriginProtocol/origin-dapp/commit/90b5601455b9cb0f439400c3cec9f3b6f97a12e9 repairs the country code select menu.
> Update case style, repair country name, and clean up code

- README.md
Added section for "Browser & Wallet Compatibility" and began to fill in tables.
Stan said this would be a good addition to readme.
> Update ReadMe.md with Browser & Wallet Compatibility section/tables

- README.md
Updated links in the table to the multiple new issues I created.  Thanks Stan for your feedback on this.
> Update README.md with issue links in the table

- .github/PULL_REQUEST_TEMPLATE.md
> Add translation reminder to PR checklist

- src/components/web3-provider.js
Pretty straightforward + some comments 😐
> Remove old [duplicate] function

- README.md
Tested PC with Chrome / Metamask. Operational.
> Tested PC with Chrome / Metamask

- README.md
I've tested the app with Firefox and Metamask, and no problems were founds.
> Tested on Firefox + Metamask, everything is working as intended.

- src/components/listing-detail.js
- src/components/my-purchase-card.js
- src/components/transaction-message.js
- src/components/transaction.js
- src/utils/transactionTypeMap.js
- translations/all-messages.json
- translations/messages/src/components/transaction-message.json
- resolve some minor bugs
- modify listing reservation to use Redux like in other parts of application
- https://github.com/OriginProtocol/origin-js/pull/303 [add confirmation callback to origin-js request listing]
Solves issue: https://github.com/OriginProtocol/origin-dapp/issues/341
> Sparrow dom/calendar prototype fixes

- src/components/my-purchases.js
- translations/all-messages.json
- translations/messages/src/components/my-purchases.json
Adds a missing translation wrapper for a link 😐
> Wrap link for translation

- src/components/messages.js
- src/css/app.css
- webpack.config.js
> Fast-Forward

- src/pages/profile/VerifyAirbnb.js
When doing airBnb attestation and bridge server either isn't available or responds with 4xx or 5xx type of error the attestation would fail without an error message. 
Fixes issue: https://github.com/OriginProtocol/origin-dapp/issues/394
> Airbnb error message fix

- src/services/origin.js
- Reconnect to the server if the connection dies(happens often on live.)
> Messaging reconnect for release

- src/pages/profile/Profile.js
Fixes #208 
- The progress loader didn't start on route changes and only worked on page refreshes.
- My suggested solution: Set the progress in the state everytime the component is mounted.
- Please suggest if a better solution comes to your mind. :pray:
> Fixes #208: Profile progress updates on route changes

- src/actions/Listing.js
- src/components/listings-grid.js
- translations/all-messages.json
- translations/messages/src/components/listings-grid.json
Use the origin-js marketplace contracts found functinoality
Dependant Pull Request: https://github.com/OriginProtocol/origin-js/pull/362
> fetch contract health from origin-js

- src/components/conversation.js
- src/components/dropdowns/messages.js
- src/components/dropdowns/notifications.js
- src/components/messages.js
- src/pages/profile/_Wallet.js
- src/utils/scopedDebounce.js
Just resolving formatting issues, so that `Testing Formatting` stage passes
> fix formatting issues

- src/components/listing-detail.js
- src/components/messaging-provider.js
- src/components/notification.js
This addresses part of https://github.com/OriginProtocol/origin-dapp/issues/445 by repairing the listing id reference and picture shown in the notification component. It also removes some old code and repairs the notifications poll.
> Fix Notifications

- src/actions/Notification.js
- src/components/notification.js
- src/reducers/Notifications.js
This consumes https://github.com/OriginProtocol/origin-js/pull/390 and resolves another task in #445.
> Repair notifications update and move to Redux

- README.md
> fix numbering README.md

- webpack.config.js
- Add some missing options to the Webpack config to allow replacement of env vars in static builds
> Add missing config options for EnvironmentPlugin

- src/actions/Wallet.js
- src/components/dropdowns/user.js
- src/components/wallet.js
- src/pages/profile/Profile.js
- src/reducers/Wallet.js
Show OGN balance in dropdown and profile.
Profile for account 1 (local blockchain):
Dropdown for account 1 (local blockchain):
Profile for account 2 (local blockchain):
Dropdown for account 2 (local blockchain):
> Show OGN balance

- src/components/listing-detail.js
- src/components/purchase-detail.js
This broke due to merge of #458 
Fixed by using listing.unitsRemaining
> Fix a reference to unitsAvailable

- src/components/boost-slider.js
- src/components/listing-create.js
- src/components/listing-detail.js
- src/components/transaction.js
This updates a commission reference to use the updated schema and removes some unused code.
> Offer Commission Repair

- src/components/constants.js
- src/components/listings-grid.js
- src/components/search/search-result.js
Add pagination to search functionality
Dependant Pull Request: 
- https://github.com/OriginProtocol/origin-js/pull/487
Resolves Issue: https://github.com/OriginProtocol/origin-dapp/issues/516
**Important(!)**
This Pull Requests depends on `sparrowDom/core-filters` branch and is thus not set to merge to master but to that dependant branch. It would be nice if `sparrowDom/core-filters` branch would merge to master first.
> add pagination

- src/components/listing-create.js
- src/components/search/search-result.js
- Fixed some formatting issues causing `npm run test` to fail
The CI server is already angry at us :scream:. Output:
`/tmp/build/a94a8fe5/origin-dapp/src/components/listing-create.js
324:7  error  'schemaFetched' is assigned a value but never used  no-unused-vars`
`/tmp/build/a94a8fe5/origin-dapp/src/components/search/search-result.js
53:17  error  Strings must use singlequote  quotes`
> Formatting fixes

- src/components/my-listings.js
- src/components/my-purchases.js
- src/components/my-sales.js
- src/components/purchase-detail.js
- src/components/wallet-card.js
- src/pages/user/User.js
This re-implements the reviews on the public profile page. It also makes some improvements to the my-listings, my-purchases, and my-sales components.
> Public Profile Reviews

- package-lock.json
- src/components/listings-grid.js
- src/components/search/search-result.js
Conforms to the new search pagination api. Fixes a bug where pagination UI was not highlighting the right page,
Dependant PR: 
- https://github.com/OriginProtocol/origin-js/pull/487
Solver Issue: 
- https://github.com/OriginProtocol/origin-dapp/issues/516
> Sparrow dom/pagination fixes

- package-lock.json
- package.json
- webpack.config.js
Replaces `extract-text-webpack-plugin` with `mini-css-extract-plugin`. This should fix the CSS problem.
There is a big warning [here](https://webpack.js.org/plugins/extract-text-webpack-plugin/) that says:
`:warning: Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead.`
:see_no_evil:
> Fix CSS issue

- src/components/app.js
- src/components/boost-slider.js
- src/components/dapp-info.js
Simple page to output info for developers. Will be useful when debugging, especially around releases. For now just outputs ENV vars and origin.js version, but there are surely many more things we could add. 
Screenshot:
> Added page for developer information about DApp.

- src/components/my-sale-card.js
This is what I mean to do the first time before I got in a hurry. 😐
> Sale Card Time Reference

- webpack.config.js
> Add ETH_NETWORK_ID to webpack config

- webpack.config.js
> change default for ETH_NETWORK_ID to null

- package-lock.json
- package.json
> Upgrade to origin 0.8.1

- src/actions/Listing.js
-~[ ] Wrap any new text/strings for translation~
- ~[ ] Map any new environment variables with a default value in the Webpack config~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)~
This fixes issues where empty hidden/featured listings would result in an invalid empty string id. 
**Related issue:** https://github.com/OriginProtocol/origin-dapp/issues/643#event-1875878859
> Fix for hidden/featured listings

- dev.env
- src/components/onboarding-modal/index.js
- src/services/origin.js
- webpack.config.js
Stopgap for speeding up scanning of events for the marketplace contract,
particularly for Rinkeby and Mainnet.
> Add block epoch & pass to origin.js

- package-lock.json
- package.json
Upgrade our dear DApp to origin npm 0.8.2
> Upgrade Dapp to origin npm 0.8.2

- public/index.html
I previously just added it to dev.html and forgot about updating index.html 🤦‍♂️ 
Thanks @micahalcorn
> Add new analytics script to index.html and remove old analytics script

- src/components/my-listings.js
- src/components/wallet-card.js
- translations/all-messages.json
- translations/messages/src/components/wallet-card.json
> Localize Strings

- package-lock.json
- package.json
> Use origin npm v0.8.4

- src/pages/profile/Profile.js
- translations/all-messages.json
- translations/messages/src/pages/profile/Profile.json
- Shows prompt warning if changes have been made and user tries to change the route somehow
- Shows attestation success model after profile is edited
Issue: https://github.com/OriginProtocol/origin-dapp/issues/644
> Profile UX improvements

- src/components/listings-grid.js
- ~[ ] Wrap any new text/strings for translation~
- ~[ ] Map any new environment variables with a default value in the Webpack config~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)~
Fix pagination problem by also removing featured listings from the listings set before slicing it for pagination. 
(have tested the search pagination and it was working as expected @micahalcorn)
> Correct pagination issue

- src/components/listings-grid.js
This repairs the first page of the listings component to only show 12 results with featured listings included. I have not tested with search functionality, but it should not be affected. 🤞
> Featured Pagination Repair

- src/components/listings-grid.js
- src/components/web3-provider.js
Correct the total number of listings to include featured listings
> Another pagination fix

- install.sh
- origin-dapp/package-lock.json
- origin-dapp/package.json
- origin-js/package-lock.json
In my environment `origin-dapp` doesn't get started without the `ajv` and `detect-port` dependancies.  Also removed some unneeded stuff from the install script.
> Fix to get containers started

- origin-dapp/src/components/listing-detail.js
Prior to this change, the featured badge appears on all listing detail pages. This was an error due to poor variable naming.
> Featured Repair

- deployment/dockerfiles/prod/origin-dapp
Fix for path in DApp container build for production.
> Fix prod dapp container build

- origin-dapp/src/css/app.css
A couple quick CSS tweaks to make the DApp look better on mobile devices now that we're featured on Coinbase Wallet and Trust Wallet. Still need lots of other optimizations, but this should help us make a slightly better first impression.
Before:
After:
> Couple quick CSS fixes to make the DApp look better on mobile

- origin-discovery/listener/listener.js
Add some internal documentation to the listener. Convert existing function descriptions to jsdoc format.
> 📙- Add some internal documentation to the listener.

- origin-discovery/package.json
This adds the same local installation script to the discovery server that we use for the dapp. This allows the event listener to work with the local blockchain outside of the box. 😇
> Local Blockchain Listening

- readme.md
Just some quick fixes to the spelling on the readme for the monorepo.
> Quick spelling fixes

- .travis.yml
Using Travis matrix to parallelize running our tests and also to add bridge tests into the mix... Let's see if this works...
> Experiment with Travis matrix

- deployment/kubernetes/charts/origin/templates/eth.ingress.yaml
Fixes something I broke with the eth node ingress and also forces SSL.
> Updates to eth node ingress

- origin-discovery/listener/listener.js
Discord’s embed features lets us put marketplace events in boxes for coolness.
Also includes a little of the item's description text.
> 🎧 Listener - Discord webhook richer now.

- origin-dapp/webpack.config.js
This adds the service worker file to [CopyWebpackPlugin](https://github.com/webpack-contrib/copy-webpack-plugin). I did not test. 😐
> Repair Service Worker File

- origin-discovery/listener/listener.js
- origin-discovery/package-lock.json
- origin-discovery/package.json
- Adds EnvKey support to the listener
- Some whitespace and formatting cleanup
> Make listener support EnvKey

- deployment/kubernetes/charts/origin/templates/notifications.ingress.yaml
Add missing CORS config for notifications server.
> Fix CORS for notifications ingress

- origin-notifications/migrations/20181029174407-create-push-subscription.js
> [Notifications] Don't use camelcase for column names in migration

- deployment/dockerfiles/event-listener
- deployment/dockerfiles/origin-notifications
- deployment/dockerfiles/scripts/start-event-listener.sh
- deployment/dockerfiles/scripts/start-notification-server.sh
- deployment/utils/gcb-discord-notifications/index.js
- Fixes issue where EnvKey variables were not available to migration scripts
- Tweaked announcement lengths for Discord deployment announcements
> Fixes for migration scripts in cloudbuild deployments

- deployment/cloudbuild-deploy.yaml
- deployment/utils/gcb-discord-notifications/index.js
- Shorts commit message of Discord announcement
- Change ordering of `git pull` so `git push` doesn't fail, might have to do `--force`?
> Fixes for Cloud Build setup

- origin-discovery/package-lock.json
- origin-discovery/package.json
- origin-discovery/src/apollo/resolvers.js
- origin-discovery/src/apollo/schema.js
- origin-discovery/src/lib/search.js
- Add a new data field of type JSON to the GraphQL schema for Listing. This field holds the output of the marketplace.getListing method.
- In resolver, fetch listing ids from Elastic and listing data from the DB.
> [Discovery] Add JSON data field to Listing schema

- deployment/dockerfiles/origin-discovery
- deployment/kubernetes/charts/origin/templates/notifications.deployment.yaml
- deployment/utils/gcb-discord-notifications/index.js
Fixes a few issues that have turned up running auto deployments.
> Fixes for autodeployments

- origin-discovery/src/apollo/db.js
- origin-discovery/test/apollo-db.test.js
- origin-discovery/test/apollo-resolvers.test.js
- origin-discovery/test/apollo-schema.test.js
Add file origin-discovery/src/apollo/db.js which was missed in a previous PR.
Add unit tests to catch these type of issues in future.
> [Discovery server] Add missing file and unit tests

- deployment/cloudbuild-deploy.yaml
This should be the branch the deployment is deploying and not master.
> Fix git pull branch

- deployment/cloudbuild-deploy.yaml
This should resolve the issue with pushing deployed tags to the staging branch. Verified it on a fork and looks good!
> Fix git push steps

- origin-contracts/contracts/token/README.md
> README for Origin token contract

- origin-dapp/README.md
Is there a more specific version that should be recommended?
> Node Version

- .travis.yml
- deployment/dockerfiles/origin-notifications
- experimental/origin-admin/package-lock.json
- experimental/origin-graphql-simple-demo/package-lock.json
- experimental/origin-graphql/package-lock.json
- ipfs-proxy/package-lock.json
- origin-contracts/package-lock.json
- origin-dapp/package-lock.json
- origin-discovery/package-lock.json
- origin-faucet/faucet/app.js
- origin-faucet/lib/config.js
- origin-faucet/package-lock.json
- origin-js/package-lock.json
- origin-js/package.json
- origin-messaging/package-lock.json
- origin-notifications/package-lock.json
- ~~[ ] Wrap any new text/strings for translation~~
- ~~[ ] Map any new environment variables with a default value in the Webpack config~~
- ~~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)~~
- Remove ipfs-proxy tests from TravisCI. They keep timing out/failing. I think it might be because they are not cleaning up after themselves properly. Will figure it out in a branch and fix it but will remove it for now so they stop holding things up.
- Fix parseInt on origin-faucet
- Use beta 34 for web3 to try and fix npm issue
> More fixes for deployment and web3 issue

- deployment/cloudbuild-deploy.yaml
- deployment/dockerfiles/origin-discovery
- development/dockerfiles/event-listener
- development/dockerfiles/ipfs-proxy
- development/dockerfiles/origin-dapp
- development/dockerfiles/origin-discovery
- development/dockerfiles/origin-js
- development/dockerfiles/origin-messaging
- development/dockerfiles/origin-notifications
- experimental/origin-admin/package-lock.json
- experimental/origin-graphql/package-lock.json
- origin-contracts/package-lock.json
- origin-dapp/package-lock.json
- origin-dapp/package.json
- origin-discovery/package-lock.json
- origin-js/package-lock.json
- origin-notifications/package-lock.json
- package-lock.json
Add `npm ci` to origin-box and fix some deployment issues.
> Npm ci and deploy

- origin-discovery/src/apollo/listing-metadata.js
- origin-discovery/src/apollo/resolvers.js
- origin-discovery/src/apollo/schema.js
Devops information improvements for discovery server
> Devops information improvements for discovery server

- origin-discovery/src/apollo/db.js
- origin-discovery/src/apollo/resolvers.js
- origin-discovery/src/apollo/schema.js
- origin-js/src/models/offer.js
- origin-js/src/services/discovery-service.js
- fix for hidden and featured listings
- fix faulty apollo query
- `rename` price to `totalPrice`
> Fix for hidden and featured listings

- origin-discovery/src/apollo/app.js
- origin-discovery/src/apollo/resolvers.js
- origin-discovery/src/apollo/schema.js
Enable schema introspection in prod (by default it is disabled when NODE_ENV is set to "production").
> [Discovery] Enable introspection

- origin-discovery/src/apollo/db.js
- origin-discovery/src/lib/search.js
- origin-discovery/src/listener/listener.js
- origin-discovery/src/listener/rules.js
- Refactored listener to make code more readable and also more modular by breaking up all the rules related code in a separate file rule.js.
- Stopped indexing Offers in Elastic and only index in DB since we won't search Offers
- Small hardening change on GraphqQL server side to log data inconsistency errors (vs previous behavior that would cause query to fail)
> [Discovery] Listener code refactor

- docker-compose.yml
- Add a missing environment variable to notifications container for origin-box. Thanks @DanielVF!
> Add missing database URL environment variable for notifications container

- deployment/cloudbuild-deploy.yaml
- Makes the deployment commit a bit more useful by identifying the container
> Add container name to commit message

- deployment/kubernetes/charts/origin/templates/website-redirect.ingress.yaml
- Keeps the path around for the `originprotocol.com` to `www.originprotocol.com` redirect.
> Fix website redirect

- deployment/dockerfiles/event-listener
- deployment/dockerfiles/origin-dapp
- deployment/dockerfiles/origin-notifications
Latest version is supposed to improve reliability...
> Upgrade envkey to latest v1.2.5

- ipfs-proxy/package-lock.json
- origin-messaging/package-lock.json
Remove malicious package from lock files.
> Remove malicious package

- origin-notifications/package-lock.json
- origin-token-transfer/server/package-lock.json
> More malicious package cleanup

- origin-dapp/src/components/listing-create.js
> Little Things

- origin-dapp/package-lock.json
- origin-dapp/package.json
- origin-js/package-lock.json
- origin-js/package.json
- Set web3 to exactly beta.34 for origin-js and origin-dapp
> Pin web3 due to CORS problem

- deployment/cloudbuild-deploy.yaml
- Make TravisCI skip tests on deploy tag commits to stop deployments clogging up our TravisCI time
> Add [ci skip] to deploy tag commit message

- origin-token-transfer/server/package.json
- Fixes package file for T3 server, sorry @cuongdo!
> Fix T3 server package file

- origin-dapp/src/components/modal.js
This should fix the use of the modal component without a blocking backdrop.
> Non-Blocking Modal Repair

- origin-dapp/src/components/listing-create.js
- origin-dapp/src/components/listing-detail.js
- origin-dapp/src/components/my-listings.js
- origin-dapp/src/components/my-purchases.js
- origin-dapp/src/components/my-sales.js
- origin-dapp/src/components/onboarding.js
- origin-dapp/src/components/user-card.js
- origin-dapp/src/components/web3-provider.js
- origin-dapp/src/pages/profile/Profile.js
- origin-dapp/src/services/origin.js
Resolves #979
@micahalcorn Please see if this fixes the problem (or at least doesn't break anything)?
> Rely on our own custom property rather than checking for givenProvider

- origin-js/src/resources/messaging.js
This is another step toward diagnosing https://github.com/OriginProtocol/origin/issues/1052.
> Recipient Validation

- origin-dapp/src/css/app.css
- origin-js/src/resources/messaging.js
Resolves https://github.com/OriginProtocol/origin/issues/1052 for real 😓
> New Message Repair

- docker-compose.yml
Add package.json volume mappings to `docker-compose`
> add package.json volume mappings

- deployment/dockerfiles/event-listener
Remove symlinks creation since these are now handled by scripts/symlink-packages.js
> Fix event-listener deployment

- origin-dapp/src/components/offer-status-event.js
Otherwise withdrawn offers sometimes show as "rejected" on the purchase card 👎
> Voided Offer Status

- .github/PULL_REQUEST_TEMPLATE.md
> Helper Reminder

- DEVELOPMENT.md
Adding information about updating dependencies. I assumed they were reinstalled when the containers started, but they're only installed on the initial container build.
Added the command, but we should probably consider a quicker way to update dependencies in the future.
> Adding dependencies build info

- origin-dapp/package.json
- Explicitly add a react-overlays dependency to avoid issue with newly published version
> Add specific react-overlays dep

- origin-dapp/src/components/web3-provider.js
This passes a `role` query string parameter so that [the appropriate landing page is displayed based on the perspective of the user](https://github.com/OriginProtocol/origin-website/pull/323).
> Enable Dynamic Mobile Landing Page

- deployment/kubernetes/helmfile/origin.yaml
- deployment/kubernetes/values/origin/nginx-ingress/values-dev.yaml
- deployment/kubernetes/values/origin/nginx-ingress/values-prod.yaml
- deployment/kubernetes/values/origin/nginx-ingress/values-staging.yaml
- deployment/kubernetes/values/origin/redis/values-dev.yaml
- deployment/kubernetes/values/origin/redis/values-prod.yaml
- deployment/kubernetes/values/origin/redis/values-staging.yaml
- deployment/kubernetes/values/origin/values-prod.yaml
- Adds Helm chart for Redis to helmfile and enables metrics
- Pin cert-manager version because new version breaks some things
- Remove enable-dynamic-configuration from nginx-ingress because new version deprecates it
> Add redis to helmfile

- origin-mobile/src/Store.js
- origin-mobile/src/actions/ExchangeRates.js
- origin-mobile/src/reducers/ExchangeRates.js
- origin-mobile/src/screens/transaction.js
- origin-mobile/src/utils/price.js
This displays real USD-equivalent values instead of dummy placeholders on the transaction screen.
> Currency Conversion

- origin-linking/src/logic/linker.js
- origin-mobile/src/OriginWallet.js
Add debugging so that we can see why push notifications are failing on stage.
> Debugging for APNS

- origin-dapp/src/components/dapp-info.js
- origin-dapp/webpack.config.js
- Add WALLET_LANDING_URL to Dapp
> Add wallet landing url env var

- origin-js/src/resources/marketplace.js
- origin-linking/src/logic/linker.js
- origin-mobile/ios/OriginCatcher/Info.plist
- origin-mobile/src/OriginWallet.js
- pre-approve notification when a link to safari opened
- force websocket reconnect from background of app
- fix linker meta issue
- fix crash on buyer listing iterator
> Fix notification websocket issues also minor patches

- origin-dapp/src/components/web3-provider.js
- origin-mobile/ios/OriginCatcher/Info.plist
- origin-mobile/src/OriginWallet.js
- origin-mobile/src/screens/messaging.js
- origin-mobile/src/utils/price.js
- fix messaging
- Do not return to a different route, instead use the same route with transactionHash passed in
- do not reconnect to the same provider
> Fix mobile issues

- origin-dapp/src/css/app.css
> Fix positioning of selling modal

- origin-js/src/resources/reflection.js
- origin-linking/src/logic/linker.js
- origin-mobile/ios/OriginCatcher/Info.plist
- origin-mobile/src/OriginWallet.js
- origin-mobile/src/actions/Wallet.js
- origin-mobile/src/screens/settings.js
- Allow changing of private keys
- Support display of ogn cost.
> Added listing with ogn support and added private key changing

- origin-mobile/ios/OriginCatcher/Info.plist
- origin-mobile/src/actions/Wallet.js
- origin-mobile/src/components/transaction-item.js
- origin-mobile/src/components/wallet-modal.js
- origin-mobile/src/screens/home.js
- origin-mobile/src/screens/transaction.js
- origin-mobile/src/utils/ogn.js
- Display OGN on transactions
- fromWei exception coverage.
> Added ogn display to transactions

- origin-mobile/ios/OriginCatcher/Info.plist
- origin-mobile/src/OriginWallet.js
…und)
- retry linking info fetching.
> Retry on link info if it failed

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- deployment/kubernetes/charts/origin/templates/messaging-api.ingress.yaml
- Fix an ingress mistake and use `*` for origin for messaging-api since there are no credentials
> Fix/tweak CORS configuration

- experimental/origin-admin/README.md
> More informative admin README

- DEVELOPMENT.md
Add line in README for where to configure environment variables.
> Natasha/Update development README

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- origin-mobile/src/components/currency.js
- origin-mobile/src/components/transaction-item.js
- origin-mobile/src/components/wallet-modal.js
- origin-mobile/src/reducers/Wallet.js
- origin-mobile/src/screens/home.js
- origin-mobile/src/screens/settings.js
- origin-mobile/src/screens/transaction.js
- origin-mobile/src/utils/currencies.js
Changes included:
- use `outline` for red buttons
- disclaim copying private key
- remove all references to DAI
- generalize funding instruction
> UI Cleanup

- experimental/origin-dapp2/src/hoc/withIdentity.js
- experimental/origin-dapp2/src/pages/nav/NotificationsOld.js
- experimental/origin-dapp2/src/pages/notifications/NotificationRow.js
- experimental/origin-dapp2/src/pages/notifications/Notifications.js
- experimental/origin-dapp2/src/pages/transaction/Transaction.js
- experimental/origin-dapp2/src/pages/transactions/Listings.js
- experimental/origin-dapp2/src/pages/transactions/Purchases.js
- experimental/origin-dapp2/src/queries/UserNotifications.js
- experimental/origin-eventsource/src/index.js
- experimental/origin-graphql/src/contracts.js
- experimental/origin-graphql/src/resolvers/Query.js
- experimental/origin-graphql/src/resolvers/User.js
- experimental/origin-graphql/src/resolvers/_pagination.js
- experimental/origin-ipfs/src/index.js
> GraphQL dapp

- origin-js/package.json
- New version of webpack has broken deps: https://github.com/webpack/webpack/issues/8656
- Fixed by adding `acorn` as explicit dependency
> Add acorn as explicit dependency

- origin-dapp/src/components/dapp-info.js
- origin-dapp/webpack.config.js
This repairs the default Rinkeby DApp URL and activates the wallet linker. 🔗
> Environment Variables

- origin-js/src/services/discovery-service.js
- Fix mistake with GraphQL query
> Fix GraphQL request

- experimental/origin-admin/src/pages/accounts/Accounts.js
- experimental/origin-dapp2/src/pages/create-listing/Review.js
- experimental/origin-dapp2/src/pages/create-listing/mutations/CreateListing.js
- experimental/origin-dapp2/src/pages/create-listing/mutations/UpdateListing.js
- experimental/origin-dapp2/src/pages/identity/mutations/DeployIdentity.js
- experimental/origin-dapp2/src/pages/listing/ListingDetail.js
- experimental/origin-dapp2/src/pages/listing/mutations/Buy.js
- experimental/origin-dapp2/src/pages/listings/ListingCards.js
- experimental/origin-dapp2/src/pages/transaction/mutations/AcceptOffer.js
- experimental/origin-dapp2/src/pages/transaction/mutations/AddData.js
- experimental/origin-dapp2/src/pages/transaction/mutations/DisputeOffer.js
- experimental/origin-dapp2/src/pages/transaction/mutations/FinalizeOffer.js
- experimental/origin-dapp2/src/pages/transaction/mutations/RejectOffer.js
- experimental/origin-dapp2/src/pages/transaction/mutations/WithdrawOffer.js
- experimental/origin-dapp2/src/pages/transactions/Purchases.js
- experimental/origin-dapp2/src/utils/category.js
> GraphQL: Data refresh fixes

- origin-dapp/src/utils/calendarHelpers.js
I think this will fix the issue that we're seeing with fractional listing detail pages on staging. I can't reproduce the bug locally so I'm not totally sure but this is likely the issue.
> Hopefully fixing fractional listing detail bug on staging

- origin-js/src/models/offer.js
This was just looking in the wrong place for slot data in the offer returned by the disco server
> Fix disco path to slots

- experimental/origin-eventsource/src/index.js
- experimental/origin-graphql/src/contracts.js
Also adds affiliate & arbitrator for rinkeby & mainnet
> Event source generates IDs with correct network ID

- origin-dapp/package.json
- origin-dapp/src/components/modal.js
- origin-dapp/src/components/navbar.js
- origin-dapp/src/components/tooltip.js
- https://github.com/react-bootstrap/react-bootstrap/issues/3424 😬 
cc @micah
> React-bootstrap fixes

- Dockerfile
- origin-growth/package.json
- origin-growth/src/apollo/schema.js
> Fix origin-graphql import in origin-growth

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- origin-dapp-creator-server/package.json
- Beta 38 appears to have some issues
- Fix ingress issue
> Pin creator web3 version

- origin-dapp-creator-client/src/components/MetaMaskCallToAction.js
Becuase https://developers.google.com/web/updates/2017/09/autoplay-policy-changes 🔇
> MetaMask CTA Autoplay Fix

- deployment/kubernetes/charts/origin/templates/bridge.ingress.yaml
- origin-dapp/src/components/customize.js
- Don't render child components of the customize component until the remote configuration has been retrieved and loaded. This should hopefully solve that issue we saw @franckc.
> Fix for marketplace filtering race condition

- origin-dapp/src/actions/Activation.js
This checks for the client-side ability to send a message beyond simply relying on the presence of a key in the remote database.
> Messaging Enabled Repair

- experimental/origin-dapp2/src/components/Calendar.js
- experimental/origin-dapp2/src/mutations/MakeOffer.js
- experimental/origin-dapp2/src/pages/create-listing/Availability.js
- experimental/origin-dapp2/src/pages/listing/ListingDetail.js
- experimental/origin-dapp2/src/pages/listing/mutations/Buy.js
- experimental/origin-dapp2/src/pages/transaction/_OfferDetails.js
- experimental/origin-dapp2/src/queries/Fragments.js
- experimental/origin-eventsource/src/index.js
- experimental/origin-graphql/src/mutations/marketplace/makeOffer.js
- experimental/origin-graphql/src/typeDefs/Marketplace.js
> Calendar blocking

- experimental/origin-dapp2/src/components/PageTitle.js
- experimental/origin-dapp2/src/pages/about/DappInfo.js
- experimental/origin-dapp2/src/pages/create-listing/CreateListing.js
- experimental/origin-dapp2/src/pages/listing/Edit.js
- experimental/origin-dapp2/src/pages/listing/ListingDetail.js
- experimental/origin-dapp2/src/pages/listings/Listings.js
- experimental/origin-dapp2/src/pages/messaging/Messages.js
- experimental/origin-dapp2/src/pages/notifications/Notifications.js
- experimental/origin-dapp2/src/pages/transaction/Transaction.js
- experimental/origin-dapp2/src/pages/transactions/Listings.js
- experimental/origin-dapp2/src/pages/transactions/Purchases.js
- experimental/origin-dapp2/src/pages/transactions/Sales.js
- experimental/origin-dapp2/src/pages/user/Profile.js
@nick, does this approach look good for page titles? 
Seems to work in Chrome, Firefox, and Safari. Will be checking IOS mobile next.
> Extremely simple page titles

- origin-mobile/src/App.js
> fix typo on intro screen

- experimental/origin-graphql/test/availability-calculator.js
> Fix graphql tests

- origin-dapp/src/pages/profile/Profile.js
- origin-js/src/index.js
- origin-js/src/resources/reflection.js
- origin-js/src/resources/users.js
- origin-linking/dev.env
- origin-linking/src/logic/linker.js
- origin-mobile/src/OriginWallet.js
- origin-mobile/src/components/transaction-item.js
- origin-mobile/src/screens/transaction.js
In the current version of the app, identity publication is fragile, as reported by @franckc. It also doesn't really have any decent UI support. The changes proposed here are not very pretty, but I think this is an urgent improvement for a piece of the mobile experience that is currently pretty broken. The React Native components are a mess, but they should probably just be properly conceived as a part of the GraphQL rewrite.
Let's get this (or an approved version) merged, built, and submitted to the App Store as soon as it's convenient. 🙏 
cc @cuongdo
> Wallet Identity Support

- origin-mobile/ios/OriginCatcher/Info.plist
> Wallet v 0.2.4

- origin-dapp-creator-client/package.json
> Add ipfs-http-client to origin-dapp-creator-client

- deployment/dockerfiles/event-listener
- deployment/dockerfiles/origin-discovery
Deploys were failing due to missing origin-token dependency.
> Fix event-listener and discovery deployments

- deployment/cloudbuild-deploy.yaml
- deployment/dockerfiles/origin-dapp2
- deployment/kubernetes/charts/origin/templates/_helpers.tpl
- deployment/kubernetes/charts/origin/templates/dapp2.deployment.yaml
- deployment/kubernetes/charts/origin/templates/dapp2.ingress.yaml
- deployment/kubernetes/charts/origin/templates/dapp2.service.yaml
- deployment/kubernetes/values/origin/values-dev.yaml
Container and Kubernetes config to run DApp2 on dev using Kovan
> Dapp2 deployment to dev

- deployment/dockerfiles/origin-discovery
Discovery server now has a dependency on origin-js so we need to build it.
> Fix discovery container

- origin-discovery/src/apollo/injector.js
- added web3url to the config.
> Discovery config with web3

- origin-contracts/migrations/16_whitelist_vA_token.js
- origin-js/src/contractInterface/marketplace/resolver.js
- origin-js/src/contractInterface/marketplace/v00_adapter.js
- origin-js/src/contractInterface/marketplace/vA_adapter.js
- origin-linking/src/logic/hot.js
- This is to fix errors in page
-  token whitelist migration
> Fix errors and token whitelist migration

- origin-contracts/migrations/14_deploy_vA_marketplace_contracts.js
- origin-contracts/migrations/16_whitelist_vA_token.js
> disable whitelist on mainnet since it can't work

- origin-js/src/contractInterface/marketplace/resolver.js
- A quick fix for the listing ID
> Fixed origin-linking on live.

- origin-contracts/releases/0.8.6/migration_17_mainnet.log
- origin-dapp-creator-client/src/index.js
- origin-dapp-creator-client/src/pages/App.js
- origin-dapp-creator-client/src/pages/Configure.js
- origin-dapp-creator-client/src/pages/Create.js
- origin-dapp-creator-server/src/app.js
- origin-dapp-creator-server/src/middleware.js
Fixes various issues on marketplace creator:
- Client/server side validation for invalid subdomains
- Handle switching of web3 account mid-flow and also where someone loads a configuration from localstorage with a different web3 account than the one it was created it (thanks @kayyoo23)
- Added some more logging to server
> Marketplace creator fixes

- deployment/dockerfiles/origin-faucet
> Run DB migration as part of Faucet deployment

- origin-faucet/package-lock.json
- origin-faucet/package.json
- origin-faucet/public/eth.html
- origin-faucet/src/app.js
- origin-faucet/src/eth.js
- Slight refactor to use /eth rather than /eth.html as landing page
- Implement NonceManager to deal with parallel transactions. Open to any better idea re how to handle this...
> NonceManager for ETH faucet

- origin-dapp-creator-client/src/pages/App.js
- Fix the state change to be correct structure, I thought I tested this. 😞
> Fix config update on change of address

- origin-faucet/package-lock.json
- origin-faucet/package.json
> Faucet: add pg to package.json

- experimental/origin-dapp2/src/components/LocaleDropdown.js
- experimental/origin-dapp2/src/pages/_Footer.js
Make the locale dropdown a component so It can be reused on the settings page.
> Componentise locale dropdown

- .gitignore
- origin-mobile/android/sentry.properties
- origin-mobile/ios/sentry.properties
> Add sentry.properties files to .gitignore

- origin-dapp/src/components/web3-provider.js
Maybe this will be the last one for awhile. 🤞
> Messaging Account Repair 

- docker-compose.experimental.yml
> fix docker mapping problem

- origin-mobile/ios/OriginCatcher.xcodeproj/project.pbxproj
- origin-mobile/ios/OriginCatcher/Info.plist
This includes `project.pbxproj` changes that I did not edit manually. It's what ended up in my repo after building master and successfully distributing to the App Store, so I figured it should be committed. 🤷‍♂️ 
cc @tomlinton @mikeshultz
> Wallet Improvement

- experimental/origin-dapp2/webpack.config.js
> Build tags

- deployment/dockerfiles/origin-dapp2
- Add EnvKey integration for ORIGIN_LINKING variable
- Fix locations of ARG commands so they are in the correct place of the multi stage build
> Add EnvKey and rearrange docker args

- experimental/origin-dapp2/src/components/PageTitle.js
- experimental/origin-dapp2/src/pages/transactions/Listings.js
- experimental/origin-dapp2/src/pages/transactions/Purchases.js
- experimental/origin-dapp2/src/pages/transactions/Sales.js
> Dapp2 fixes

- origin-mobile/ios/OriginCatcher.xcodeproj/project.pbxproj
- origin-mobile/ios/OriginCatcher/Info.plist
[I lied](https://github.com/OriginProtocol/origin/pull/1515#issuecomment-468462787). 😇 These changes were also present in the latest build.
> iOS Build Updates

- origin-faucet/src/eth.js
> [Faucet] Bump up gas price to speed up transactions

- origin-dapp/src/components/listings-grid.js
Unexpected linting errors have been seen only on some peoples' computers.  Appears that an empty tag caused it.  This change doesn't appear to have any negative effect on the listing grid.
Linting error seen on my local:
lerna ERR! npm run lint exited 1 in 'origin-dapp'
lerna ERR! npm run lint stdout:
> origin-dapp@0.3.0 lint /home/mike/dev/origin/origin-dapp
> eslint 'src/**/*.js'
/home/mike/dev/origin/origin-dapp/src/components/listings-grid.js
77:17  error  Strings must use singlequote  quotes
88:22  error  Strings must use singlequote  quotes
96:21  error  Strings must use singlequote  quotes
106:17  error  Strings must use singlequote  quotes
✖ 4 problems (4 errors, 0 warnings)
4 errors, 0 warnings potentially fixable with the `--fix` option.
lerna ERR! npm run lint stderr:
Warning: …
> Fixes spooky linting errors

- origin-bridge/package-lock.json
- origin-bridge/package.json
- origin-bridge/src/app.js
- origin-bridge/src/controllers/email.js
- Stores session data in postgresql rather than in memory (which isn't suited for production due to memory leaks according to warnings when starting).
- Fixed an error message
> Add persistent session storage for origin-bridge

- origin-bridge/migrations/20190212002833-create-attestation.js
- origin-bridge/src/models/attestation.js
- Remove updated_at column from bridge migration and set the correct default value for created_at.
> Fix broken bridge migration

- deployment/cloudbuild-deploy.yaml
- Add step to checkout fraud private code to cloudbuild deploy config.
> Deploy private fraud code

- origin-token-transfer-client/.eslintrc.js
- origin-token-transfer-client/package.json
- origin-token-transfer-client/src/App.js
- origin-token-transfer-client/src/actions/index.js
- origin-token-transfer-client/src/components/Events.js
- origin-token-transfer-client/src/components/GrantRow.js
- origin-token-transfer-client/src/components/Grants.js
- origin-token-transfer-client/src/components/GrantsTable.js
- origin-token-transfer-client/src/components/Login.js
- origin-token-transfer-client/src/components/NavBar.js
- origin-token-transfer-client/src/components/TransferDialog.js
- origin-token-transfer-client/src/reducers/index.js
- origin-token-transfer-server/package.json
- origin-token-transfer-server/src/app.js
- origin-token-transfer-server/src/lib/transfer.js
- origin-token-transfer-server/src/lib/vesting.js
- origin-token-transfer-server/src/models/event.js
- origin-token-transfer-server/src/models/grant.js
- origin-token-transfer-server/src/models/index.js
- origin-token-transfer-server/src/passport.js
> Implementing linting and run prettier on t3 packages

- deployment/kubernetes/charts/ethereum-network/templates/geth-miner.statefulset.yaml
- deployment/kubernetes/charts/ethereum-network/values.yaml
- Update geth
- Fix an issue with second miner node and disk access
> Update Helm chart for Origin testnet

- origin-bridge/src/controllers/redirects.js
> Fix res.sendFile calls

- origin-growth/src/apollo/app.js
- origin-growth/src/apollo/resolvers.js
- disable growth location functionality
- log received headers on growth server
> disable location functionality. Log request headers

- origin-dapp/src/components/Balances.js
- origin-dapp/src/components/Reviews.js
- origin-dapp/src/components/WaitForTransaction.js
- origin-dapp/src/pages/create-listing/Boost.js
- origin-dapp/src/pages/create-listing/Review.js
- origin-dapp/src/pages/identity/EmailAttestation.js
- origin-dapp/src/pages/identity/PhoneAttestation.js
- origin-dapp/src/pages/listing/_BuyFractional.js
- origin-dapp/src/pages/listing/mutations/Buy.js
- origin-dapp/src/pages/messaging/Message.js
- origin-dapp/src/pages/messaging/Messages.js
- origin-dapp/src/pages/messaging/Room.js
- origin-dapp/src/pages/nav/Messages.js
- origin-dapp/src/pages/onboard/MetaMask.js
- origin-dapp/src/pages/user/Profile.js
- origin-dapp/src/pages/user/User.js
- origin-dapp/src/pages/user/_EditModal.js
- origin-graphql/src/contracts.js
- origin-graphql/src/metaMaskSync.js
- origin-graphql/src/mutations/marketplace/createListing.js
- origin-graphql/src/resolvers/Web3.js
> Various dapp2 fixes

- deployment/kubernetes/charts/origin/templates/growth.ingress.yaml
add authentication header for growth engine
> add authentication header

- origin-dapp/public/template.html
- Add a header to prevent caching of index.html
> Expire content header

- origin-dapp/src/pages/create-listing/mutations/CreateListing.js
- origin-dapp/src/pages/create-listing/mutations/UpdateListing.js
Added verbose instructions on what comes next, to match dapp1
On spreadsheet as "Create listing complete modal text"
> Updated success message for listing create/update to match dapp1 

- origin-dapp/src/components/EventTick.js
- origin-dapp/src/components/TransactionStages.js
- origin-dapp/src/pages/listing/Listing.js
- origin-dapp/src/pages/listing/mutations/Buy.js
- origin-dapp/src/pages/transaction/_Progress.js
- origin-dapp/src/pages/transaction/_WaitForFinalize.js
- origin-dapp/src/pages/transactions/Purchases.js
- origin-dapp/src/pages/transactions/Sales.js
- origin-dapp/src/pages/transactions/_OfferStatus.js
- origin-dapp/src/queries/Fragments.js
> Stages on My Listings / Sales

- origin-dapp/src/utils/marketplaceCreator.js
- Fix favicon element selector for new dapp2 index.html
> Update favicon link rel for dapp2

- DEVELOPMENT.md
Update documentation with suggested workflow for Docker
> update Docker documentation

- origin-growth/src/apollo/app.js
- origin-growth/src/apollo/resolvers.js
Improve logging on authentication part of growth engine
> improve logging errors in growth engine

- .travis.yml
- Travis/something is broken so disable these for now.
> Disable integration tests

- origin-growth/src/apollo/resolvers.js
- origin-growth/src/resources/email.js
> Populate growth_invite from the /invite endpoint

- origin-dapp/index.js
- origin-graphql/src/contracts.js
> Truffle config

- origin-discovery/src/listener/handler_identity.js
- origin-faucet/src/eth.js
> [Faucet] Increase gas amount in case user uses a managed wallet

- origin-dapp/src/components/Reviews.js
😬 My First DApp2 Contribution ™️ 
This increases the number of reviews that are shown prior to expansion and causes more of them to appear with pagination as requested by @AustinVirts. It also changes the heading to help communicate the context of the subject of the reviews collection and removes the number count to avoid translation complications.
Resolves the latter half of https://github.com/OriginProtocol/origin/issues/1389 ✅
> Reviews Pagination Improvements

- origin-dapp/src/hoc/withCanTransact.js
Fix linking popup when wallet linked
> Fix linking popup when wallet linked

- origin-dapp/src/mutations/GrowthEnroll.js
make invite code non mandatory
> make invite code non mandatory

- origin-growth/src/models/growth_campaign.js
- origin-growth/src/models/growth_event.js
- origin-growth/src/models/growth_invite.js
- origin-growth/src/models/growth_reward.js
- origin-growth/src/resources/email.js
- Fixed invite model by adding auto-increment (invite recording was failing with error: null value in column id violates not-null constraint)
- Fixed fetching invite code (was missing an await)
- Fixed other models that had same issue.
- Added check to avoid inserting duplicate entries in growth_invite.
> [Growth] Fix models and invite

- origin-graphql/src/contracts.js
add growth configuration for the dev environment
> set a growth engine for dev deployment

- origin-messaging-client/src/Messaging.js
Switch to camelCase. Warnings were killing me 😅
> camelCase messaging

- deployment/dockerfiles/origin-messaging
- origin-messaging/package.json
- Add sequelize-cli to prod dependencies
- Add EnvKey to container for migration
> Messaging dep/container fix

- origin-dapp/src/pages/growth/Invite.js
- origin-dapp/webpack.config.js
- origin-graphql/src/contracts.js
- origin-growth/src/resources/email.js
- origin-growth/src/templates/emailInvite.html
- origin-growth/src/templates/emailInvite.txt
- origin-growth/test/invite.test.js
Implement html and text templating for emails.
Content and styling is not finalized. Waiting on Aure/Matt.
> [Growth] Templates implementation

- deployment/utils/gcb-discord-notifications/index.js
- origin-docs/cloudbuild.yaml
- origin-docs/jekyll-builder/Dockerfile
- Cloudbuild config for docs build/push
This closes #1228
> Docs build automation

- origin-graphql/src/typeDefs/Growth.js
- origin-growth/src/resources/invite.js
Found couple bugs while testing referral on staging...
> [Growth] Fixes to referral code

- origin-growth/src/apollo/resolvers.js
- origin-growth/src/resources/email.js
- origin-growth/src/templates/emailInvite.html
- origin-growth/src/templates/emailInvite.txt
- origin-growth/src/templates/emailReminder.html
- origin-growth/src/templates/emailReminder.txt
- origin-growth/test/invite.test.js
Implemented /inviteRemind mutation.
> [Growth] Reminder email implementation

- origin-dapp/src/pages/growth/Welcome.js
- origin-dapp/src/queries/InviteInfo.js
- origin-graphql/src/typeDefs/Growth.js
Support personalised invite page and update some copyrights texts
> Personalized invite page

- origin-dapp/src/pages/growth/Campaigns.js
- origin-dapp/src/pages/growth/WithEnrolmentModal.js
- origin-dapp/src/pages/identity/EmailAttestation.js
- origin-dapp/src/pages/identity/PhoneAttestation.js
- origin-growth/src/apollo/resolvers.js
- changes text on email and phone attestations
- adds location check to enroll functionality
- update terms UI and text
- move campaign cap to 1000 from 100
> Growth updates

- origin-faucet/public/eth.html
- origin-faucet/public/index.html
See if this fixes the scale and zoom. 🌈
> Faucet Viewport

- origin-dapp/src/components/GrowthCampaignBox.js
- origin-dapp/src/components/ProgressBar.js
- origin-dapp/src/pages/growth/Campaigns.js
Make growth campaign box that shows the status of growth campaign in the profile page
> Sparrow dom/profile growth campaign box

- origin-dapp/scripts/convertTranslations.js
- origin-dapp/src/components/QueryError.js
- origin-dapp/src/components/TransactionError.js
- origin-dapp/src/components/WaitForTransaction.js
- origin-dapp/src/hoc/withWallet.js
- origin-dapp/src/index.js
- origin-dapp/src/pages/growth/Invite.js
- origin-dapp/src/pages/growth/mutations/Enroll.js
- origin-dapp/src/pages/identity/AirbnbAttestation.js
- origin-dapp/src/pages/identity/EmailAttestation.js
- origin-dapp/src/pages/identity/FacebookAttestation.js
- origin-dapp/src/pages/identity/PhoneAttestation.js
- origin-dapp/src/pages/identity/TwitterAttestation.js
- Makes it easier to spot errors and warnings in console
- Makes it easier to spot left-behind debugging console.log's in logs that might otherwise get committed.
> console.log()-->console.error(),console.warn() where appropriate

- origin-dapp/src/components/Analytics.js
- origin-dapp/src/components/FormattedDescription.js
- origin-dapp/src/hoc/withTokenBalance.js
- origin-dapp/src/pages/create-listing/listing-types/AnnouncementListing/Review.js
- origin-dapp/src/pages/create-listing/listing-types/FractionalListing/Review.js
- origin-dapp/src/pages/create-listing/listing-types/UnitListing/Review.js
- origin-dapp/src/pages/listings/_Search.js
Fixes for issues on prod:
- Create listing gets stuck
- Review page description formatting.
> Fix create listing getting stuck. Review page description formatting.

- origin-dapp/src/pages/growth/Invite.js
> [Growth] Fix sharing URI encoding

- deployment/kubernetes/values/origin/values-dev.yaml
- origin-growth/src/util/locationInfo.js
> [Growth] Update list of forbidden countries

- dapps/marketplace/src/pages/create-listing/ChooseListingType.js
Temporary hack to prevent hourly fractional being used in production but can be tested and used by executing in console:
localStorage.setItem('enableAllFractional', 'true');
remove with:
localStorage.removeItem('enableAllFractional');
> Use localstorage to enable/disable fractional listings.

- devops/kubernetes/charts/origin/values.yaml
- devops/kubernetes/values/origin/values-dev.yaml
- devops/kubernetes/values/origin/values-prod.yaml
- devops/kubernetes/values/origin/values-staging.yaml
- Pin deployed IPFS version due to issue with IPNS, e.g. https://ipfs.originprotocol.com/ipns/config.raretoken.art returns `ipfs resolve -r /ipns/config.raretoken.art: not a valid proquint string`. I validated this version of dev and it works correctly.
- Also cleaned up values files and added defaults for all the new packages.
> Pin deployed ipfs version

- devops/dockerfiles/origin-dapp-creator-client
> Fix dapp-creator-client container

- dapps/marketplace/src/pages/listing/ListingDetail.js
>  Allow repeat purchases of multi-unit listing 

- dapps/marketplace/src/pages/transaction/_Progress.js
> Show only stages for transaction public view

- dapps/marketplace/src/pages/growth/Welcome.js
- dapps/marketplace/src/pages/growth/mutations/Enroll.js
- devops/kubernetes/values/origin/values-dev.yaml
- infra/growth/src/apollo/adapter.js
- infra/growth/src/apollo/resolvers.js
- infra/growth/src/resources/rules.js
- packages/graphql/src/typeDefs/Growth.js
- Fix bug where past events where included when computing a rule status
- Fix bug where invalid invite code would cause welcome page to error out
- Fix bug where invite code would sometime show as undefined
> [Growth] Misc fixes

- dapps/marketplace/src/pages/growth/Action.js
- dapps/marketplace/src/pages/growth/Campaigns.js
- dapps/marketplace/src/pages/growth/Invite.js
- dapps/marketplace/src/pages/growth/Welcome.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- on Invite Friends action show Earned and pending invites in case those are bigger than 0. If they are both 0 show the amount of reward 1 invite brings
- clear invite emails field on successful invite
- making labels in modal checkboxes clickable
- automatically refreshing invite information after you trigger email invites
- fixing welcome page title
- correcting the position of astronaut on an non personalised welcome page
**Still a work in progress**
> Knocking out the growth engine P1s

- mobile/.gitignore
- mobile/android/build.gradle
I'm not sure if this dependency upgrade is necessary, but it resulted from my efforts to get Android to build on my machine. I also needed to ignore the Firebase config file for some reason.
> Android Tweaks

- dapps/marketplace/webpack.config.js
- Fix webpack template generation. Should close #1789.
> Add metamask enabled to webpack config

- dapps/marketplace/src/pages/create-listing/mutations/_listingData.js
> Announcement Listing

- dapps/marketplace/src/pages/identity/EmailAttestation.js
- packages/graphql/src/mutations/attestations/generateAirbnbCode.js
- packages/graphql/src/mutations/attestations/generateEmailCode.js
> Validate email address during Attestation

- dapps/marketplace/src/pages/identity/EmailAttestation.js
- dapps/marketplace/src/pages/identity/PhoneAttestation.js
Fixes #1834 
Allows the user to type only numbers and restricting it to 6 characters at max.
> Verification Code Validation

- dapps/marketplace/src/components/ImageCropper.js
- dapps/marketplace/src/components/ImagePicker.js
- dapps/marketplace/src/utils/loadImage.js
Uses a white (instead of black) background for images uploaded with a transparent background. 
Closes #1344
> Image transparency white background

- infra/growth/src/templates/emailInvite.html
- infra/growth/src/templates/emailReminder.html
Remove leftover templating tags that were copied over by mistake from our other repo.
> Remove unused templating tags

- dapps/marketplace/src/pages/_Footer.js
> Fix spacing around links in footer

- dapps/marketplace/src/pages/_Nav.js
- dapps/marketplace/src/pages/_RewardsBanner.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/nav/Sell.js
- fixes annoying console error
- aligns buy and sell buttons to the center
- removes `add listing` nav button in md size.
> Minor UX fixes

- dapps/marketplace/src/components/Attestations.js
- dapps/marketplace/src/pages/nav/Profile.js
- dapps/marketplace/src/pages/settings/Settings.js
> Settings link in profile dropdown

- dapps/marketplace/src/pages/_Nav.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- make "Earn Tokens" link look like other links
- remove some of the un-needed props on enrolment buttons
> Minor UI fixes

- docs/guides/getting_started/local-development.md
Thanks to @nick  and @tomlinton for the fix!
> Add python2.7 to docs, ensure npm install works.

- infra/growth/src/apollo/adapter.js
- infra/growth/src/apollo/app.js
- infra/growth/src/util/money.js
Couple changes:
- Fixed a bug where the toString method rather than the toFixed method was called on BigNumber for formatting reward total amounts.
- Check for admin secret before auth token.
> [Growth] Fix bug with reward amount formatting

- infra/discovery/src/listener/queries/Fragments.js
- infra/discovery/src/listener/webhooks.js
> Fix webhooks

- packages/ipfs/src/index.js
> Simplify IPFS optimization

- infra/growth/migrations/20190407031520-add-ip-participant.js
- infra/growth/migrations/20190407031521-add-country-participant.js
- infra/growth/src/apollo/resolvers.js
- infra/growth/src/models/growth_participant.js
- infra/growth/src/resources/authentication.js
For easier analytics and fraud detection.
> Store IP and country in growth_participant

- infra/discovery/src/listener/listener.js
This should fix the listener loop and stop it erroring/missing blocks.
> Fix listener loop

- devops/kubernetes/charts/origin/templates/ipfs.ingress.yaml
We are hitting this limit now with the front page load.
> Bump IPFS ingress RPS limit

- dapps/marketplace/src/pages/onboard/MetaMask.js
- packages/eventsource/src/index.js
- packages/graphql/src/metaMaskSync.js
- packages/graphql/src/resolvers/Web3.js
- packages/graphql/src/resolvers/marketplace/_featuredAndHidden.js
A few more optimizations and simplifications for reducing number of ethereum node requests
> More request optimizations

- dapps/marketplace/package.json
- dapps/marketplace/src/pages/user/Profile.js
- packages/graphql/src/contracts.js
- packages/graphql/src/mutations/attestations/verifyAirbnbCode.js
- packages/graphql/src/mutations/attestations/verifyEmailCode.js
- packages/graphql/src/mutations/attestations/verifyFacebook.js
- packages/graphql/src/mutations/attestations/verifyPhoneCode.js
- packages/graphql/src/mutations/attestations/verifyTwitter.js
- packages/graphql/src/resolvers/Query.js
Adds attestation schema validation:
- when fetching an attestation back from the bridge server
- when loading saved attestations from session storage
> Validate attestations when loading from sessionStorage

- packages/graphql/src/typeDefs/Common.js
- packages/graphql/src/typeDefs/Growth.js
> [Growth] Use a custom GrowthPrice rather than default Price

- docker-compose.yml
- infra/discovery/src/listener/listener.js
Fix for a listener to work in docker
> minor fixes

- dapps/marketplace/src/pages/listing/ListingDetail.js
- dapps/marketplace/src/pages/listing/_ListingWithdrawn.js
Buyers should not be able to purchase a withdrawn listing
Closes #1656
> Buyers should not be able to purchase a withdrawn listing

- dapps/marketplace/src/pages/listing/mutations/Buy.js
Show modal if error on purchase
> Show modal if error on purchase

- dapps/marketplace/src/utils/marketplaceCreator.js
> Fix setting of title for created marketplaces

- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/utils/profileTools.js
Fixes 2 things in Profile Wizard: 
- fixes bug where it would show there are changes to be published even when there were not
- fixes bug where Rewards enrol modal would not be centered
> Sparrow dom/profile wizard fix

- DEVELOPMENT.md
Including grammar, punctuation, and spelling
> Edits for clarity and consistency

- dapps/marketplace/src/pages/growth/mutations/Enroll.js
Un-translate signature message
> Un-translate signature message

- dapps/marketplace/src/pages/growth/mutations/Enroll.js
> add comment

- infra/discovery/src/listener/webhooks.js
Didn't test. 
@franckc would you mind checking if this looks right?
> Pass additional information when subscribing users to our mailing list

- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/transaction/_Progress.js
- dapps/marketplace/src/pages/transactions/Listings.js
This repairs some copy that we noticed during our latest user research sessions.
> Copy Repairs

- dapps/marketplace/src/pages/listing/mutations/Buy.js
> Set DAI allowance request to offer value

- packages/graphql/fixtures/_demoListings.js
Important work 🏆 
Resolves https://github.com/OriginProtocol/origin/issues/1113#issuecomment-452162125
But srsly, can #1113 be closed?
> Demo Listings Repair

- dapps/marketplace/src/components/Balances.js
- dapps/marketplace/src/components/TokenBalance.js
> DAI decimal places in wallet dropdown

- infra/bridge/migrations/20190408083420-add-google-attestion-type.js
> Fix bridge attestation enum

- dapps/marketplace/src/pages/growth/mutations/Enroll.js
- packages/services/index.js
> Fix enrol of Origin Rewards

- dapps/marketplace/src/pages/growth/Campaigns.js
remove info icon in campaigns home
> remove info icon in campaigns home

- dapps/marketplace/src/components/Attestations.js
- dapps/marketplace/src/pages/user/Profile.js
- dapps/marketplace/src/pages/user/User.js
This arranges the attestation elements based on the order in which they appear in the wizard (and that we prefer). There was some slight confusion with this during our recent user research sessions.
> Attestation Arrangement

- docker-compose.yml
Fixes services starting in docker
> fix services running in docker

- dapps/marketplace/src/index.js
- packages/graphql/src/contracts.js
Only enable mobile bridge when in mobile dapp
> Small tweak for mobile bridge

- Dockerfile
- devops/dockerfiles/event-listener
- devops/dockerfiles/origin-admin
- devops/dockerfiles/origin-cron
- devops/dockerfiles/origin-dapp
- devops/dockerfiles/origin-dapp-creator-client
- devops/dockerfiles/origin-discovery
- devops/dockerfiles/origin-growth
- docker-compose.yml
Per title, knew I forgot something!
> Replace linker-client with mobile-bridge in deployments

- packages/graphql/src/configs/origin.js
Some of these disappeared in the config rejig.
> Add bridge and messaging back to dev config

- devops/dockerfiles/origin-notifications
> copy identity package as part of notifications

- devops/dockerfiles/origin-notifications
- infra/notifications/src/logger.js
Needed a bit more than I thought @wanderingstan. This should make it go!
> Fix notifications container

- mobile/ios/OriginCatcher/Info.plist
- mobile/package-lock.json
- mobile/package.json
- mobile/src/OriginWallet.js
- mobile/src/components/account-modal.js
- mobile/src/components/onboarding.js
- mobile/src/screens/fork.js
- mobile/src/screens/marketplace.js
- Change package for SafeAreaView
- Use the forceInset option on the marketplace screen to avoid it ever overlapping
- Ran prettier
> Fix SafeAreaView on marketplace screen

- infra/faucet/public/static/css/styles.css
Decrease padding should make it render OK on small devices.
> Reduce top padding on mobile for faucet

- packages/graphql/src/mutations/attestations/verifyPhoneCode.js
> Fix for "Silent Phone Verification Code Failure"

- dapps/marketplace/src/pages/listing/_BuyFractional.js
- dapps/marketplace/src/pages/listing/mutations/Buy.js
- dapps/marketplace/src/pages/transaction/_OfferDetails.js
- packages/graphql/src/utils/AvailabilityCalculator.js
The following changes have been made to FractionalListing type
- The price charged is now based on per-night basis. If the user books a listing for Thursday-Friday, he will be charged for Thursday night. The minimum number of nights a user can book is 1.
- Previously If an user checks out on a day, other users cannot book that night. That has been changed.
> Update FractionalListing price calculation and booking availability

- packages/graphql/fixtures/populate.js
- packages/graphql/src/configs/localhost.js
- packages/services/index.js
Add epoch to populate script. Fix write to truffle build files.
> Small fixes for populate script

- infra/notifications/src/app.js
> don't rate limit `/events`

- dapps/marketplace/src/components/QueryError.js
- Fixes react-native invariant error about an object as a react child
- Displays errors different inside the WebView because of no access to console
> Fix query error and support mobile

- .travis.yml
> Add puppeteer tests to travis

- packages/event-cache/src/EventCache.js
Adds retries for `getPastEvents` call and a bit of error handling for debugging.  Might help detecting and dealing any JSON-RPC call failures to Infura.
> Adds a bit of Bottleneck error handling and retries for getPastEvents JSON-RPC call

- dapps/marketplace/src/components/QueryError.js
- mobile/src/screens/marketplace.js
- packages/graphql/src/contracts.js
- packages/mobile-bridge/src/index.js
- packages/mobile-bridge/src/webviewbridge.js
This should improve stability by relying on a window object that exists for WebViews rather than injecting our own. Closes #2111.
> Better WebView detection

- dapps/marketplace/src/pages/listing/mutations/Buy.js
- packages/graphql/src/utils/AvailabilityCalculator.js
> Update fractional listing price calculation

- packages/event-cache/src/EventCache.js
Adds some debugging info to try and suss out issues described in #1972.  This adds an extra JSON-RPC request and probably shouldn't be a permanent change.
> adds some debugging info to logs for potential event-cache lag issues

- packages/graphql/src/utils/currencies.js
> Peg DAI to $1

- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/nav/Mobile.js
Close hamburger menu when clicking Earn Tokens
Closes #2171
> Close hamburger menu when clicking Earn Tokens

- packages/graphql/src/resolvers/marketplace/_featuredAndHidden.js
Feature list cache buster
Closes #1674
> Feature list cache buster

- devops/kubernetes/charts/origin/templates/notifications.deployment.yaml
Mounted them in the wrong container 😬
> Fix notification container volume mounts

- dapps/marketplace/src/components/AutoMutate.js
- dapps/marketplace/src/pages/identity/FacebookAttestation.js
- dapps/marketplace/src/pages/identity/GoogleAttestation.js
- dapps/marketplace/src/pages/identity/TwitterAttestation.js
- dapps/marketplace/test/index.js
Automatically complete mobile attestation after redirect
> Automatically complete mobile attestation after redirect

- infra/discovery/src/listener/listener.js
> [Listener] Simplify filtering code

- mobile/.gitignore
- mobile/android/build.gradle
- mobile/ios/OriginCatcher/Info.plist
- mobile/package-lock.json
- mobile/package.json
- mobile/src/OriginWallet.js
- mobile/src/Store.js
- mobile/src/reducers/Wallet.js
- mobile/src/screens/marketplace.js
- mobile/src/utils/contractDecoder.js
This includes a bunch of fixes for little things for the latest releases.
- Only display notification nag modal for listing transaction events not signing or identity
- Validation of accounts on startup to make sure the saved data can't get into a weird state
> Mobile version bumps and misc fixes

- docker-compose.yml
Docker services container errors out for me missing `packages/services/data/localhost.key` files since the `/app/packages/services/data` folder is excluded from mapping
> add file mappings

- dapps/marketplace/src/pages/create-listing/listing-types/FractionalHourlyListing/Review.js
- dapps/marketplace/src/pages/create-listing/listing-types/FractionalListing/Review.js
- dapps/marketplace/src/pages/create-listing/listing-types/GiftCardListing/Review.js
- dapps/marketplace/src/pages/create-listing/listing-types/UnitListing/Review.js
> Wrap withTokenBalance hoc w/withWallet hoc

- dapps/marketplace/src/pages/identity/PhoneAttestation.js
> Make attestation modal overflow

- dapps/marketplace/src/components/WithPrices.js
- dapps/marketplace/src/hoc/withCurrencyBalances.js
- dapps/marketplace/src/pages/listing/_PaymentOptions.js
> Update withCurrencyBalances hoc to render after loading has completed

- packages/graphql/src/mutations/_gasCost.js
Increase finalization gas cost
Closes #2220
> Increase finalization gas cost

- dapps/marketplace/src/pages/transaction/_Progress.js
- dapps/marketplace/src/pages/transaction/mutations/FinalizeOffer.js
Seller can finalize after window has passed.
Closes #2219
> Seller can finalize after window has passed

- dapps/marketplace/src/pages/growth/Welcome.js
fixes an error where invite code not present
> fix invite code checking

- mobile/android/app/build.gradle
- mobile/android/app/src/main/java/com/origincatcher/MainApplication.java
- mobile/android/settings.gradle
- mobile/ios/OriginCatcher.xcodeproj/project.pbxproj
- mobile/package-lock.json
- mobile/package.json
- mobile/src/screens/marketplace.js
- mobile/src/utils/index.js
No idea what this one does 🙈 
Reconstructs a user agent that looks like the standard browser for the device. Closes #2227.
> Simulate standard browser user agent in webview

- dapps/marketplace/src/mutations/GrowthEnroll.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/growth/mutations/Enroll.js
- infra/growth/src/apollo/resolvers.js
- infra/growth/src/resources/authentication.js
- infra/growth/src/util/bannedUserError.js
- packages/graphql/src/typeDefs/Growth.js
Handle the case so that un-enrolled account gets directed to blocked page in case that account is blocked.
> handle the case where blocked account tries to enroll

- packages/graphql/src/mutations/token/updateTokenAllowance.js
Estimate gas for token allowance step for Dai swap.
> Don't use max token allowance gas amount

- dapps/marketplace/src/pages/listing/ListingDetail.js
Bug I accidentally introduced in ef077b2f624df0bad2269d550e89992c90cfa00a
Fixes buyer and seller detection on Listing detail page.
Closes #2240
> Sellers should not be able to purchase their own listing

- dapps/marketplace/test/index.js
- packages/graphql/src/links/schema.js
Fix annoying bug that sometimes causes integration test to fail
> Fix profile integration test

- infra/growth/src/resources/email.js
- infra/growth/src/scripts/createProdCampaign.js
- infra/growth/src/scripts/distributeRewards.js
- infra/growth/src/scripts/sendPayoutEmails.js
- infra/growth/src/templates/emailPayout.html
- infra/growth/src/util/token.js
- Small changes to the script for sending payout email.
- Small misc other cleanups.
> [Growth] Fixes to payout email script

- dapps/marketplace/src/components/ImageCropperModal.js
- dapps/marketplace/src/components/ImagePicker.js
> Show crop outline when cropping listing images

- dapps/marketplace/src/pages/create-listing/listing-types/GiftCardListing/Details.js
- dapps/marketplace/src/pages/create-listing/listing-types/GiftCardListing/Review.js
- dapps/marketplace/src/pages/identity/_CountryDropdown.js
- dapps/marketplace/src/pages/listing/ListingDetail.js
Flag image names are lowercase, our codes are uppercase. Fix with `.toLowerCase()`
> giftcard flagfix

- infra/growth/migrations/20190515212953-add-growth-payout-type.js
- infra/growth/migrations/20190515213012-add-growth-payout-data.js
- infra/growth/src/enums.js
- infra/growth/src/models/growth_payout.js
- infra/growth/src/scripts/adjustPayout.js
- infra/growth/src/scripts/distributeRewards.js
- infra/growth/src/util/tokenDistributor.js
Script for making manual payout adjustments, for example when after reviewing an account we decide to lift the banning and give credit to a user.
- Takes as input a file with eth address, amount and reason for adjustment.
- Creates payout rows that have 2 new columns populated: type=Adjustment, data=Reason for adjustment
> [Growth] Adjustment script

- dapps/marketplace/src/components/WithPrices.js
Hopefully fixes rounding errors we've been seeing and occasional integration test failures
> Fix JS rounding error when calculating value

- devops/kubernetes/charts/origin/templates/relayer.deployment.yaml
- devops/kubernetes/charts/origin/templates/relayer.secret.yaml
> Minor fixes to relayer config

- devops/kubernetes/charts/origin/templates/bridge.ingress.yaml
- devops/kubernetes/charts/origin/templates/ipfs.ingress.yaml
- devops/kubernetes/charts/origin/templates/notifications.ingress.yaml
Tweak RPS values to (hopefully) help out meetups.
> Change RPS values

- dapps/admin/src/pages/_NodeInfo.js
- infra/relayer/src/app.js
- infra/relayer/src/relayer.js
- packages/contracts/build/contracts_origin.json
- packages/graphql/src/configs/_localStorageHas.js
- packages/graphql/src/configs/localhost.js
- packages/graphql/src/configs/mainnet.js
- packages/graphql/src/configs/origin.js
- packages/graphql/src/configs/rinkeby.js
- packages/graphql/src/links/remoteSchema.js
- yarn.lock
> MetaTX wip

- cloudbuild.yaml
- infra/relayer/src/risk/dev/engine.js
Checkout private repo with fraud code when deploying origin-relayer container.
> Checkout private fraud code if deploying origin-relayer

- infra/discovery/src/listener/listener.js
Force listener process to restart when catching an exception in its main loop.
> [Listener] Exit process when exception caught in main loop

- Dockerfile
- docker-compose.yml
add missing folders mappings to docker file and docker-compose
> add the missing mappings for docker to run

- infra/discovery/src/listener/listener.js
- infra/discovery/src/listener/utils.js
- packages/event-cache/src/EventCache.js
Some logging to hopefully help with #2338.
> adds some logging instrumentation for listener debugging. 

- dapps/marketplace/package.json
- dapps/marketplace/src/hoc/withCurrencyBalances.js
- dapps/marketplace/test/index.js
> Fix for marketplace tests

- dapps/marketplace/src/pages/create-listing/listing-types/GiftCardListing/Review.js
> Fix huge flag issue.

- dapps/marketplace/src/index.js
- dapps/marketplace/src/pages/_MobileModal.js
- dapps/marketplace/src/pages/listings/Listings.js
- dapps/marketplace/src/pages/transactions/Listings.js
- dapps/marketplace/src/pages/transactions/Purchases.js
- dapps/marketplace/src/pages/transactions/Sales.js
- dapps/marketplace/test/index.js
- yarn.lock
Expand puppeteer tests to editing listings
> Expand puppeteer tests to editing listings

- packages/eventsource/src/index.js
Adds the ability to disable eventsource caching with the `DISABLE_CACHE` env var. 
Ref #2346
CC @franckc
> Option to disable eventsource caching

- packages/event-cache/test/index.js
Quick & dirty PR that adds a simple test with an `undefined` value for a `getEvents()` argument in EC
> Adds a test to EventCache

- .circleci/config.yml
- packages/graphql/src/resolvers/Listing.js
A cache fix was causing issues with puppeteer so disabled it for now
> Fix puppeteer tests

- .circleci/config.yml
> CircleCI tweaks

- package.json
- scripts/package-versions.js
Finds all package.json files and compares versions. Useful for ensuring npm versions are kept in sync:
```
@babel/core
./infra/dapp-creator-server/package.json ^7.3.4
./infra/ipfs-proxy/package.json ^7.3.4
./infra/dapp-creator-client/package.json ^7.3.4
./infra/token-transfer-server/package.json ^7.3.4
./infra/messaging/package.json ^7.3.4
./dapps/marketplace/package.json ^7.3.4
./dapps/admin/package.json ^7.3.4
X ./mobile/package.json ^7.4.4
./packages/event-cache/package.json ^7.3.4
./packages/contracts/package.json ^7.3.4
./packages/graphql/package.json ^7.3.4
@babel/polyfill
./infra/dapp-creator-client/package.json ^7.2.5
./infra/token-transfer-server/package.json ^7.2.5
./infra/messaging/package.json ^7.2.5
X ./mobile/package.json ^7.4.4
./packages/contracts/package.json ^7.2.5 …
```
> Script to show version differences between package.json files

- packages/graphql/src/resolvers/marketplace/listings.js
Fallback if discovery server returns error
> Fallback if discovery server returns error

- infra/discovery/src/listener/handler_identity.js
Do not require a profile pic for logging a GrowthEvent profile entry.
Addresses #2397
> Remove profile pic requirement

- packages/graphql/src/resolvers/IdentityEvents.js
- packages/graphql/src/server.js
- packages/graphql/src/utils/validateAttestation.js
- Attestation valid on either proxy or owner. 
- GraphQL server config override for proxies.
> Meta tx fixes

- dapps/marketplace/src/pages/user/User.js
- packages/graphql/src/resolvers/IdentityEvents.js
- Profile avatar was not working
- Attestation icons on user profile were not working
> Fixes for user profile and attestations

- infra/growth/package.json
Growth now needs discovery to be able to read data from the proxy DB table which is in discovery...
> [Growth] Add dependency on discovery

- mobile/ios/OriginCatcher.xcodeproj/project.pbxproj
- mobile/ios/OriginCatcher/Info.plist
- mobile/package.json
- mobile/src/components/transaction-card.js
Give payment a 0 value to stop the total being calculated as NaN. 🙈
> Fix NaN display on listing creation/blockchain transaction in mobile

- packages/mobile-bridge/src/index.js
Forward `signPersonalMessage` to mobile.
> Handle personal signing in mobile bridge

- packages/graphql/src/mutations/_relayer.js
- packages/mobile-bridge/src/index.js
Per title. Also updated mobile bridge to give personal sign its own method so mobile can distinguish.
> Send full meta tx to mobile

- dapps/marketplace/src/components/Reviews.js
- dapps/marketplace/src/index.js
- dapps/marketplace/src/pages/listing/ListingDetail.js
- dapps/marketplace/src/pages/user/User.js
- dapps/marketplace/webpack.config.js
- packages/eventsource/src/index.js
- packages/graphql/src/resolvers/Marketplace.js
- packages/graphql/src/resolvers/User.js
- packages/graphql/src/utils/apolloPathToString.js
This PR is mostly to help diagnose #2346, and takes a couple shots in the dark at fixing it.  So far I've been unable to repro the error at all.
This includes:
- ~~A change to provide Sentry with the proper dapp URL~~
- Logging messages in places I think might help
- Some queries are now skipped without proper ID
- ~~Enables source maps for production, though I'm not sure if anything else needs to be done here for this to work in prod.  @nick?~~
> Instrumentation!

- infra/relayer/src/util.js
Didn't show up in testing, I guess ganache is just way too forgiving.
> Fixes improperly formatted RPC requests made in Purse

- dapps/marketplace/src/pages/growth/Purchases.js
- dapps/marketplace/src/pages/growth/Verifications.js
> fix image paths

- dapps/marketplace/webpack.config.js
Add source maps to production build
> Add source maps to production build. Closes #2471

- dapps/marketplace/src/components/MobileModal.js
- dapps/marketplace/src/pages/user/Profile.js
- dapps/marketplace/src/pages/user/_EditModal.js
- dapps/marketplace/src/pages/user/_EditProfile.js
Should fix the following comments from @micahalcorn on #2398
> DApp3 fixes

- infra/relayer/src/purse.js
- infra/relayer/test/purse.test.js
This:
- Fixes a BigNumber calculation issue
- Adds transaction object storage, currently for debugging (figture re-signing functionality)
Ref: #2527 and #2528
> Purse debugging and fixes

- infra/ipfs-proxy/src/app.js
> Allow mp4 in ipfs-proxy

- Dockerfile
- devops/dockerfiles/event-listener
- devops/dockerfiles/origin-admin
- devops/dockerfiles/origin-cron
- devops/dockerfiles/origin-dapp
- devops/dockerfiles/origin-dapp-creator-client
- devops/dockerfiles/origin-discovery
- devops/dockerfiles/origin-graphql
- devops/dockerfiles/origin-growth
- devops/dockerfiles/origin-notifications
- docker-compose.yml
Fixes docker issue introduced with the new web3-provider package
> Fixes docker issues for web3-provider package

- mobile/src/components/no-rewards-card.js
- mobile/src/utils/price.js
Vertically centers the mobile growth warning and fixes bad prettier string.
> Center mobile growth alert

- dapps/marketplace/src/pages/onboard/Email.js
> Onboard back button

- mobile/android/app/src/main/res/values/strings.xml
- mobile/ios/OriginCatcher/Info.plist
Changes name to Origin for Android and iOS.
> Rename mobile to Origin

- infra/bridge/src/controllers/github.js
- infra/bridge/src/utils/validation.js
- infra/bridge/test/facebook.js
- infra/bridge/test/github.js
- infra/bridge/test/google.js
- infra/bridge/test/kakao.js
- infra/bridge/test/linkedin.js
- infra/bridge/test/twitter.js
- infra/bridge/test/wechat.js
> Add "User-Agent" to GitHub attestation

- dapps/marketplace/src/pages/create-listing/ChooseCategory.js
- dapps/marketplace/src/pages/create-listing/listing-types/ServiceListing/Review.js
- dapps/marketplace/src/pages/create-listing/listing-types/ServiceListing/ServiceListing.js
- dapps/marketplace/src/pages/create-listing/listing-types/index.js
- dapps/marketplace/src/pages/create-listing/mutations/_listingData.js
- dapps/marketplace/src/pages/listing/ListingDetail.js
- dapps/marketplace/src/pages/listing/_ListingEditOnly.js
- dapps/marketplace/src/pages/transactions/Listings.js
- dapps/marketplace/src/queries/Fragments.js
- packages/eventsource/src/index.js
- packages/graphql/src/resolvers/index.js
- packages/graphql/src/typeDefs/Marketplace.js
- packages/graphql/src/typeDefs/fragmentTypes.js
- packages/token/package.json
Same as UnitListing but no quantity specified when creating listing
> New ServiceListing type

- devops/kubernetes/charts/ethereum-network/templates/geth-genesis.configmap.yaml
Forking at block `1201800`.  Need to get thid deployed soon.
> Constantinople fork on dev eth network

- dapps/marketplace/src/pages/create-listing/Pricing.js
- packages/graphql/src/mutations/_txHelper.js
Allow zero value listings to be created
> Zero price listings

- infra/relayer/src/relayer.js
Normalizes addresses for comparison in relayer
> normalize addresses before comparison in relayer

- dapps/marketplace/src/pages/nav/Profile.js
Resolves issue: https://github.com/OriginProtocol/origin/issues/2624
> Resolve navigation button behaviour

- devops/cloud-functions/gcf-pin-ipfs-hash/package-lock.json
- devops/cloud-functions/gcf-pin-ipfs-hash/package.json
Just a missing dependency in the package.json.
> Add safe-buffer to pin service cloud function package.json

- infra/relayer/src/relayer.js
Those values were set based on data from Mainnet transactions that are recorded in the relayer_txn DB table.
> [Relayer] Reduce gas

- infra/relayer/src/purse.js
Adds instrumentation to get to the bottom of the funding issue on prod.  @franckc, any others you think might want to see added?
> More Purse instrumentation

- infra/discovery/src/listener/handler_proxy.js
> [Listener] Ignore event with zero proxy address

- devops/kubernetes/values/origin/values-dev.yaml
- infra/relayer/src/purse.js
Couple of fixes here:
1) Fix to prevent a race condition where two transactions could be sent if some JSON-RPC requests take longer than expected
2) Fix where the pending funding transaction switch might get flipped before funding has been completed
> Purse duplicate funding transactions

- infra/relayer/package.json
- infra/relayer/src/debug-cli.js
Our relayer transactions are a little hairy to decode on the blockchain. 
This currently repeatedly unwraps the input parameters, giving you the story on what what the relayer transaction is intended to do. This is very much a draft at the moment - I've only implemented more detailed expanding for the methods I have run across.
```
============
0x21c67e7587f2e248966665d3df4b472474700d9cc0ff340c2a73314266921b7c
--> 1. createProxyWithSenderNonce
{ _mastercopy: '0xb8B530afcfc283EE330F9FcaEa26468c4007c0C3',
initializer:
'0x8fe94fb2000000000000000000000000174a9986974899c522d6e30b0f125bc90a0317170000000000000000000000008ac16c08105de55a02e2b7462b1eec6085fa4d860000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000 …
```
> TX info CLI

- packages/token/src/contractHelper.js
The reward payout script was failing when using Alchemy provider, but not Infura. This should fix it.
> Fix token transfer logic to handle Parity receipts

- dapps/marketplace/src/pages/listing/_BuyFractional.js
- dapps/marketplace/src/pages/listing/_BuyFractionalHourly.js
> Repair ETH Fractional Purchases

- packages/ipfs/src/index.js
- packages/services/index.js
minor instrumentation to help debugging services and ipfs.  Helped when I was debugging something earlier and figured it was useful enough to commit.
> Trivial instrumentation addition

- devops/kubernetes/charts/origin/templates/dapp.ingress.yaml
Adds shoporigin.co to the dapp ingress.
> Add shoporigin.co

- devops/kubernetes/charts/origin/templates/dapp.ingress.yaml
Adds www.shoporigin.co to Ingres spec tls for dapp
> www.shoporigin.co TLS config and addition of shoporigin.com

- mobile/src/components/pin-input.js
- mobile/src/screens/onboarding/email.js
- mobile/src/screens/onboarding/phone.js
- mobile/src/styles/onboarding.js
- Workaround for react-native bug where focusing on a TextInput on Android doesn't pop the keyboard (as described by @kayyoo23, thanks!)
- Fix for crashes on Android for TextInput color change where a default color isn't specified 😳 
- Fix for form error not displaying
> Android mobile fixes

- infra/notifications/src/app.js
I noticed some crashes in the notification server.
Updating a bit the instrumentation to gather data to troubleshoot.
> [Notification] Add instrumentation to troubleshoot prod issue

- infra/relayer/src/purse.js
This PR adds better error output if _process dies, also wraps blocks of functionality in `_process()` with try/catch blocks so problems can be narrowed down and makes it less likely to cause a process termination
Sorry, the diff sucks on this one.  The only changes to `_process()` is adding the try/catch wrappers.
> Purse: Improved error handling and logging

- package.json
Should use scope instead of prefix.
> Fix start command in root package.json

- infra/growth/src/scripts/calculateRewards.js
- infra/growth/src/scripts/distributeRewards.js
- infra/growth/src/scripts/sendPayoutEmails.js
Update the growth payout scripts so that a specific eth address can be provided for handling one-off post campaign payout adjustment.
> [Growth] Update scripts for one-off payout adjustment

- dapps/marketplace/test/index.js
> Puppeteer test fix

- infra/relayer/package.json
- infra/relayer/src/purse.js
- infra/relayer/src/relayer.js
- infra/relayer/src/sentry.js
- yarn.lock
Adds Sentry error reporting to the Relayer
> Adds Sentry to Relayer

- packages/graphql/src/resolvers/web3/transactions.js
Adding a consistency check to help troubleshoot issue #2623
> Add check for event.id in getTransactionReceipt resolver

- dapps/marketplace/src/pages/notifications/NotificationRow.js
> fix problem

- .circleci/config.yml
- infra/token-transfer-server/src/scripts/show_events.sh
- infra/token-transfer-server/src/scripts/show_grants.sh
> [T3] Add unit tests to circleci

- dapps/marketplace/src/pages/messaging/Message.js
- dapps/marketplace/src/pages/messaging/Messages.js
Some minor design tweaks for messaging that will
- Make the messaging bubble wider and remove avatar beside each message
- Fix the conversation name
> Messaging Design Tweaks

- docs/software/dapp.md
The previous link is no longer valid and I have updated it to shoporigin.com. It is better because it is right.
> Updated dapp.originprotocol.com to shoporigin.com

- dapps/marketplace/src/pages/listing/ListingDetail.js
Resolves https://github.com/OriginProtocol/origin/issues/2753 ✅
> Listing Image Gallery Repair

- mobile/android/app/build.gradle
- mobile/android/build.gradle
Solves #2517 and #2516. Looks good locally, will test in Play beta after merged.
> Upgrade to 28 and build for 64 bit

- dapps/marketplace/src/utils/marketplaceCreator.js
Adds shoporigin.com to the list of marketplace creator config exceptions.
> Dont attempt to load marketplace creator config for shoporigin.com

- devops/dockerfiles/event-listener
- devops/dockerfiles/origin-bridge
- devops/dockerfiles/origin-discovery
- devops/dockerfiles/origin-growth
- devops/dockerfiles/origin-notifications
Update Dockerfiles for deployment
> Fix deploy scripts

- infra/growth/src/models/index.js
Should fix a bug related to growth-event in production
> Include growth-event models with growth models

- infra/relayer/src/purse.js
Adds some logic to prevent race conditions occurring during `getAvailableAccount()`
> Purse race prevention in account selection

- dapps/marketplace/src/pages/identity/EmailAttestation.js
- dapps/marketplace/src/pages/identity/EmailAttestationModal.js
fix a bug where email attestation wouldn't close when clicking on cancel.
> fix email modal not closing when clicking cancel

- dapps/marketplace/src/pages/create-listing/CreateListing.js
> Puppeteer fix

- infra/bridge/src/hooks/twitter.js
> [SocialSharing] Add instrumentation to bridge to debug Twitter webhook

- .circleci/config.yml
- infra/growth/src/resources/rules.js
This PR will the make the growth server to fetch the latest identity and also add support for proxy addresses
> [SocialRewards] Use proxy to get identity

- infra/bridge/src/controllers/promotions.js
Minor fix that returned null when extracting profile from event
> [SocialRewards] Fix twitterProfile bug

- infra/growth/src/resources/rules.js
- infra/growth/src/scripts/manageCampaign.js
- infra/growth/src/util/fixtures.js
- fix a problem where all events were considered for share rewards and not only twitter share events
- Add August campaign fixture
> Sparrow dom/growth social fixes3

- infra/bridge/src/controllers/hooks/index.js
- infra/bridge/src/controllers/promotions.js
Add verbose logs to debug bridge on staging
> Add logs to debug bridge

- dapps/marketplace/src/pages/growth/Promotions.js
Styling fix for mobile link previews
> Minor styling fix

- infra/bridge/src/controllers/hooks/index.js
Just for the demo today. Will be reverted after the demo
> Workaround for demo

- infra/bridge/src/hooks/twitter.js
- infra/growth/campaigns/august.js
- infra/growth/test/apollo-adapter-august.test.js
- infra/growth/test/rules-august.test.js
> [Social sharing] Fix tests, add some logging, remove fake rules translation

- infra/growth/campaigns/august.js
Using latest content from [this doc](https://docs.google.com/spreadsheets/d/1akbpgFFy5vW-PszmcJNImIW2rjkiwDk4xVXlUO7fMzo/edit#gid=1116035166)
> [Social Sharing] Update tweet content

- infra/bridge/src/hooks/twitter.js
> Update subscription URL

- infra/bridge/src/controllers/hooks/index.js
- infra/bridge/src/hooks/twitter.js
Revert back things I did in the PR #2839
> Another bridge hotfix

- dapps/marketplace/src/components/growth/ActionList.js
> fix layout issue

- infra/growth/src/resources/rules.js
- infra/growth/test/rules.test.js
- fixes a problem where users would get a too little reward for sharing Twitter content
> Sparrow dom/growth social fixes4

- dapps/marketplace/src/components/growth/ActionGroupList.js
Should change order of Growth actions to:
- Verifications
- Follow
- Promote
- Invitations
- Purchases
> Change order of growth actions

- mobile/src/screens/marketplace.js
- mobile/src/utils/index.js
Twitter does not display the share dialog with the user agent that is default to react Native webView. For that reason we replace that user agent with a working one
**Solves issue:**https://github.com/OriginProtocol/origin/issues/2844
> Sparrow dom/origin wallet twitter workaround

- infra/growth/src/apollo/resolvers.js
- packages/graphql/src/links/remoteSchema.js
- packages/graphql/src/links/schema.js
By adding `growth_wallet_override` and `growth_admin_secret` (this one is available in EnvKey) you can inspect the DApp rewards as a person specified in the `growth_wallet_override`.
> Sparrow dom/rewards inspector

- devops/dockerfiles/origin-cron
Fixes missing deps on origin-cron Dockerfile
> Dockerfile fixes for origin-cron

- docker-compose.yml
This tries to make migrations a bit more manageable since there seems to be a lot of interdependencies between database tables and packages.
For instance, anything that depends on `@origin/growth-event` would fail if the relevant tables were not found when the service was brought up even though migrations might be getting run by a non-dependent service.
This runs all migrations from the services container, and makes the relevant services wait for services to become available before running their command.
CC: @rtman 
closes #2872
> Docker compose dependency fixes

- docker-compose.yml
set `INDEX_PROXY=true` in `docker-compose.yml`
> Index proxies on local docker setup

- infra/bridge/src/controllers/hooks/index.js
- infra/bridge/test/hooks.js
> Add `sha256=` prefix to Twitter sign

- infra/bridge/src/controllers/hooks/index.js
- infra/bridge/test/hooks.js
Disabling it for now. Will submit another PR to fix that.
> Disable twitter sign validation temporarily

- infra/growth/src/scripts/distributeRewards.js
- infra/growth/src/templates/emailPayout.html
- infra/growth/src/templates/emailPayout.txt
- infra/growth/src/util/tokenDistributor.js
- packages/token/src/config.js
- packages/token/src/token.js
Fixed a few bugs due to the Token class refactor.
Updated email templates for July campaign.
> [OriginRewards] Misc payout pipeline fixes

- dapps/marketplace/src/components/growth/Action.js
show 0 OGN where there is no reward
> show 0 OGN where there is no reward

- packages/graphql/src/mutations/messaging/sendMessage.js
An error state was justified for #2888, but the error left much to be wanted.
> Replaces one error with another

- infra/bridge/test/airbnb.js
- infra/bridge/test/email.js
- infra/bridge/test/exchange-rate.js
- infra/bridge/test/facebook.js
- infra/bridge/test/github.js
- infra/bridge/test/google.js
- infra/bridge/test/hooks.js
- infra/bridge/test/identity.js
- infra/bridge/test/kakao.js
- infra/bridge/test/linkedin.js
- infra/bridge/test/phone.js
- infra/bridge/test/promotions.js
- infra/bridge/test/twitter.js
- infra/bridge/test/website.js
- infra/bridge/test/wechat.js
> Fix bridge test mess

- devops/dockerfiles/origin-messaging
origin-messaging needs to deal with the new dep of @origin/graphql
> origin-messaging needs grpahql

- infra/faucet/src/ogn.js
- infra/faucet/src/scripts/airDrop.js
Someone committing to master again? Oh hi @franckc 😁
> Fix linting in faucet

- docker-compose.yml
- packages/graphql/src/configs/docker.js
don't use localhost for inter-service communication between docker containers
> Local Docker services fix

- dapps/marketplace/src/pages/identity/TelegramAttestation.js
- infra/bridge/test/telegram.js
Remove the hardcoded bot username and switch to build-time environment variable
> Fix Bot Username on Staging

- dapps/marketplace/src/components/growth/ActionGroup.js
- dapps/marketplace/src/pages/identity/TelegramAttestation.js
- dapps/marketplace/webpack.config.js
- Should fix the white screen issue on Origin Wallet after successful attestation
- Support for different bots on staging and production
> Changes to push Telegram attestation to production

- dapps/marketplace/src/components/growth/Action.js
Allow clicking on some actions when they are completed
> Allow clicking on some actions when they are completed

- infra/faucet/src/ogn.js
> [Faucet[ Add logging to debug dev issue

- .circleci/config.yml
Raised sleep to 10 to wait for graphql server to spin up for GraphQLEngineSchemaCheck
> GraphQLEngineSchemaCheck Fix

- infra/notifications/src/app.js
> [Notification server] Fix typo causing crash

- dapps/admin/package.json
- dapps/marketplace/package.json
- dapps/marketplace/test/index.js
- dapps/marketplace/webpack.config.js
- infra/bridge/package.json
- infra/growth-event/package.json
- infra/messaging/package.json
- infra/notifications/package.json
- package.json
- packages/event-cache/package.json
- packages/eventsource/package.json
- packages/graphql/fixtures/populate.js
- packages/graphql/src/utils/currencies.js
- packages/ip2geo/package.json
- packages/ipfs/package.json
- packages/services/package.json
- packages/validator/package.json
- packages/web3-provider/package.json
- yarn.lock
Turns out exchange rates were still being fetch in puppeteer tests
> Another attempt at fixing flaky tests

- dapps/marketplace/src/pages/promote-listing/Amount.js
- dapps/marketplace/src/pages/promote-listing/Budget.js
> Flaky tests

- dapps/admin/package.json
- dapps/admin/src/utils/formatDate.js
- dapps/marketplace/package.json
- dapps/marketplace/src/utils/formatDate.js
- dapps/marketplace/webpack.config.js
Remove date-fns dependency from marketplace dapp
> Date package update

- packages/graphql/src/contracts.js
- packages/graphql/src/mutations/_txHelper.js
Remove unnecessary call to getBlockByNumber
> No get block

- dapps/marketplace/src/components/AboutParty.js
- dapps/marketplace/src/components/EthAddress.js
- dapps/marketplace/src/hoc/withIdentity.js
- dapps/marketplace/src/pages/user/Profile.js
Use SkinnyIdentityQuery in a few more places
> Optimize identity query

- dapps/marketplace/src/pages/listings/Listings.js
- dapps/marketplace/src/pages/listings/SortMenu.js
Fixes for small styling issues on listing sorting
> Sort style fix

- packages/graphql/fixtures/_demoListings.js
- packages/graphql/src/resolvers/marketplace/listings.js
Fix for multi contract listing pagination
> Fix for multi contract listing pagination

- README.md
- infra/bridge/README.md
- infra/bridge/src/utils/exchange-rate.js
- infra/discovery/README.md
- infra/discovery/src/apollo/README.md
- infra/discovery/src/listener/listener.js
- packages/graphql/src/resolvers/marketplace/listings.js
- packages/services/index.js
- packages/services/start.js
- Fix up some READMEs
- Listener for marketplace should default to v0
- GraphQL fix for discovery result listing IDs.
- Add listener and discovery to `@origin/services`
> Listener + discovery multi-contract fix

- dapps/marketplace/src/pages/messaging/Messages.js
> Add webkit overflow scrolling to messaging containers

- devops/kubernetes/charts/ethereum-network/templates/geth-genesis.configmap.yaml
- devops/kubernetes/charts/ethereum-network/values.yaml
Upgrades to the dev Ethereum network
Ref: #2589
Config ref: https://github.com/ethereum/go-ethereum/blob/master/cmd/puppeth/wizard_genesis.go#L47-L53
> geth upgrade, Constantinople and Petersburg

- infra/token-transfer-client/src/components/SessionTable.js
- infra/token-transfer-client/src/components/WithdrawalHistoryCard.js
- infra/token-transfer-client/src/components/pages/Phone.js
- infra/token-transfer-client/src/components/pages/Terms.js
- infra/token-transfer-client/src/reducers/transfer.js
- infra/token-transfer-server/package.json
- infra/token-transfer-server/src/app.js
- infra/token-transfer-server/src/config.js
- infra/token-transfer-server/src/controllers/transfer.js
- infra/token-transfer-server/src/lib/transfer.js
- infra/token-transfer-server/src/lib/webhook.js
- yarn.lock
- Fixed a few display bugs
- Fixed bug with balance not updating properly due to broken transfers reducer
- Added some security headers via `helmet`
- Added discord webhook for queued token transfers
> More T3 fixes

- dapps/marketplace/src/hoc/withIsMobile.js
- dapps/marketplace/src/pages/listings/_Search.js
This PR fixes several responsive issues:
- The search bar and nav list elements no longer overlap
- The search bar's right border is visible now when the clear button is enabled
- The clear button's placement is correct throughout all breakpoints
- The navbar no longer breaks at `767px` width ([fixes this](https://i.norbert.dev/7eb243))
<a href="http://i.norbert.dev/3ef8c6" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/0B130z161w2H3k1O423N/Screen%20Recording%202019-08-27%20at%2012.42%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>
<a href="http://i.norbert.dev/4fd179" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/1c3038001R3h09272i3z/Screen%20Recording%202019-08-27%20at%2012.44%20PM.gif" style="display: block;height: …
> Fix responsive header issues

- package.json
- packages/services/index.js
- packages/services/package.json
- yarn.lock
Upgrade IPFS package in `@origin/services`
> Upgrade IPFS

- .circleci/config.yml
Allow CircleCI to run tests for non-OriginProtocol org PRs
> CircleCI checkout command for non-origin PRs

- infra/growth/campaigns/september.js
- infra/growth/src/resources/rules/baseRule.js
- adds link to 2 tweets
- fixes joinRewards article
- fixes unlock condition messages on Rewards Campaign page
> September rewards fixes

- dapps/marketplace/src/components/WaitForTransaction.js
- dapps/marketplace/src/index.js
- dapps/marketplace/src/utils/sentry.js
Quick & dirty integration of Sentry into `WaitFortransaction` component for #3199
> Sentry integration into WaitForTransaction

- dapps/marketplace/src/pages/listing/mutations/Buy.js
- packages/graphql/src/mutations/_txHelper.js
Prevent modal dismiss. Closes #2044
> Prevent modal dismiss

- dapps/marketplace/src/pages/App.js
Sentry catch-all.  Issue #3199
> Sentry catch-all in dapp

- dapps/marketplace/src/pages/listing/mutations/Buy.js
- dapps/marketplace/src/pages/settings/Settings.js
- dapps/marketplace/src/pages/settings/_TextRow.js
- dapps/marketplace/src/pages/settings/_ToggleRow.js
- dapps/marketplace/src/queries/Config.js
- dapps/marketplace/src/utils/formHelpers.js
- packages/graphql/src/typeDefs/Web3.js
- Configure GraphQL Server
- Toggle Performance Mode
- Toggle onboarding requirement
- General refactor
> Settings page improvments

- dapps/marketplace/src/components/MetaMaskAnimation.js
- dapps/marketplace/src/hoc/withIsMobile.js
- dapps/marketplace/src/pages/onboard/MetaMask.js
- dapps/marketplace/src/pages/onboard/Wallet.js
Disable MetaMask animation on mobile. 
Closes #3213
> Disable MetaMask animation on mobile wallets

- dapps/admin/webpack.config.js
- dapps/graphql-simple-demo/webpack.config.js
- dapps/marketplace/webpack.config.js
- infra/dapp-creator-client/webpack.config.js
New version of Terser outputs comments in separate file. Disable that behavior.
> Disable terser comments

- packages/graphql/src/mutations/marketplace/makeOffer.js
Should fix listings that require shipping address on dev/staging
> Use proxy owner address for OutOfBand messages

- packages/graphql/src/mutations/marketplace/makeOffer.js
A minor thing that I overlooked in PR #3251
> Await `proxyOwner`

- dapps/marketplace/src/pages/listing/_ConfirmShippingAndPurchase.js
- dapps/marketplace/test/_helpers.js
- packages/graphql/src/resolvers/messaging/Messaging.js
Should fix the failing marketplaces tests on master
> Fix marketplace tests

- dapps/marketplace/src/pages/listing/ProvideShippingAddress.js
- dapps/marketplace/src/pages/listing/_PaymentOptions.js
- dapps/marketplace/src/pages/listing/_PurchaseSummary.js
- dapps/marketplace/src/pages/transaction/_OfferAcceptedBuyer.js
- dapps/marketplace/src/pages/transaction/_Progress.js
- dapps/marketplace/src/pages/transaction/_ReviewAndFinalization.js
- dapps/marketplace/src/pages/transaction/_ShippingAddress.js
- dapps/marketplace/src/queries/DecryptShippingAddress.js
- packages/graphql/src/typeDefs/Marketplace.js
- packages/graphql/src/typeDefs/Messaging.js
Should address the things listed by @micahalcorn in #3258
> Shipping address revisions

- packages/mobile-bridge/src/EthGasStationProvider.js
While I think it's unlikely the cause of #3266 is this subprovider, better safe than sorry.  This includes some logic updates and sanity checks to try not to return bogus data for `eth_gasPrice` calls.
Unable to really test this...
> Safety netting in mobile-bridge's EthGasStationProvider

- dapps/marketplace/webpack.config.js
> Add GAS_PRICE_KEY to dapp webpack config

- dapps/marketplace/src/utils/sentry.js
- dapps/marketplace/webpack.config.js
Makes sure the env vars used by sentry are included in the build.
- `NAMESPACE`
- `ETH_NETWORK_ID`
> Dap env vars fix for Sentry

- packages/graphql/src/mutations/_txHelper.js
`resetProxyCache` should be called when using the relayer, not just when sending via the local wallet.  This may help with some of the various proxy issues we've seen recently, including requests being re-sent to the relayer returning "Proxy already exists".
> resetProxyCache should also be called when using the relayer

- dapps/marketplace/public/translations/de_DE.json
- dapps/marketplace/public/translations/el_GR.json
- dapps/marketplace/public/translations/es_ES.json
- dapps/marketplace/public/translations/fil_PH.json
- dapps/marketplace/public/translations/fr_FR.json
- dapps/marketplace/public/translations/hr_HR.json
- dapps/marketplace/public/translations/id_ID.json
- dapps/marketplace/public/translations/it_IT.json
- dapps/marketplace/public/translations/ja_JP.json
- dapps/marketplace/public/translations/ko_KR.json
- dapps/marketplace/public/translations/nl_NL.json
- dapps/marketplace/public/translations/pt_PT.json
- dapps/marketplace/public/translations/ro_RO.json
- dapps/marketplace/public/translations/ru_RU.json
- dapps/marketplace/public/translations/th_TH.json
- dapps/marketplace/public/translations/tr_TR.json
- dapps/marketplace/public/translations/uk_UA.json
- dapps/marketplace/public/translations/vi_VN.json
- dapps/marketplace/public/translations/zh_CN.json
- dapps/marketplace/public/translations/zh_TW.json
- dapps/marketplace/src/pages/promote-listing/HowWorks.js
- dapps/marketplace/translation/crowdin/all-messages.json
> Disable promotion on Mainnet

- dapps/marketplace/src/hoc/withWalletBalances.js
- dapps/marketplace/src/mutations/WithdrawDust.js
- dapps/marketplace/src/pages/settings/Settings.js
- dapps/marketplace/src/pages/settings/_WithdrawDust.js
- packages/graphql/src/mutations/_gasCost.js
- packages/graphql/src/mutations/index.js
- packages/graphql/src/mutations/marketplace/withdrawDust.js
- packages/graphql/src/typeDefs/Marketplace.js
Allows the users to withdraw token dusts from their proxy addresses.
> Add "Withdraw Dust" option under "Developer's Mode"

- dapps/marketplace/src/components/growth/Action.js
- mobile/README.md
- mobile/src/screens/marketplace.js
Should fix Telegram attestation on Origin Marketplace app.
Closes #3315
> Fix Telegram Attestation on Mobile

- dapps/marketplace/src/pages/create-listing/ChooseCategory.js
- dapps/marketplace/src/pages/promote-listing/HowWorks.js
- packages/graphql/src/mutations/marketplace/withdrawDust.js
> Add back icon to Listing Promotion and fix mainnet warning constraint

- packages/event-cache/src/EventCache.js
Added a check to help debug issue #2944
> [EventCache] Add defensive check to getPastEvents

- packages/contracts/contracts/token/OriginToken.sol
Per security audit, updated the comments on the OGN contract to mention the increase/decreaseApproval are supported.
> [OGN contract] Update comment to mention increase/decreaseApproval methods

- mobile/src/PushNotifications.js
Added instrumentation to help diagnose issue #3438 
Let me know if you can think of other places where I should also add instrumentation...
> [Mobile] Capture failures to register with notification server in Sentry

- packages/graphql/src/mutations/identity/deployIdentity.js
> Fix deployIdentity on prod

- dapps/marketplace/src/pages/create-listing/CreateListing.js
- dapps/marketplace/src/pages/create-listing/listing-types/Steps.js
- dapps/marketplace/test/index.js
- dapps/marketplace/test/multiUnit.js
- dapps/marketplace/test/utils/_actions.js
Prevent Listing Type Editing. 
Closes #3224
> Prevent Listing Type Editing

- infra/relayer/src/purse.js
adds some extra instrumentation and error handling to Purse. 
Ref #3512
> More instrumentation and error handling for Purse

- dapps/marketplace/src/mutations/MakeOffer.js
- dapps/marketplace/src/pages/listing/mutations/Buy.js
- packages/graphql/src/mutations/marketplace/makeOffer.js
- packages/graphql/src/mutations/marketplace/updateListing.js
- packages/graphql/test/index.js
Remove validation calls from mutations as they require expensive calls to eventSource
> Remove remaining eventSource calls in mutations

- packages/graphql/src/mutations/marketplace/makeOffer.js
> Fix makeOffer mutation

- mobile/ios/OriginMarketplace/Info.plist
- mobile/package.json
- mobile/src/constants.js
- mobile/src/screens/importMnemonic.js
- mobile/src/screens/importPrivateKey.js
- mobile/src/styles/onboarding.js
- mobile/translation/crowdin/all-messages.json
Fixes an Android crash popping up in Sentry e.g. https://sentry.io/organizations/origin-protocol/issues/1218247199/?project=1399965&query=is%3Aunresolved&statsPeriod=14d.
This happens if you set a color on a TextInput and later remove it.
> Fix Android color crash

- packages/graphql/src/contracts.js
> Fix flaky graphql test?

- dapps/marketplace/src/components/WaitForTransaction.js
- packages/graphql/src/contracts.js
- packages/graphql/src/server.js
Cuts down on time waiting for transactions to mine. 
Cuts down performanceMode puppeteer test time from ~14 mins to ~10 mins.
> Refactor WaitForTransaction to use subscriptions

- packages/graphql/src/configs/mainnet.js
include the address in the graphql config.  v1 for real this time.
> v1 marketplace graphql config

- infra/growth/campaigns/october.js
Fixed video links for October campaign.
> [Growth] Fix sharing links

- infra/growth/test/apollo-adapter-october.test.js
Broke tests in #3593 :(
Need to update twitter content hash in the tests when updating content...
> [Growth] Fix tests

- dapps/marketplace/src/components/EnableMessagingModal.js
- dapps/marketplace/src/pages/messaging/RefetchOnMessageData.js
- dapps/marketplace/src/pages/messaging/Room.js
- dapps/marketplace/src/pages/nav/Messages.js
- dapps/marketplace/src/queries/MessagingReadySubscription.js
- dapps/marketplace/src/queries/MessagingStatusChangeSubscription.js
- packages/graphql/src/resolvers/Subscription.js
- packages/graphql/src/resolvers/messaging/Conversation.js
- packages/graphql/src/resolvers/messaging/Messaging.js
- packages/graphql/src/typeDefs/Messaging.js
- packages/messaging-client/src/Messaging.js
Should fix the issues listed in #3625
> Messaging fixes for staging

- dapps/marketplace/src/hoc/withOffer.js
- dapps/marketplace/src/pages/messaging/Messages.js
- dapps/marketplace/src/pages/messaging/OfferEvent.js
- dapps/marketplace/src/queries/Conversations.js
- dapps/marketplace/src/queries/Room.js
- packages/graphql/src/resolvers/messaging/Conversation.js
- packages/graphql/src/typeDefs/Messaging.js
- packages/messaging-client/src/Messaging.js
> Defer messaging event loading

- .circleci/config.yml
- dapps/marketplace/test/fractional.js
- dapps/marketplace/test/utils/_actions.js
> Run CircleCI Puppeteer tests in parallel

- infra/growth/src/util/fixtures.js
> Fixing fixture id

- dapps/marketplace/src/components/QueryError.js
Fixes an issue I introduced in #3535 
Closes #3659
> Better handling of errors in QueryError

- infra/relayer/src/purse.js
When the master balance gets really low, there's a good chance no transactions will be pushed through, meaning no balance checks and updates.  When this happens, the relayer will become depressed and just do nothing forever because it doesn't think it has the funds to work.  This PR makes sure it obsessively(every 3 seconds) checks balances when the master account becomes depleted.
closes #3682
> Obsessively check balance when master balance is depleted

- devops/kubernetes/charts/ethereum-network/templates/geth-genesis.configmap.yaml
Did a dev chain reset, but we need byzantium and the rest.
> Dev chain reset

- packages/contracts/build/contracts_origin.json
> fresh contracts on dev!

- packages/mobile-bridge/src/index.js
We are removing one cache provider and one subscriptions provider with the old code. This is the providers list (without removing any): 
And after the PR change:
> Sparrow dom/mobile providers fix

- devops/kubernetes/charts/ethereum-network/templates/geth-miner.statefulset.yaml
- devops/kubernetes/charts/ethereum-network/templates/geth-tx.statefulset.yaml
Fixes quoting issue in PR #3713
> Fix quoting issue in ethereum-network charts

- dapps/admin/src/pages/contracts/Contracts.js
- packages/graphql/src/resolvers/Marketplace.js
- packages/graphql/src/resolvers/Query.js
- packages/graphql/src/resolvers/Token.js
Better fault tolerance for admin and graphql.
> More admin fixen

- infra/bridge/src/controllers/hooks/telegram.js
- infra/bridge/src/controllers/hooks/twitter.js
- infra/bridge/src/controllers/promotions.js
> Add instrumentation to Telegram webhook

- dapps/marketplace/src/pages/nav/Nav.js
fix bug with screen console growing too big
> screen console logs growing too big fix

- packages/graphql/src/resolvers/User.js
Add some debug statements to debug #3353
> Add instrumentation to user review resolver

- infra/discovery/src/listener/webhooks.js
Fix bug where ethAddress was not passed properly to the email webhook
> [Listener] Fix email webhook

- packages/eventsource/src/index.js
- packages/graphql/src/resolvers/User.js
More handling of bad data coming from `getOffer` calls.
> More error handling for bad chain data

- mobile/ios/Podfile
- packages/graphql/src/resolvers/messaging/Messaging.js
- packages/messaging-client/src/Messaging.js
Should fix #3762. But not 100% sure.
> Potential fix for #3762

- packages/messaging-client/src/Messaging.js
> Fix DApp tests

- dapps/marketplace/src/components/EnableMessagingModal.js
- dapps/marketplace/src/pages/listing/_ConfirmPurchaseButton.js
- infra/messaging/src/index.js
- packages/messaging-client/src/Messaging.js
[Link to test build](https://originprotocol.github.io/test-builds/shah/)
- Fixes a minor glitch in staging that hides the "Enable Messaging" modal after the first sign
- Also a minor code cleanup and refactor
~~**Don't merge it. Testing it on mobile right now**~~ Tested the build on mobile. Seems to work fine for me.
> Clean up messaging status PubSub

- infra/token-transfer-client/src/components/pages/Terms.js
> Update T3 terms

- infra/identity/src/models/identity.js
- infra/identity/src/utils.js
Some columns of the identity table were not getting populated correctly.
> [Listener] Fix population of identity columns

- packages/contracts/build/contracts_origin.json
- packages/graphql/src/configs/origin.js
v1 marketplace deployed to dev network
> Adds v1 marketplace to origin network

- dapps/marketplace/src/pages/growth/Campaigns.js
- infra/growth/src/scripts/manageCampaign.js
See title.
Also update progress bar for FE.
> [Growth] Update manage campaign script for Nov.

- dapps/marketplace/src/pages/identity/mutations/DeployIdentity.js
refetch centralised identity data after it gets published
> refetch centralised identity data after it gets published

- devops/dockerfiles/event-listener
- devops/dockerfiles/origin-bridge
- devops/dockerfiles/origin-cron
- devops/dockerfiles/origin-dapp
- devops/dockerfiles/origin-dapp-creator-client
- devops/dockerfiles/origin-faucet
- devops/dockerfiles/origin-growth
- devops/dockerfiles/origin-messaging
- devops/dockerfiles/origin-notifications
- devops/dockerfiles/origin-relayer
- devops/dockerfiles/origin-token-transfer-client
- devops/dockerfiles/origin-token-transfer-server
Adds double quotes to eval statement in all dockerfiles to preserve whitespaces. Related to #3861
> Wrap every eval statement in double quotes

- infra/dapp-creator-server/package.json
> Add babel polyfill to creator server

- dapps/marketplace/src/pages/about/DappInfo.js
- Fixes DApp Info page error on mainnet
> Fix DApp info

- packages/graphql/src/contracts.js
Temporarily disabling some code to help troubleshoot issue #3898 on ImToken wallet.
> Disable websocket provider

- infra/token-transfer-client/src/components/GrantDetail.js
- infra/token-transfer-client/src/components/NewsHeadlinesCard.js
- infra/token-transfer-server/src/validators.js
Fix CSS imports for new version of react-swiper and TOTP issue.
> Fixes for swiper upgrade

- devops/dockerfiles/event-listener
Copy auth-client and auth-utils files to event-listener's image for building
> Fix eventlistener dockerfile

- devops/dockerfiles/event-listener
> Fix  directory on dockerfile

- dapps/admin/src/pages/marketplace/mutations/CreateListing.js
- dapps/marketplace/src/components/Balances.js
- dapps/marketplace/src/components/WithPrices.js
- dapps/marketplace/src/pages/create-listing/CreateListing.js
- dapps/marketplace/src/pages/create-listing/_PricingChooser.js
- dapps/marketplace/src/pages/listing/PaymentMethods.js
- dapps/marketplace/src/pages/listing/listing-types/fractional-hourly/withFractionalHourlyData.js
- dapps/marketplace/src/pages/listing/listing-types/fractional/withFractionalData.js
- dapps/marketplace/src/pages/listing/listing-types/multi-unit/withMultiUnitData.js
- dapps/marketplace/src/pages/listing/listing-types/single-unit/withSingleUnitData.js
- dapps/marketplace/src/pages/nav/SignIn.js
- dapps/marketplace/src/pages/onboard/Email.js
- dapps/marketplace/src/pages/onboard/_DownloadWalletCTA.js
- dapps/marketplace/src/pages/settings/_WithdrawDust.js
- dapps/marketplace/test/payments.js
- dapps/marketplace/test/singleUnit.js
- packages/graphql/src/mutations/marketplace/createListing.js
- packages/graphql/src/utils/supportedTokens.js
> Fix some DApp bugs

- devops/dockerfiles/origin-admin
Add `auth-utils` and `auth-client` packages to admin dockerfile
> Fix admin DApp dockerfile

- dapps/marketplace/src/pages/create-listing/CreateListing.js
- dapps/marketplace/src/pages/listing/_ConfirmPurchaseButton.js
- dapps/marketplace/src/pages/nav/Profile.js
- dapps/marketplace/src/pages/user/Profile.js
[Link to test build](https://originprotocol.github.io/test-builds/shah/#/)
If not logged in, should prevent users from
> Login enhancements

- docker-compose.yml
> fix auth server docker setup

- infra/growth/campaigns/november.js
- packages/eventsource/src/index.js
- packages/graphql/src/resolvers/Web3.js
- packages/services/index.js
Added a check to detech imToken wallet. Fixes #3212 
[Relevant Doc](https://docs.token.im/dapp-sdk/en/)
> Update walletType resolver to detect imToken

- dapps/marketplace/src/pages/create-listing/CreateListing.js
- packages/auth-client/src/auth-client.js
A temp fix for #3927 until I replace polling with subscriptions
> Fix Edit Listing Redirect

- mobile/src/AppContainer.js
- mobile/src/PushNotifications.js
- mobile/src/components/backup-prompt.js
- mobile/src/components/notification-card.js
- mobile/src/components/origin-web3view.js
- mobile/src/components/samsung-bks.js
- mobile/src/hoc/withConfig.js
- mobile/src/hoc/withOriginGraphql.js
- mobile/src/screens/account.js
- mobile/src/screens/backup.js
- mobile/src/screens/changePin.js
- mobile/src/screens/currency.js
- mobile/src/screens/importMnemonic.js
- mobile/src/screens/importPrivateKey.js
- mobile/src/screens/language.js
- mobile/src/screens/marketplace.js
- mobile/src/screens/pin.js
- mobile/src/screens/settings.js
- mobile/src/screens/welcome.js
- packages/eventsource/src/index.js
- packages/services/index.js
New version of prettier changed some things, so reprettify everything.
> Prettier upgrade

- infra/token-transfer-client/src/utils/index.js
- infra/token-transfer-server/migrations/20191114131900-add-revised-schedule-abstained-column.js
- infra/token-transfer-server/src/models/user.js
We needed a way to represent abstinence from voting on the revised vesting schedule.  These users should not be shown the revised vesting schedule to accept.
> Add T3 column for users who abstained from voting on the revised vesting schedule

- devops/dockerfiles/origin-discovery
- infra/token-transfer-client/src/components/AccountActions.js
- infra/token-transfer-client/src/components/BonusModal.js
- infra/token-transfer-client/src/components/GrantDetail.js
- infra/token-transfer-client/src/components/LockupCard.js
- infra/token-transfer-client/src/components/Navigation.js
- infra/token-transfer-client/src/components/VestingCard.js
- infra/token-transfer-client/src/components/pages/Dashboard.js
- infra/token-transfer-client/src/components/pages/Lockup.js
- infra/token-transfer-client/src/components/pages/News.js
- infra/token-transfer-client/src/components/pages/OtpExplain.js
- infra/token-transfer-client/src/components/pages/RevisedSchedule.js
- infra/token-transfer-client/src/components/pages/RevisedTerms.js
- infra/token-transfer-client/src/components/pages/Security.js
- infra/token-transfer-client/src/components/pages/Terms.js
- infra/token-transfer-client/src/css/navbar.css
All the small stuff that came out of T3 audit session. Will do the remaining bigger things in separate PRs.
> T3 copy and small layout tweaks

- infra/token-transfer-client/src/app.js
- infra/token-transfer-client/src/components/NavLink.js
- infra/token-transfer-client/src/components/ScrollToTop.js
Adds scroll to top for every route change in T3 and cleans up unused parameter in NavLink.
- ~~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)~~
> Implement scroll to top on all route changes in T3

- infra/token-transfer-client/src/app.js
- infra/token-transfer-client/src/components/pages/Welcome.js
Adds a T3 warning for small screen users advising them to switch to desktop/laptop. Closes #3978. 
- ~~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)~~
> T3 mobile warning modal

- infra/token-transfer-server/src/controllers/account.js
- infra/token-transfer-server/src/controllers/lockup.js
- infra/token-transfer-server/src/controllers/login.js
- infra/token-transfer-server/src/controllers/transfer.js
Add more logging to T3 to get visibility.
- ~~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)~~
> Add more logging to T3

- infra/growth/src/scripts/manageUser.js
Script to ban or close accounts.
> [Growth] Script to manager users

- infra/token-transfer-server/src/templates/lockup.mjml
- infra/token-transfer-server/src/templates/login.mjml
- infra/token-transfer-server/src/templates/transfer.mjml
- infra/token-transfer-server/src/templates/welcome.mjml
Removes the long links in emails in favour of the button only.
> Remove raw links in T3 emails

- devops/kubernetes/values/origin/values-dev.yaml
- infra/token-transfer-client/src/components/AccountTable.js
- infra/token-transfer-client/src/components/BonusCard.js
- infra/token-transfer-client/src/components/BonusModal.js
- infra/token-transfer-client/src/components/WithdrawalSummaryCard.js
- infra/token-transfer-client/src/components/pages/Lockup.js
- infra/token-transfer-client/src/components/pages/LockupConfirm.js
- infra/token-transfer-client/src/components/pages/Phone.js
- infra/token-transfer-client/src/components/pages/RevisedTerms.js
- infra/token-transfer-client/src/components/pages/Security.js
- infra/token-transfer-client/src/components/pages/Terms.js
- infra/token-transfer-server/src/templates/lockup.mjml
- infra/token-transfer-server/src/templates/lockup.txt
- infra/token-transfer-server/test/api/lockup.test.js
> Final 𝕿𝟥 Copy Scrub

- infra/token-transfer-client/package.json
- infra/token-transfer-client/src/app.js
- infra/token-transfer-client/src/components/BonusModal.js
- infra/token-transfer-client/src/components/Modal.js
- infra/token-transfer-client/src/components/WithdrawModal.js
- infra/token-transfer-client/src/hoc/withTracker.js
- yarn.lock
Pretty standard with a bit of extra stuff for tracking modal views (they don't cause route changes).
> T3 Google Analytics integration

- devops/dockerfiles/origin-messaging
- devops/dockerfiles/origin-notifications
Should fix the `messaging` and `notifications` builds that fail on dev.
> Fix dependencies on dockerfiles

- dapps/marketplace/src/utils/listing.js
- dapps/marketplace/test/utils/_actions.js
- packages/graphql/src/resolvers/attestations/checkTelegramStatus.js
Prettier run, @shahthepro I think you need to upgrade to 1.19.1, see https://app.circleci.com/jobs/github/OriginProtocol/origin/90324.
> Prettier fixes

- infra/discovery/src/listener/listener.js
Use PROVIDER_URL if it is defined
> [Listener] Use PROVIDER_URL

- packages/messaging-client/src/Messaging.js
[This changeset](https://github.com/OriginProtocol/origin/pull/3992/commits/5e0becc3df15a068f515483ca9abe2b2ead3354b) from me broke messaging encryption keys. This PR should fix that
> Fix messaging encryption key

- dapps/shop/README.md
- dapps/shop/index.js
- dapps/shop/package.json
- dapps/shop/webpack.config.js
> Instructions

- infra/growth/campaigns/december.js
- infra/growth/src/resources/rules/baseRule.js
There were a couple misconfiguration for the sharing content in december.
Also add a defensive check for calculation of earned rewards.
> Fix december config

- mobile/src/screens/partnerWelcome.js
Style fixes and verbiage updates per #4104
> style changes to partner welcome screen as requested by @micahalcorn

- infra/growth/src/scripts/manageCampaign.js
> Fixes issue in manageCampaign.js

- mobile/src/screens/authentication.js
- mobile/src/screens/pin.js
Should force the user with any referral code to go through the onboarding just like the partner referrals.
> Non-partner referral funnel

- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
> Fix alignment for checkboxes on Rewards terms acceptance page

- dapps/marketplace/src/components/_UserProfileCreated.js
- dapps/marketplace/src/hoc/withPartnerCampaignConfig.js
- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/onboard/Finished.js
- dapps/marketplace/src/pages/onboard/RewardsSignUp.js
- dapps/marketplace/src/utils/growthTools.js
> [Partner Referral Funnel] Fix alignment and reward values on DApp

- infra/growth/src/resources/email.js
Update referral link in invite emails.
> Fix referral URL

- infra/growth/src/apollo/app.js
Address lookup on DB has to be lower.  
Ref: #4131
> Address case fix for invite code lookup

- dapps/marketplace/src/components/growth/Action.js
- dapps/marketplace/src/pages/identity/OAuthAttestation.js
- dapps/marketplace/src/pages/nav/Nav.js
- dapps/marketplace/src/pages/onboard/Email.js
- dapps/marketplace/src/pages/onboard/Profile.js
- dapps/marketplace/src/pages/onboard/SignIn.js
- dapps/marketplace/src/pages/user/Profile.js
[Link to test build](https://originprotocol.github.io/test-builds/shah)
> DApp fixes

- devops/kubernetes/charts/ethereum-network/letsencrypt-prod.yaml
- devops/kubernetes/charts/ethereum-network/templates/ingress.yaml
- devops/kubernetes/helmfile/ethereum-network.yaml
- devops/kubernetes/values/ethereum-network/nginx-ingress/values.yaml
Upgrades cert-manager to fix SSL issuance for our testnet.
> Upgrades for cert-manager in ethereum-network chart

- infra/token-transfer-server/src/scripts/enqueue_test_transfers.js
Simple script for enqueueing transfers for testing purposes.
> [T3] Script for enqueueing test transfers

- infra/token-transfer-server/src/config.js
- infra/token-transfer-server/src/lib/transfer.js
- packages/token/src/token.js
Moved gas price multiplier to token package.
> [T3] Gas price multiplier take two

- infra/token-transfer-server/src/app.js
- infra/token-transfer-server/src/lib/transfer.js
- infra/token-transfer-server/src/tasks/transfer.js
- infra/token-transfer-server/test/lib/transfer.test.js
- infra/token-transfer-server/test/task/transfer.test.js
Instantiate it in the main app startup and pass it to the required functions to deal with excessive web3 requests.
> Use a single @origin/token instance in T3

- dapps/shop/backend/README.md
- dapps/shop/backend/deploy_heroku.sh
- dapps/shop/backend/listener.js
- dapps/shop/backend/tstEnc.js
- dapps/shop/backend/utils/emailer.js
Backend deploy script for Heroku.  Also includes:
- base64 encoded PGP key fallback
- support for SendGrid u/p for auto-configuration on Heroku
> dshop - Heroku deploy script for backend

- dapps/marketplace/src/pages/onboard/RewardsSignUp.js
> Don't redirect if user is on onboarding from landing page

- infra/token-transfer-client/src/components/Navigation.js
- infra/token-transfer-client/src/components/PrivateRoute.js
- infra/token-transfer-client/src/components/VestingCard.js
- infra/token-transfer-client/src/components/pages/Dashboard.js
- Hide bonus tokens options for team
- Hide revised token schedule for team
> T3 UI changes for team

- infra/token-transfer-server/src/controllers/account.js
Have T3 server send IP and country code when calling the website's mailing-list/join endpoint so that we can segment our mailing list and insight data by country.
> [T3 server] Send IP and country code to Insight when adding a wallet

- devops/kubernetes/charts/origin/templates/graphql.ingress.yaml
- devops/kubernetes/charts/origin/templates/growth.ingress.yaml
> Increases ingress rate limits for graphql and growth

- infra/ipfs-proxy/src/app.js
> Add request logging to ipfs-proxy

- devops/kubernetes/charts/origin/templates/ipfs.ingress.yaml
Not a cure, but could alleviate the pressure?
> IPFS Ingress Timeout adjustment

- infra/auth-server/dev.env
- infra/auth-server/src/utils/verify-sign.js
> Increase clock difference offset to 15 mins

- mobile/src/constants.js
- mobile/src/screens/settings.js
Lots of people are changing this to `Origin` for some reason. This is an untested, blind change that I hope isn't misguided. 🤞
> Change Network Displayed Name

- dapps/marketplace/src/pages/growth/Welcome.js
minor alignment fix on welcome screen
> minor alignment fix on welcome screen

- dapps/marketplace/src/components/SignIn.js
- dapps/marketplace/src/pages/growth/Welcome.js
- Disables sign in button until the wallet has loaded
- Redirects to onboarding if no wallet is present
Fixes #4130
> Take to onboarding if no wallet is present during signin

- infra/bridge/telegram.md
> Add a readme for Telegram webhooks and bot

- infra/bridge/src/utils/exchange-rate.js
- mobile/src/utils/exchangeRate.js
- Fixes exchange rate info handed out by bridge when fiat currency pair is not USD
- updates fallback exchange rates
Fixes: https://github.com/OriginProtocol/origin/issues/4209
> Sparrow dom/bridge exchange rate info

- dapps/marketplace/public/template.html
> Defer hiding zendesk widget trigger

- dapps/marketplace/src/pages/identity/TelegramAttestation.js
- packages/graphql/src/mutations/identity/deployIdentity.js
- packages/graphql/src/resolvers/attestations/checkTelegramStatus.js
Logs a few things to Sentry that should help in identifying and fixing #4217
> Add some logging for #4217

- mobile/ios/OriginMarketplace/Info.plist
- mobile/package.json
- mobile/src/constants.js
> Tomlinton/mobile 0.30.x

- infra/auth-server/src/app.js
- infra/bridge/src/app.js
- infra/dapp-creator-server/src/app.js
- infra/messaging/src/index.js
- infra/notifications/src/app.js
- infra/relayer/src/app.js
- infra/token-transfer-server/src/app.js
- packages/graphql/src/mutations/identity/deployIdentity.js
> Fix unit tests broken by a careless engineer

- dapps/marketplace/public/template.html
- dapps/marketplace/src/pages/App.js
> Remove zendesk chat icon flicker with hacky code

- docker-compose.yml
- packages/graphql/src/mutations/identity/deployIdentity.js
> fix docker environment setup

- infra/bridge/src/utils/process-telegram-message.js
This directs people to the new help center if they're struggling with our Telegram bot. 🤖
> Telegram Bot Reply

- dapps/marketplace/src/pages/listing/PaymentMethods.js
Fixes a bug where listing has no accepted tokens listed. Couldn't reproduce a way to create such listings. So when this happens we allow for ETH payments. 
Fixes: https://github.com/OriginProtocol/origin/issues/4039#event-2955492198
> Payments fix

- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- dapps/marketplace/src/pages/messaging/SendMessage.js
- packages/graphql/src/utils/currencies.js
- packages/messaging-client/src/Messaging.js
- Fix the bug that prevents the user sending two messages in succession
- Change USDT decimals from 18 to 6
> Fix messaging and USDT decimals

- infra/messaging/package.json
- package.json
- packages/messaging-client/package.json
Hopefully will fix the messaging breakage in prod...
> Downgrade and freeze secp256k1

- devops/kubernetes/charts/origin/templates/_helpers.tpl
- devops/kubernetes/charts/origin/templates/ipfs-issuer.statefulset.yaml
Fixes a bug and points the issuer at the right spot
> ipfs-issuer fix and port change

- packages/graphql/test/availability-calculator-hourly.js
> Fix fractional hourly calculator tests

- packages/mobile-bridge/src/index.js
> Linting error

- infra/growth/package.json
- infra/growth/src/apollo/app.js
- infra/growth/src/resources/eventLogger.js
Get params for the log_event route from the request's body. Also log IP and fingerprint data in the registration event.
> [Growth] log_event route: extract params from the POST body

- dapps/marketplace/src/pages/App.js
This does not seem to have any impact on the UI across all browsers
and the different breakpoints
Broken
Fixed
> Remove height 100% from App.js

- dapps/shop/backend/data/migrations/20200226172508-createTables.js
- dapps/shop/backend/routes/auth.js
- dapps/shop/backend/routes/tx.js
- dapps/shop/backend/utils/sellers.js
> Small fixes for dshop backend

- dapps/shop/backend/utils/validators.js
> Less logging

- dapps/marketplace/src/pages/growth/WithEnrolmentModal.js
- infra/growth/src/util/locationInfo.js
> [Growth] Remove US from restricted list

- infra/notifications/.gitignore
- infra/notifications/src/app.js
- infra/notifications/src/dupeTools.js
- infra/notifications/src/mobilePush.js
- infra/notifications/src/utils/firebaseMessaging.js
- infra/notifications/test/mobile-push.test.js
Part of "Notifications Admin tool"
Adds endpoints for sending push notifications to
- Devices owned by an address
- Multicast to an array of addresses
- To everyone who has installed the Origin Marketplace app
> Changes for notifications admin tool

- infra/notifications/src/app.js
- infra/notifications/src/mobilePush.js
Adds methods to send push notification based country/language on codes and adds an endpoint to return all supported language and country codes.
> Add support for targetting language/country

- infra/notifications/src/app.js
- infra/notifications/src/mobilePush.js
Adds some debug statements and removes unused code
> Add debug statements in the notifications server

- infra/notifications/src/mobilePush.js
Seems like I broke push notification for Android in a past PR. This PR fixes it.
> Fix push notifications on Android

- infra/token-transfer-server/src/config.js
- infra/token-transfer-server/src/lib/transfer.js
- Fix T3 balance check when executing transfers
- Fix issue when LARGE_TRANSFER_DELAY_MINUTES set to "0" via environment variable
> Execute transfer logic fixes

- devops/dockerfiles/snippets/origin-dapp-creator-issuer/nginx.conf.template
- devops/kubernetes/charts/origin/templates/ipfs.ingress.yaml
Move IPFS security headers to nginx.config
> IPFS headers

- infra/relayer/src/relayer.js
- infra/relayer/src/scripts/predict-address.js
- mobile/src/constants.js
- packages/graphql/src/configs/mainnet.js
Migration to geth based Alchemy endpoints.
Note: not ideal to have those keys in the codebase but I'm not going to worry about it since it has not been an issue so far.
> Update Alchemy endpoints to v2

- devops/dockerfiles/snippets/origin-dapp-creator-issuer/nginx.conf.template
> Small change to Content-Security-Policy header for issuer

- dapps/shop/backend/scripts/configs.js
- dapps/shop/src/pages/admin/settings/Console.js
- dapps/shop/src/pages/super-admin/shops/CreateListing.js
- dapps/shop/src/pages/super-admin/shops/Shops.js
- dapps/shop/src/utils/listing.js
- packages/services/package.json
- yarn.lock
Add a button to the DShop admin > Settings > Console panel that allows to update the listing associated with a shop by calling the marketplace contract.
The listing data that is published includes a field "shopIpfsHash" that points to the IPFS hash of the dshop.
This feature enables any external system to listen for the ListingUpdated events to get notified when a dshop gets updated. For example, an ETL pipeline could listen to those events and trigger a re-indexing of the associated dshop's catalog.
> DShop admin: add a button to the console to emit a ListingUpdated event 

- mobile/README.md
- mobile/src/constants.js
> [mobile] Replace hardcoded provider url with env var

- devops/kubernetes/charts/origin-experimental/templates/_helpers.tpl
- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-rinkeby.statefulset.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-redis-mainnet.configmap.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-redis-mainnet.service.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-redis-mainnet.statefulset.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-redis-rinkeby.configmap.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-redis-rinkeby.service.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-redis-rinkeby.statefulset.yaml
- devops/kubernetes/charts/origin-experimental/values.yaml
Adds redis cluuters for the dshop backends.
> Redis clusters for dshop backends

- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-mainnet.ingress.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-mainnet.statefulset.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-rinkeby.ingress.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-rinkeby.statefulset.yaml
Some kubernetes lifecycle adjustments for dshop backend to eliminiate 502s and 503s.
> Dshop backend lifecycle adjustments

- devops/kubernetes/charts/origin-experimental/templates/_helpers.tpl
- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-mainnet.balancer.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-rinkeby.balancer.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-issuer-mainnet.service.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-issuer-mainnet.statefulset.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-issuer-rinkeby.service.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-issuer-rinkeby.statefulset.yaml
- devops/kubernetes/charts/origin-experimental/values.yaml
- devops/kubernetes/values/origin-experimental/values.yaml
Adds AutoSSL issuer and balancer to handle serving dshop dapps from backend.  These assets have already been deployed so I'm going to merge this immediately so the repo is in sync with the cluster.
> Adds issuer and balancer for dshop

- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-mainnet.statefulset.yaml
- devops/kubernetes/charts/origin-experimental/templates/dshop-backend-rinkeby.statefulset.yaml
> Set EXTERNAL_IP env var for dshop backends

- devops/dockerfiles/snippets/origin-dapp-creator-issuer/nginx.conf.template
- devops/kubernetes/charts/origin-experimental/templates/dshop-issuer-mainnet.statefulset.yaml
Adds img-src CSP for dshop backend AutoSSL issuer.
> Fixes CSP issue with dshop backend with issuer

- devops/dockerfiles/snippets/origin-dapp-creator-issuer/nginx.conf.template
Dshop's theme editor loads the preview in an iframe.
> Allowing loading Dshop in iframes

- devops/dockerfiles/snippets/origin-dapp-creator-issuer/nginx.conf.template
> Dshop theme editor needs issuer header change

- infra/token-transfer-server/src/shared.js
> Fix timezone issue

- devops/dockerfiles/snippets/origin-dapp-creator-issuer/nginx.conf.template
> Set Permissions-Policy in origin-dapp-creator-issuer nginx.conf

- docker-compose.test.yml
- [ x] Test your work and double-check to confirm that you didn't break anything
- [ x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ x] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ x] Update any relevant …
> fixed test-compose volume mispelling
